const T = (bks: string, tr: string, uk: string, ro: string, ar: string) => ({ bks, tr, uk, ro, ar });
const A = (id: string, text: string, is_correct: boolean, position: number) => ({ id, text, is_correct, position });
const H = (bks: string, tr: string, uk: string, ro: string, ar: string) => ({ help: T(bks, tr, uk, ro, ar) });

export const bakeryA2Override = {
  lesson: {
    id: "22222222-2222-2222-2222-222222222223",
    slug: "baeckerei-a2",
    title: "In der Bäckerei",
    description: "A2: Routinen, Vorlieben, Mengen, Alternativen, Empfehlungen und einfache Probleme beim Einkauf verständlich besprechen.",
    level: "A2",
    region: "de",
    category_slug: "alltag",
    subcategory_slug: "baeckerei",
    topic_slug: "baeckerei",
    topic_title: "In der Bäckerei",
    duration_seconds: 3000,
    thumbnail_key: "baeckerei",
    video_url: null,
    is_premium: true,
    status: "published",
    popularity: 99,
    grammar_topics: ["weil und deshalb", "welcher / welche / welches", "Komparativ", "Mengenangaben", "Perfekt im Alltag", "Modalverben", "Wünsche und Alternativen", "freundlich nachfragen"],
    grammar_notes: [
      { title: "A2: mehr als nur bestellen", explanation: "Auf A2 kann man Wünsche genauer beschreiben, Alternativen vergleichen, nachfragen und einfache Gründe nennen.", examples: ["Ich hätte gern etwas, das nicht zu süß ist.", "Welcher Kuchen ist heute frisch?", "Ich nehme das kleinere Brot, weil wir nur zu zweit sind."] },
      { title: "weil / deshalb", explanation: "Mit weil nennt man einen Grund. Mit deshalb nennt man eine Folge.", examples: ["Ich nehme nur ein kleines Brot, weil wir zu zweit sind.", "Ich habe wenig Bargeld, deshalb zahle ich mit Karte."] },
      { title: "Komparativ", explanation: "Mit -er und als vergleicht man Dinge.", examples: ["Das Roggenbrot ist kräftiger als das Weißbrot.", "Der Apfelkuchen ist weniger süß als die Torte."] },
      { title: "Perfekt für kurze Alltagserfahrungen", explanation: "A2-Lernende können kurz sagen, was schon passiert ist.", examples: ["Ich habe gestern dieses Brot gekauft.", "Wir haben die Torte schon probiert."] }
    ],
    place_items: [
      { german_text: "Die Verkäuferin steht hinter der Theke.", preposition: "hinter", image_key: "baeck-ill-01", translations: T("Prodavačica stoji iza pulta.", "Satıcı tezgâhın arkasında.", "Продавчиня за прилавком.", "Vânzătoarea este în spatele tejghelei.", "البائعة خلف المنضدة.") },
      { german_text: "Die Kuchen stehen nebeneinander in der Auslage.", preposition: "nebeneinander", image_key: "baeck-ill-03", translations: T("Kolači stoje jedan pored drugog u vitrini.", "Pastalar vitrinde yan yana.", "Торти стоять поруч у вітрині.", "Prăjiturile sunt una lângă alta în vitrină.", "الكعكات بجانب بعضها في الواجهة.") },
      { german_text: "Das Kartenlesegerät steht auf der Theke.", preposition: "auf", image_key: "baeck-ill-09", translations: T("Čitač kartica je na pultu.", "Kart okuyucu tezgâhın üstünde.", "Термінал стоїть на прилавку.", "Cititorul de card este pe tejghea.", "جهاز البطاقة على المنضدة.") }
    ]
  },

  scenes: [
    { id: "a2-s1", position: 1, image_key: "baeck-ill-02", german_text: "Mara schaut sich die Auslage an und überlegt, was sie kaufen möchte.", translations: T("Mara gleda vitrinu i razmišlja šta želi kupiti.", "Mara vitrine bakıp ne alacağını düşünüyor.", "Мара дивиться на вітрину й думає, що купити.", "Mara se uită la vitrină și se gândește ce să cumpere.", "تنظر مارا إلى الواجهة وتفكر ماذا ستشتري.") },
    { id: "a2-s2", position: 2, image_key: "baeck-ill-01", german_text: "Die Verkäuferin fragt, ob sie Mara helfen kann.", translations: T("Prodavačica pita može li pomoći Mari.", "Satıcı Mara'ya yardım edip edemeyeceğini soruyor.", "Продавчиня питає, чи може допомогти Марі.", "Vânzătoarea întreabă dacă o poate ajuta pe Mara.", "تسأل البائعة إن كانت تستطيع مساعدة مارا.") },
    { id: "a2-s3", position: 3, image_key: "baeck-ill-03", german_text: "Mara sucht etwas Süßes, das nicht zu schwer und nicht zu süß ist.", translations: T("Mara traži nešto slatko što nije preteško ni preslatko.", "Mara çok ağır ve çok tatlı olmayan bir şey arıyor.", "Мара шукає щось солодке, але не надто важке й солодке.", "Mara caută ceva dulce, dar nu prea greu și nu prea dulce.", "تبحث مارا عن شيء حلو لكنه ليس ثقيلاً أو شديد الحلاوة.") },
    { id: "a2-s4", position: 4, image_key: "baeck-ill-03", german_text: "Die Verkäuferin empfiehlt ihr Apfelkuchen und erklärt, dass er heute frisch gebacken wurde.", translations: T("Prodavačica preporučuje kolač od jabuka i kaže da je danas svježe pečen.", "Satıcı elmalı pastayı öneriyor ve bugün taze piştiğini söylüyor.", "Продавчиня радить яблучний пиріг і каже, що його сьогодні свіжо спекли.", "Vânzătoarea recomandă prăjitura cu mere și spune că a fost coaptă azi.", "توصي البائعة بكعكة التفاح وتقول إنها خُبزت اليوم.") },
    { id: "a2-s5", position: 5, image_key: "baeck-ill-04", german_text: "Mara entscheidet sich für ein Stück und fragt zusätzlich nach einem Brot für das Abendessen.", translations: T("Mara bira jedan komad i dodatno pita za hljeb za večeru.", "Mara bir dilim seçiyor ve akşam yemeği için ekmek soruyor.", "Мара обирає шматок і ще питає про хліб на вечерю.", "Mara alege o felie și mai întreabă de o pâine pentru cină.", "تختار مارا قطعة وتسأل أيضًا عن خبز للعشاء.") },
    { id: "a2-s6", position: 6, image_key: "baeck-ill-06", german_text: "Die Verkäuferin zeigt zwei Brotsorten und erklärt kurz den Unterschied.", translations: T("Prodavačica pokazuje dvije vrste hljeba i kratko objašnjava razliku.", "Satıcı iki ekmek türü gösterip farkı kısaca açıklıyor.", "Продавчиня показує два види хліба й коротко пояснює різницю.", "Vânzătoarea arată două tipuri de pâine și explică pe scurt diferența.", "تعرض البائعة نوعين من الخبز وتشرح الفرق باختصار.") },
    { id: "a2-s7", position: 7, image_key: "baeck-ill-06", german_text: "Mara nimmt das kleinere Roggenbrot, weil sie heute nur zu zweit essen.", translations: T("Mara uzima manji raženi hljeb jer danas jedu samo dvoje.", "Mara daha küçük çavdar ekmeğini alıyor çünkü bugün sadece iki kişiler.", "Мара бере менший житній хліб, бо сьогодні їдять лише вдвох.", "Mara ia pâinea de secară mai mică pentru că azi mănâncă doar două persoane.", "تأخذ مارا خبز الجاودار الأصغر لأنهما سيأكلان شخصين فقط.") },
    { id: "a2-s8", position: 8, image_key: "baeck-ill-07", german_text: "Sie möchte das Brot geschnitten, damit sie es später leichter einfrieren kann.", translations: T("Želi narezani hljeb da ga kasnije lakše zamrzne.", "Ekmeği dilimlenmiş istiyor, böylece sonra daha kolay dondurabilir.", "Вона хоче нарізаний хліб, щоб потім легше заморозити.", "Vrea pâinea feliată ca să o poată congela mai ușor.", "تريد الخبز مقطعًا كي تتمكن من تجميده بسهولة لاحقًا.") },
    { id: "a2-s9", position: 9, image_key: "baeck-ill-08", german_text: "An der Kasse fragt Mara nach dem Gesamtpreis und nach einer kleinen Tüte.", translations: T("Na kasi Mara pita za ukupnu cijenu i malu vrećicu.", "Kasada Mara toplam fiyatı ve küçük bir poşeti soruyor.", "На касі Мара питає загальну ціну й маленький пакет.", "La casă, Mara întreabă prețul total și cere o pungă mică.", "عند الصندوق تسأل مارا عن السعر الإجمالي وكيس صغير.") },
    { id: "a2-s10", position: 10, image_key: "baeck-ill-09", german_text: "Sie bezahlt mit Karte, weil sie nicht genug Bargeld dabeihat.", translations: T("Plaća karticom jer nema dovoljno gotovine.", "Yeterince nakdi olmadığı için kartla ödüyor.", "Вона платить карткою, бо не має достатньо готівки.", "Plătește cu cardul pentru că nu are suficienți bani cash.", "تدفع بالبطاقة لأنها لا تحمل نقدًا كافيًا.") },
    { id: "a2-s11", position: 11, image_key: "baeck-ill-10", german_text: "Die Verkäuferin gibt ihr die Tüte und den Kassenbon.", translations: T("Prodavačica joj daje vrećicu i račun.", "Satıcı ona poşeti ve fişi veriyor.", "Продавчиня дає їй пакет і чек.", "Vânzătoarea îi dă punga și bonul.", "تعطيها البائعة الكيس والإيصال.") },
    { id: "a2-s12", position: 12, image_key: "baeck-ill-10", german_text: "Mara bedankt sich und sagt, dass sie den Apfelkuchen beim nächsten Mal wieder kaufen möchte.", translations: T("Mara se zahvaljuje i kaže da će sljedeći put opet kupiti kolač od jabuka.", "Mara teşekkür ediyor ve bir dahaki sefere elmalı pastayı yine almak istediğini söylüyor.", "Мара дякує й каже, що наступного разу знову купить яблучний пиріг.", "Mara mulțumește și spune că data viitoare va cumpăra din nou prăjitura cu mere.", "تشكر مارا وتقول إنها تريد شراء كعكة التفاح مرة أخرى في المرة القادمة.") }
  ],

  vocab: [
    ["die Empfehlung", "Nomen", "die", "die Empfehlungen", "Haben Sie eine Empfehlung?", T("preporuka", "öneri", "рекомендація", "recomandare", "توصية")],
    ["die Brotsorte", "Nomen", "die", "die Brotsorten", "Welche Brotsorte ist kräftiger?", T("vrsta hljeba", "ekmek çeşidi", "вид хліба", "tip de pâine", "نوع الخبز")],
    ["das Roggenbrot", "Nomen", "das", "die Roggenbrote", "Ich nehme ein Roggenbrot.", T("raženi hljeb", "çavdar ekmeği", "житній хліб", "pâine de secară", "خبز الجاودار")],
    ["frisch gebacken", "Wendung", null, null, "Der Kuchen ist heute frisch gebacken.", T("svježe pečeno", "taze pişmiş", "свіжоспечений", "proaspăt copt", "مخبوز طازج")],
    ["nicht zu süß", "Wendung", null, null, "Ich suche etwas, das nicht zu süß ist.", T("ne previše slatko", "çok tatlı olmayan", "не надто солодкий", "nu prea dulce", "ليس حلوًا جدًا")],
    ["kleiner / größer", "Adjektiv", null, null, "Ich nehme das kleinere Brot.", T("manji / veći", "daha küçük / daha büyük", "менший / більший", "mai mic / mai mare", "أصغر / أكبر")],
    ["kräftig", "Adjektiv", null, null, "Roggenbrot schmeckt kräftiger.", T("jak okus", "yoğun", "насичений", "intens", "قوي النكهة")],
    ["der Unterschied", "Nomen", "der", "die Unterschiede", "Was ist der Unterschied?", T("razlika", "fark", "різниця", "diferență", "فرق")],
    ["einfrieren", "Verb", null, null, "Ich friere das Brot ein.", T("zamrznuti", "dondurmak", "заморожувати", "a congela", "يجمّد")],
    ["der Gesamtpreis", "Nomen", "der", "die Gesamtpreise", "Wie hoch ist der Gesamtpreis?", T("ukupna cijena", "toplam fiyat", "загальна ціна", "preț total", "السعر الإجمالي")],
    ["der Kassenbon", "Nomen", "der", "die Kassenbons", "Kann ich den Kassenbon haben?", T("račun", "fiş", "чек", "bon", "إيصال")],
    ["Bargeld", "Nomen", "das", "—", "Ich habe nicht genug Bargeld dabei.", T("gotovina", "nakit", "готівка", "numerar", "نقد")],
    ["dabeihaben", "Verb", null, null, "Ich habe meine Karte dabei.", T("imati sa sobom", "yanında bulundurmak", "мати при собі", "a avea la tine", "يحمل معه")],
    ["empfehlen", "Verb", null, null, "Was können Sie empfehlen?", T("preporučiti", "önermek", "рекомендувати", "a recomanda", "يوصي")],
    ["probieren", "Verb", null, null, "Ich habe den Kuchen schon probiert.", T("probati", "denemek", "спробувати", "a încerca", "يجرّب")],
    ["weniger", "Adverb", null, null, "Der Kuchen ist weniger süß.", T("manje", "daha az", "менше", "mai puțin", "أقل")],
    ["deshalb", "Konjunktion", null, null, "Ich habe wenig Bargeld, deshalb zahle ich mit Karte.", T("zato", "bu yüzden", "тому", "de aceea", "لذلك")],
    ["weil", "Konjunktion", null, null, "Ich nehme das kleine Brot, weil wir zu zweit sind.", T("jer", "çünkü", "тому що", "pentru că", "لأن")]
  ].map((v, i) => ({ id: `a2-v${i + 1}`, position: i + 1, term: v[0], word_class: v[1], article: v[2], plural: v[3], example: v[4], example_translations: v[5], translations: v[5], collocations: [] })),

  dialog: [
    [1, "Eine Empfehlung bekommen", "V", "Verkäuferin", "Guten Morgen. Kann ich Ihnen helfen?", T("Dobro jutro. Mogu li vam pomoći?", "Günaydın. Yardımcı olabilir miyim?", "Доброго ранку. Чим можу допомогти?", "Bună dimineața. Vă pot ajuta?", "صباح الخير. هل يمكنني مساعدتك؟")],
    [1, "Eine Empfehlung bekommen", "K", "Kundin", "Ja, gern. Ich suche etwas Süßes, aber nicht zu süß. Was können Sie empfehlen?", T("Da. Tražim nešto slatko, ali ne preslatko. Šta preporučujete?", "Evet. Tatlı ama çok tatlı olmayan bir şey arıyorum. Ne önerirsiniz?", "Так. Я шукаю щось солодке, але не надто солодке. Що порадите?", "Da. Caut ceva dulce, dar nu prea dulce. Ce recomandați?", "نعم. أبحث عن شيء حلو لكن ليس شديد الحلاوة. ماذا تنصحين؟")],
    [1, "Eine Empfehlung bekommen", "V", "Verkäuferin", "Unser Apfelkuchen ist heute frisch gebacken und weniger süß als die Schokotorte.", T("Naš kolač od jabuka je danas svježe pečen i manje sladak od čokoladne torte.", "Elmalı pastamız bugün taze ve çikolatalı pastadan daha az tatlı.", "Наш яблучний пиріг сьогодні свіжий і менш солодкий, ніж шоколадний торт.", "Prăjitura cu mere e proaspătă azi și mai puțin dulce decât tortul de ciocolată.", "كعكة التفاح طازجة اليوم وأقل حلاوة من كعكة الشوكولاتة.")],
    [1, "Eine Empfehlung bekommen", "K", "Kundin", "Dann nehme ich ein Stück Apfelkuchen. Und welches Brot ist gut fürs Abendessen?", T("Onda uzimam komad kolača od jabuka. A koji hljeb je dobar za večeru?", "O zaman bir dilim elmalı pasta alayım. Akşam yemeği için hangi ekmek iyi?", "Тоді я візьму шматок яблучного пирога. А який хліб добрий на вечерю?", "Atunci iau o felie de prăjitură cu mere. Și ce pâine e bună pentru cină?", "إذن سأأخذ قطعة من كعكة التفاح. وأي خبز مناسب للعشاء؟")],
    [1, "Eine Empfehlung bekommen", "V", "Verkäuferin", "Wenn Sie etwas Kräftigeres mögen, würde ich das Roggenbrot empfehlen.", T("Ako volite nešto jačeg okusa, preporučila bih raženi hljeb.", "Daha yoğun bir şey seviyorsanız çavdar ekmeğini öneririm.", "Якщо любите більш насичений смак, раджу житній хліб.", "Dacă vă place un gust mai intens, recomand pâinea de secară.", "إذا كنت تحبين نكهة أقوى، أنصح بخبز الجاودار.")],
    [1, "Eine Empfehlung bekommen", "K", "Kundin", "Gut, dann nehme ich das kleinere. Wir sind heute nur zu zweit.", T("Dobro, onda uzimam manji. Danas smo samo dvoje.", "Tamam, o zaman küçüğünü alayım. Bugün sadece iki kişiyiz.", "Добре, тоді візьму менший. Сьогодні нас лише двоє.", "Bine, atunci îl iau pe cel mai mic. Azi suntem doar doi.", "حسنًا، سأأخذ الأصغر. نحن شخصان فقط اليوم.")],
    [1, "Eine Empfehlung bekommen", "V", "Verkäuferin", "Möchten Sie es geschnitten?", T("Želite li ga narezanog?", "Dilimlenmiş ister misiniz?", "Нарізати?", "Doriți să fie feliată?", "هل تريدينه مقطعًا؟")],
    [1, "Eine Empfehlung bekommen", "K", "Kundin", "Ja, bitte. Dann kann ich einen Teil einfrieren.", T("Da, molim. Onda mogu dio zamrznuti.", "Evet lütfen. Böylece bir kısmını dondurabilirim.", "Так, будь ласка. Тоді частину зможу заморозити.", "Da, vă rog. Așa pot congela o parte.", "نعم من فضلك. عندها أستطيع تجميد جزء منه.")],

    [2, "An der Kasse", "V", "Verkäuferin", "Das macht zusammen vierzehn Euro zwanzig.", T("Ukupno je četrnaest eura i dvadeset.", "Toplam on dört euro yirmi.", "Разом чотирнадцять євро двадцять.", "În total sunt paisprezece euro și douăzeci.", "المجموع أربعة عشر يورو وعشرون سنتًا.")],
    [2, "An der Kasse", "K", "Kundin", "Ich habe heute nicht genug Bargeld dabei. Kann ich mit Karte zahlen?", T("Danas nemam dovoljno gotovine. Mogu li platiti karticom?", "Bugün yeterince nakdim yok. Kartla ödeyebilir miyim?", "Сьогодні в мене недостатньо готівки. Можна карткою?", "Nu am suficient numerar la mine azi. Pot plăti cu cardul?", "ليس معي نقد كافٍ اليوم. هل يمكنني الدفع بالبطاقة؟")],
    [2, "An der Kasse", "V", "Verkäuferin", "Natürlich. Möchten Sie den Kassenbon?", T("Naravno. Želite li račun?", "Tabii. Fişi ister misiniz?", "Звичайно. Вам потрібен чек?", "Desigur. Doriți bonul?", "بالطبع. هل تريدين الإيصال؟")],
    [2, "An der Kasse", "K", "Kundin", "Ja, bitte. Und könnten Sie mir noch eine kleine Tüte geben?", T("Da, molim. I možete li mi dati malu vrećicu?", "Evet lütfen. Bir de küçük poşet verebilir misiniz?", "Так, будь ласка. І можете дати маленький пакет?", "Da, vă rog. Și îmi puteți da o pungă mică?", "نعم من فضلك. وهل يمكنك إعطائي كيسًا صغيرًا؟")],
    [2, "An der Kasse", "V", "Verkäuferin", "Gerne. Hier sind die Tüte und der Bon.", T("Naravno. Evo vrećice i računa.", "Tabii. İşte poşet ve fiş.", "Звичайно. Ось пакет і чек.", "Sigur. Iată punga și bonul.", "بكل سرور. هذا الكيس والإيصال.")],
    [2, "An der Kasse", "K", "Kundin", "Danke. Der Apfelkuchen war letztes Mal sehr gut. Den nehme ich bestimmt wieder.", T("Hvala. Kolač od jabuka je prošli put bio odličan. Sigurno ću ga opet uzeti.", "Teşekkürler. Elmalı pasta geçen sefer çok iyiydi. Kesin yine alırım.", "Дякую. Минулого разу яблучний пиріг був дуже смачний. Обов'язково візьму знову.", "Mulțumesc. Prăjitura cu mere a fost foarte bună data trecută. Sigur o voi lua din nou.", "شكرًا. كانت كعكة التفاح ممتازة في المرة الماضية. سأشتريها بالتأكيد مرة أخرى.")]
  ].map((d, i) => ({ id: `a2-d${i + 1}`, position: i + 1, dialog_index: d[0], dialog_title: d[1], speaker: d[2], speaker_role: d[3], german_text: d[4], translations: d[5] })),

  questions: [
    { id: "a2-g1", position: 1, kind: "single_choice", section: "grammar", prompt: "Welche Formulierung passt zu A2, wenn man eine Empfehlung möchte?", explanation: "A2 kann Wünsche genauer beschreiben und nach Empfehlungen fragen.", data: H("Kako pristojno tražiti preporuku?", "Öneri nasıl istenir?", "Як попросити рекомендацію?", "Cum ceri o recomandare?", "كيف تطلب توصية؟"), quiz_answers: [A("a", "Ich suche etwas, das nicht zu süß ist. Was können Sie empfehlen?", true, 1), A("b", "Kuchen!", false, 2), A("c", "Ich sein süß.", false, 3)] },
    { id: "a2-g2", position: 2, kind: "gap_select", section: "grammar", prompt: "Ich nehme das kleinere Brot, ___ wir heute nur zu zweit sind.", explanation: "weil nennt den Grund.", data: { options: ["weil", "deshalb", "aber", "oder"], ...H("jer = weil", "çünkü = weil", "тому що = weil", "pentru că = weil", "لأن = weil") }, quiz_answers: [A("a", "weil", true, 1)] },
    { id: "a2-g3", position: 3, kind: "gap_select", section: "grammar", prompt: "Ich habe wenig Bargeld, ___ zahle ich mit Karte.", explanation: "deshalb nennt die Folge.", data: { options: ["deshalb", "weil", "obwohl", "denn"], ...H("zato = deshalb", "bu yüzden = deshalb", "тому = deshalb", "de aceea = deshalb", "لذلك = deshalb") }, quiz_answers: [A("a", "deshalb", true, 1)] },
    { id: "a2-g4", position: 4, kind: "single_choice", section: "grammar", prompt: "Welcher Satz vergleicht zwei Produkte?", explanation: "Der Komparativ vergleicht.", data: H("Koja rečenica poredi dva proizvoda?", "Hangi cümle iki ürünü karşılaştırıyor?", "Яке речення порівнює два продукти?", "Ce propoziție compară două produse?", "أي جملة تقارن منتجين؟"), quiz_answers: [A("a", "Das Roggenbrot ist kräftiger als das Weißbrot.", true, 1), A("b", "Ich nehme Brot.", false, 2), A("c", "Guten Morgen.", false, 3)] },
    { id: "a2-g5", position: 5, kind: "single_choice", section: "grammar", prompt: "Welche Form ist korrekt?", explanation: "Perfekt: ich habe gekauft.", data: H("Koja je Perfekt forma?", "Perfekt hangisi?", "Яка форма Perfekt?", "Care este forma de perfect compus?", "ما صيغة الماضي؟"), quiz_answers: [A("a", "Ich habe gestern dieses Brot gekauft.", true, 1), A("b", "Ich habe gestern dieses Brot kaufen.", false, 2), A("c", "Ich gekauft Brot gestern.", false, 3)] },
    { id: "a2-u1", position: 20, kind: "single_choice", section: "uebungen", prompt: "Mara möchte etwas Leichtes und nicht zu Süßes. Was sagt sie?", explanation: "Sie beschreibt eine Vorliebe genauer.", data: H("Mara želi nešto lagano i ne preslatko.", "Mara hafif ve çok tatlı olmayan bir şey istiyor.", "Мара хоче щось легке й не надто солодке.", "Mara vrea ceva ușor și nu prea dulce.", "مارا تريد شيئًا خفيفًا وغير شديد الحلاوة."), quiz_answers: [A("a", "Ich suche etwas Süßes, aber nicht zu süß.", true, 1), A("b", "Ich möchte alles.", false, 2), A("c", "Ist hier ein Bahnhof?", false, 3)] },
    { id: "a2-u2", position: 21, kind: "single_choice", section: "uebungen", prompt: "Die Verkäuferin sagt: „Das Roggenbrot ist kräftiger.“ Was meint sie?", explanation: "kräftiger beschreibt einen intensiveren Geschmack.", data: H("Šta znači kräftiger?", "kräftiger ne demek?", "Що означає kräftiger?", "Ce înseamnă kräftiger?", "ماذا تعني kräftiger؟"), quiz_answers: [A("a", "Es hat einen intensiveren Geschmack.", true, 1), A("b", "Es ist kostenlos.", false, 2), A("c", "Es ist flüssig.", false, 3)] },
    { id: "a2-u3", position: 22, kind: "single_choice", section: "uebungen", prompt: "Warum möchte Mara das Brot geschnitten?", explanation: "Sie möchte einen Teil einfrieren.", data: H("Zašto želi narezani hljeb?", "Neden dilimlenmiş istiyor?", "Чому вона хоче нарізаний хліб?", "De ce îl vrea feliat?", "لماذا تريده مقطعًا؟"), quiz_answers: [A("a", "Damit sie einen Teil leichter einfrieren kann.", true, 1), A("b", "Weil sie keinen Kuchen mag.", false, 2), A("c", "Weil die Bäckerei schließt.", false, 3)] },
    { id: "a2-u4", position: 23, kind: "sentence_order", section: "uebungen", prompt: "Baue die Frage richtig auf.", explanation: "Was können Sie empfehlen?", data: { words: ["Was", "können", "Sie", "empfehlen?"], ...H("Šta možete preporučiti?", "Ne önerebilirsiniz?", "Що можете порадити?", "Ce puteți recomanda?", "ماذا يمكنك أن توصي؟") }, quiz_answers: [] },
    { id: "a2-u5", position: 24, kind: "true_false", section: "uebungen", prompt: "Auf A2 kann man einfache Gründe und Vorlieben nennen.", explanation: "Richtig.", data: H("Na A2 možeš navesti jednostavne razloge i preference.", "A2'de basit neden ve tercihler söylenebilir.", "На A2 можна називати прості причини й уподобання.", "La A2 poți exprima motive simple și preferințe.", "في A2 يمكن ذكر أسباب وتفضيلات بسيطة."), quiz_answers: [A("a", "Richtig", true, 1), A("b", "Falsch", false, 2)] },
    { id: "a2-db1", position: 40, kind: "sentence_order", section: "dialog_builder", prompt: "Dialog bauen: Empfehlung → Auswahl → Brot → Grund → Schneiden.", explanation: "Ordne die Gesprächsteile logisch.", data: { words: ["Verkäuferin: Kann ich Ihnen helfen?", "Kundin: Ich suche etwas, das nicht zu süß ist.", "Verkäuferin: Ich empfehle den Apfelkuchen.", "Kundin: Dann nehme ich ein Stück.", "Kundin: Welches Brot ist gut fürs Abendessen?", "Verkäuferin: Das Roggenbrot ist kräftiger.", "Kundin: Ich nehme das kleinere, weil wir zu zweit sind.", "Verkäuferin: Möchten Sie es geschnitten?", "Kundin: Ja, bitte."], ...H("Složi dijalog.", "Diyaloğu sırala.", "Склади діалог.", "Ordonează dialogul.", "رتّب الحوار.") }, quiz_answers: [] },
    { id: "a2-t1", position: 100, kind: "single_choice", section: "test", prompt: "Welche Aussage zeigt A2-Niveau am besten?", explanation: "A2 beschreibt routinemäßige Situationen etwas genauer.", data: H("Koja rečenica najbolje odgovara A2?", "Hangisi A2'ye daha uygun?", "Яке речення найбільше відповідає A2?", "Care propoziție corespunde cel mai bine A2?", "أي جملة تناسب مستوى A2 أكثر؟"), quiz_answers: [A("a", "Ich nehme das kleinere Brot, weil wir heute nur zu zweit sind.", true, 1), A("b", "Brot bitte.", false, 2), A("c", "Die ökonomische Entwicklung der Bäckereibranche ist komplex.", false, 3)] },
    { id: "a2-t2", position: 101, kind: "single_choice", section: "test", prompt: "Was ist eine natürliche Frage nach einer Empfehlung?", explanation: "Was können Sie empfehlen?", data: H("Prirodno pitanje za preporuku?", "Doğal öneri sorusu?", "Природне питання про рекомендацію?", "Întrebare naturală pentru recomandare?", "سؤال طبيعي لطلب توصية؟"), quiz_answers: [A("a", "Was können Sie empfehlen?", true, 1), A("b", "Empfehlung geben!", false, 2), A("c", "Wo ist der Arzt?", false, 3)] },
    { id: "a2-t3", position: 102, kind: "single_choice", section: "test", prompt: "Was bedeutet „weniger süß“?", explanation: "Es enthält bzw. schmeckt nicht so süß wie etwas anderes.", data: H("Šta znači manje slatko?", "Daha az tatlı ne demek?", "Що означає менш солодкий?", "Ce înseamnă mai puțin dulce?", "ماذا يعني أقل حلاوة؟"), quiz_answers: [A("a", "Nicht so süß wie etwas anderes.", true, 1), A("b", "Süßer als alles andere.", false, 2), A("c", "Ganz salzig.", false, 3)] },
    { id: "a2-t4", position: 103, kind: "gap_select", section: "test", prompt: "Wir sind nur zu zweit, ___ nehme ich das kleinere Brot.", explanation: "deshalb = Folge.", data: { options: ["deshalb", "weil", "obwohl", "wenn"], ...H("zato = deshalb", "bu yüzden = deshalb", "тому = deshalb", "de aceea = deshalb", "لذلك = deshalb") }, quiz_answers: [A("a", "deshalb", true, 1)] },
    { id: "a2-t5", position: 104, kind: "single_choice", section: "test", prompt: "Was ist ein Kassenbon?", explanation: "Der Beleg über den Einkauf.", data: H("račun", "fiş", "чек", "bon", "إيصال"), quiz_answers: [A("a", "Ein Beleg über den Einkauf.", true, 1), A("b", "Eine Brotsorte.", false, 2), A("c", "Ein Messer.", false, 3)] },
    { id: "a2-t6", position: 105, kind: "single_choice", section: "test", prompt: "Welche Aussage ist im Perfekt korrekt?", explanation: "haben + Partizip II.", data: H("Koja rečenica u perfektu je tačna?", "Doğru Perfekt cümlesi?", "Правильне речення в Perfekt?", "Propoziție corectă la perfect?", "الجملة الصحيحة في الماضي؟"), quiz_answers: [A("a", "Ich habe den Kuchen schon probiert.", true, 1), A("b", "Ich bin den Kuchen probiert.", false, 2), A("c", "Ich habe probieren den Kuchen.", false, 3)] },
    { id: "a2-t7", position: 106, kind: "single_choice", section: "test", prompt: "Warum zahlt Mara mit Karte?", explanation: "Sie hat nicht genug Bargeld dabei.", data: H("Zašto plaća karticom?", "Neden kartla ödüyor?", "Чому платить карткою?", "De ce plătește cu cardul?", "لماذا تدفع بالبطاقة؟"), quiz_answers: [A("a", "Weil sie nicht genug Bargeld dabeihat.", true, 1), A("b", "Weil das Brot zu süß ist.", false, 2), A("c", "Weil sie den Bus verpasst hat.", false, 3)] },
    { id: "a2-t8", position: 107, kind: "single_choice", section: "test", prompt: "Was ist eine Brotsorte?", explanation: "Eine bestimmte Art von Brot.", data: H("vrsta hljeba", "ekmek çeşidi", "вид хліба", "tip de pâine", "نوع الخبز"), quiz_answers: [A("a", "Eine bestimmte Art von Brot.", true, 1), A("b", "Ein Zahlungsgerät.", false, 2), A("c", "Eine Person.", false, 3)] }
  ]
};