export const bakeryA2VisualPlan = [
  { position: 1, image_key: "baeck-a2-01", german_text: "Mara schaut aus dem Fenster ihrer Wohnung. Die Bäckerei liegt direkt gegenüber auf der anderen Straßenseite." },
  { position: 2, image_key: "baeck-a2-02", german_text: "Mara verlässt ihre Wohnung und geht über die Straße zur Bäckerei." },
  { position: 3, image_key: "baeck-a2-03", german_text: "Sie betritt die Bäckerei und sieht die große Auslage." },
  { position: 4, image_key: "baeck-a2-04", german_text: "Die Verkäuferin begrüßt Mara freundlich und fragt, ob sie helfen kann." },
  { position: 5, image_key: "baeck-a2-05", german_text: "Mara schaut sich mehrere Kuchen an und überlegt, was sie nehmen möchte." },
  { position: 6, image_key: "baeck-a2-06", german_text: "Sie erklärt, dass sie etwas Süßes sucht, das nicht zu schwer und nicht zu süß ist." },
  { position: 7, image_key: "baeck-a2-07", german_text: "Die Verkäuferin zeigt Mara zwei passende Kuchen und erklärt den Unterschied." },
  { position: 8, image_key: "baeck-a2-08", german_text: "Sie empfiehlt den Apfelkuchen, weil er heute frisch gebacken wurde." },
  { position: 9, image_key: "baeck-a2-09", german_text: "Mara fragt, welcher Kuchen weniger süß ist." },
  { position: 10, image_key: "baeck-a2-10", german_text: "Die Verkäuferin erklärt, dass der Apfelkuchen weniger süß als die Torte ist." },
  { position: 11, image_key: "baeck-a2-11", german_text: "Mara entscheidet sich für ein Stück Apfelkuchen." },
  { position: 12, image_key: "baeck-a2-12", german_text: "Sie fragt zusätzlich nach einem Brot für das Abendessen." },
  { position: 13, image_key: "baeck-a2-13", german_text: "Die Verkäuferin zeigt ein Roggenbrot und ein helleres Mischbrot." },
  { position: 14, image_key: "baeck-a2-14", german_text: "Sie erklärt, dass das Roggenbrot kräftiger schmeckt und länger satt macht." },
  { position: 15, image_key: "baeck-a2-15", german_text: "Mara nimmt das kleinere Roggenbrot, weil sie heute nur zu zweit essen." },
  { position: 16, image_key: "baeck-a2-16", german_text: "Die Verkäuferin fragt: Geschnitten oder ganz?" },
  { position: 17, image_key: "baeck-a2-17", german_text: "Mara möchte das Brot geschnitten, damit sie es später leichter einfrieren kann." },
  { position: 18, image_key: "baeck-a2-18", german_text: "Das Brot wird in der Schneidemaschine in gleichmäßige Scheiben geschnitten." },
  { position: 19, image_key: "baeck-a2-19", german_text: "Die Verkäuferin packt Brot und Kuchen getrennt ein." },
  { position: 20, image_key: "baeck-a2-20", german_text: "An der Kasse fragt Mara nach dem Gesamtpreis und nach einer kleinen Tüte." },
  { position: 21, image_key: "baeck-a2-21", german_text: "Die Verkäuferin nennt den Gesamtpreis und zeigt ihn auf der Kasse." },
  { position: 22, image_key: "baeck-a2-22", german_text: "Mara schaut in ihre Geldbörse und merkt, dass sie nicht genug Bargeld dabeihat." },
  { position: 23, image_key: "baeck-a2-23", german_text: "Sie fragt, ob sie mit Karte bezahlen kann." },
  { position: 24, image_key: "baeck-a2-24", german_text: "Mara bezahlt mit Karte und bekommt den Kassenbon." },
  { position: 25, image_key: "baeck-a2-25", german_text: "Mara nimmt die Tüte, bedankt sich und geht zurück zu ihrer Wohnung gegenüber." },
] as const;
