const T = (bks: string, tr: string, uk: string, ro: string, ar: string) => ({ bks, tr, uk, ro, ar });
const A = (id: string, text: string, is_correct: boolean, position: number) => ({ id, text, is_correct, position });

export const bakeryA1Override = {
  lesson: {
    id: "22222222-2222-2222-2222-222222222222",
    slug: "baeckerei-a1",
    title: "In der Bäckerei",
    description:
      "Ein vollständiges A1-Lernmodul: in der Bäckerei einkaufen, Kuchen und Brot kaufen, nach dem Schneiden fragen, bezahlen, Artikel und lokale Präpositionen üben.",
    level: "A1",
    region: "de",
    category_slug: "alltag",
    subcategory_slug: "baeckerei",
    topic_slug: "baeckerei",
    topic_title: "In der Bäckerei",
    duration_seconds: 2700,
    thumbnail_key: "baeckerei",
    video_url: null,
    is_premium: false,
    status: "published",
    popularity: 100,
    grammar_topics: [
      "Höflich bestellen",
      "der / die / das",
      "ein / eine",
      "Akkusativ beim Kaufen",
      "Lokale Präpositionen",
      "mit Karte / bar bezahlen",
    ],
    grammar_notes: [
      {
        title: "Natürlich bestellen",
        explanation:
          "In einer Bäckerei hört man sehr oft: „Ich hätte gern …“, „Ich nehme …“ oder einfach „Zwei Brötchen, bitte.“ Der Satz muss zur Situation passen.",
        examples: [
          "Ich hätte gern ein Stück Apfelkuchen, bitte.",
          "Ich nehme noch ein Mischbrot.",
          "Zwei Brezeln, bitte.",
          "Kann ich mit Karte zahlen?",
        ],
      },
      {
        title: "Artikel: der, die, das",
        explanation:
          "Nomen werden mit ihrem Artikel gelernt: der Kuchen, die Brezel, das Brot. Beim Kaufen braucht man häufig ein/eine oder den/die/das.",
        examples: [
          "der Kuchen → Ich nehme den Kuchen.",
          "die Brezel → Ich nehme eine Brezel.",
          "das Brot → Ich nehme ein Brot.",
          "die Brötchen → Ich nehme vier Brötchen.",
        ],
      },
      {
        title: "Wo ist was?",
        explanation:
          "Mit in, auf, vor, hinter, neben, zwischen, über und unter beschreiben wir Orte. Die Bilder helfen dir: Schau zuerst genau hin und wähle dann die passende Präposition.",
        examples: [
          "Die Kundin steht vor der Theke.",
          "Die Verkäuferin steht hinter der Theke.",
          "Das Brot liegt im Regal.",
          "Die Brezeln liegen neben den Brötchen.",
        ],
      },
    ],
    place_items: [
      { german_text: "Die Kundin steht vor der Theke.", preposition: "vor", image_key: "baeck-bestellen", translations: T("Kupac stoji ispred pulta.", "Müşteri tezgâhın önünde duruyor.", "Покупчиня стоїть перед прилавком.", "Clienta stă în fața tejghelei.", "تقف الزبونة أمام المنضدة.") },
      { german_text: "Die Verkäuferin steht hinter der Theke.", preposition: "hinter", image_key: "baeck-bestellen", translations: T("Prodavačica stoji iza pulta.", "Satıcı tezgâhın arkasında duruyor.", "Продавчиня стоїть за прилавком.", "Vânzătoarea stă în spatele tejghelei.", "تقف البائعة خلف المنضدة.") },
      { german_text: "Das Brot liegt im Regal.", preposition: "in", image_key: "baeck-auslage", translations: T("Hljeb je na polici.", "Ekmek rafta.", "Хліб лежить на полиці.", "Pâinea este pe raft.", "الخبز على الرف.") },
      { german_text: "Die Brezeln liegen neben den Brötchen.", preposition: "neben", image_key: "baeck-gebaeck", translations: T("Perece su pored peciva.", "Pretzeller küçük ekmeklerin yanında.", "Кренделі лежать поруч із булочками.", "Covrigii sunt lângă chifle.", "البريتزل بجانب اللفائف.") },
      { german_text: "Der Kuchen steht zwischen zwei anderen Kuchenstücken.", preposition: "zwischen", image_key: "restaurant", translations: T("Kolač stoji između dva druga komada kolača.", "Kek iki başka kek diliminin arasında.", "Шматок торта стоїть між двома іншими шматками.", "Prăjitura este între alte două felii.", "قطعة الكعك بين قطعتين أخريين.") },
    ],
  },

  scenes: [
    { id: "bak-s1", position: 1, scene_group: "bild-1", image_key: "baeck-eintreten", german_text: "Mara kommt in die Bäckerei.", translations: T("Mara ulazi u pekaru.", "Mara fırına giriyor.", "Мара заходить до пекарні.", "Mara intră în brutărie.", "تدخل مارا إلى المخبز.") },
    { id: "bak-s2", position: 2, scene_group: "bild-2", image_key: "baeck-auslage", german_text: "Sie schaut sich die Auslage an.", translations: T("Gleda izlog i ponudu.", "Vitrine bakıyor.", "Вона дивиться на вітрину.", "Se uită la vitrină.", "تنظر إلى واجهة العرض.") },
    { id: "bak-s3", position: 3, scene_group: "bild-3", image_key: "restaurant", german_text: "Mara sieht Kuchen und Gebäck.", translations: T("Mara vidi kolače i pecivo.", "Mara pasta ve hamur işleri görüyor.", "Мара бачить торт і випічку.", "Mara vede prăjituri și produse de patiserie.", "ترى مارا الكعك والمعجنات.") },
    { id: "bak-s4", position: 4, scene_group: "bild-4", image_key: "baeck-bestellen", german_text: "Die Verkäuferin begrüßt Mara.", translations: T("Prodavačica pozdravlja Maru.", "Satıcı Mara'yı selamlıyor.", "Продавчиня вітає Мару.", "Vânzătoarea o salută pe Mara.", "تحيي البائعة مارا.") },
    { id: "bak-s5", position: 5, scene_group: "bild-5", image_key: "restaurant", german_text: "Mara sagt: „Ich hätte gern ein Stück Apfelkuchen, bitte.“", translations: T("Mara kaže: „Htjela bih komad pite od jabuka, molim.“", "Mara: „Bir dilim elmalı kek istiyorum, lütfen.“ diyor.", "Мара каже: «Я хотіла б шматок яблучного пирога, будь ласка.»", "Mara spune: „Aș dori o felie de prăjitură cu mere, vă rog.“", "تقول مارا: «أود قطعة من كعكة التفاح، من فضلك.»") },
    { id: "bak-s6", position: 6, scene_group: "bild-6", image_key: "baeck-gebaeck", german_text: "Die Verkäuferin legt den Kuchen auf ein Tablett.", translations: T("Prodavačica stavlja kolač na pladanj.", "Satıcı keki tepsiye koyuyor.", "Продавчиня кладе пиріг на тацю.", "Vânzătoarea pune prăjitura pe o tavă.", "تضع البائعة الكعك على صينية.") },
    { id: "bak-s7", position: 7, scene_group: "bild-7", image_key: "baeck-auslage", german_text: "Mara sieht ein Mischbrot im Regal.", translations: T("Mara vidi miješani hljeb na polici.", "Mara rafta karışık ekmek görüyor.", "Мара бачить змішаний хліб на полиці.", "Mara vede o pâine mixtă pe raft.", "ترى مارا خبزًا مشكّلًا على الرف.") },
    { id: "bak-s8", position: 8, scene_group: "bild-8", image_key: "baeck-bestellen", german_text: "Sie sagt: „Ich nehme noch ein Mischbrot, bitte.“", translations: T("Kaže: „Uzet ću još jedan miješani hljeb, molim.“", "„Bir karışık ekmek daha alayım, lütfen.“ diyor.", "Вона каже: «Я візьму ще один змішаний хліб, будь ласка.»", "Spune: „Mai iau și o pâine mixtă, vă rog.“", "تقول: «سآخذ أيضًا خبزًا مشكّلًا، من فضلك.»") },
    { id: "bak-s9", position: 9, scene_group: "bild-9", image_key: "baeck-schneiden", german_text: "Die Verkäuferin fragt: „Möchten Sie das Brot geschnitten oder ganz?“", translations: T("Prodavačica pita: „Želite li hljeb narezan ili cijeli?“", "Satıcı soruyor: „Ekmeği dilimlenmiş mi yoksa bütün mü istersiniz?“", "Продавчиня запитує: «Хліб нарізати чи залишити цілим?»", "Vânzătoarea întreabă: „Doriți pâinea feliată sau întreagă?“", "تسأل البائعة: «هل تريدين الخبز مقطعًا أم كاملًا؟»") },
    { id: "bak-s10", position: 10, scene_group: "bild-10", image_key: "baeck-schneiden", german_text: "Mara antwortet: „Geschnitten, bitte.“", translations: T("Mara odgovara: „Narezano, molim.“", "Mara: „Dilimlenmiş, lütfen.“ diyor.", "Мара відповідає: «Нарізаний, будь ласка.»", "Mara răspunde: „Feliată, vă rog.“", "تجيب مارا: «مقطعًا، من فضلك.»") },
    { id: "bak-s11", position: 11, scene_group: "bild-11", image_key: "kueche", german_text: "Die Verkäuferin schneidet das Brot in Scheiben.", translations: T("Prodavačica reže hljeb na kriške.", "Satıcı ekmeği dilimliyor.", "Продавчиня нарізає хліб скибками.", "Vânzătoarea feliază pâinea.", "تقطع البائعة الخبز إلى شرائح.") },
    { id: "bak-s12", position: 12, scene_group: "bild-12", image_key: "baeck-gebaeck", german_text: "Die Verkäuferin fragt: „Möchten Sie sonst noch etwas?“", translations: T("Prodavačica pita: „Želite li još nešto?“", "Satıcı soruyor: „Başka bir şey ister misiniz?“", "Продавчиня запитує: «Бажаєте ще щось?»", "Vânzătoarea întreabă: „Mai doriți ceva?“", "تسأل البائعة: «هل تريدين شيئًا آخر؟»") },
    { id: "bak-s13", position: 13, scene_group: "bild-13", image_key: "baeck-gebaeck", german_text: "Mara sagt: „Nein, danke. Das ist alles.“", translations: T("Mara kaže: „Ne, hvala. To je sve.“", "Mara: „Hayır, teşekkürler. Hepsi bu.“ diyor.", "Мара каже: «Ні, дякую. Це все.»", "Mara spune: „Nu, mulțumesc. Asta e tot.“", "تقول مارا: «لا، شكرًا. هذا كل شيء.»") },
    { id: "bak-s14", position: 14, scene_group: "bild-14", image_key: "kasse", german_text: "Die Verkäuferin sagt: „Das macht zwölf Euro vierzig.“", translations: T("Prodavačica kaže: „To je dvanaest eura i četrdeset.“", "Satıcı: „On iki euro kırk.“ diyor.", "Продавчиня каже: «З вас дванадцять євро сорок.»", "Vânzătoarea spune: „Doisprezece euro și patruzeci.“", "تقول البائعة: «اثنا عشر يورو وأربعون سنتًا.»") },
    { id: "bak-s15", position: 15, scene_group: "bild-15", image_key: "baeck-bezahlen", german_text: "Mara schaut in ihre Geldbörse. Sie hat nicht genug Kleingeld.", translations: T("Mara gleda u novčanik. Nema dovoljno sitnog novca.", "Mara cüzdanına bakıyor. Yeterince bozuk parası yok.", "Мара дивиться в гаманець. У неї недостатньо дрібних грошей.", "Mara se uită în portofel. Nu are suficienți bani mărunți.", "تنظر مارا في محفظتها. ليس لديها ما يكفي من النقود المعدنية.") },
    { id: "bak-s16", position: 16, scene_group: "bild-16", image_key: "kasse", german_text: "Sie fragt: „Kann ich auch mit Karte zahlen?“", translations: T("Pita: „Mogu li platiti i karticom?“", "„Kartla da ödeyebilir miyim?“ diye soruyor.", "Вона запитує: «Можна також оплатити карткою?»", "Întreabă: „Pot plăti și cu cardul?“", "تسأل: «هل يمكنني الدفع بالبطاقة أيضًا؟»") },
    { id: "bak-s17", position: 17, scene_group: "bild-17", image_key: "baeck-bezahlen", german_text: "Die Verkäuferin antwortet: „Ja, natürlich.“", translations: T("Prodavačica odgovara: „Da, naravno.“", "Satıcı: „Evet, tabii.“ diyor.", "Продавчиня відповідає: «Так, звичайно.»", "Vânzătoarea răspunde: „Da, bineînțeles.“", "تجيب البائعة: «نعم، بالطبع.»") },
    { id: "bak-s18", position: 18, scene_group: "bild-18", image_key: "baeck-erhalten", german_text: "Mara bezahlt, nimmt ihre Tüte und sagt: „Danke. Auf Wiedersehen!“", translations: T("Mara plaća, uzima kesu i kaže: „Hvala. Doviđenja!“", "Mara ödüyor, poşetini alıyor ve „Teşekkürler. Hoşça kalın!“ diyor.", "Мара платить, бере пакет і каже: «Дякую. До побачення!»", "Mara plătește, ia punga și spune: „Mulțumesc. La revedere!“", "تدفع مارا وتأخذ الكيس وتقول: «شكرًا. إلى اللقاء!»") },
  ],

  vocab: [
    ["die Bäckerei", "Nomen", "die", "Bäckereien", "Ich gehe in die Bäckerei.", T("pekara", "fırın", "пекарня", "brutărie", "مخبز"), T("Idem u pekaru.", "Fırına gidiyorum.", "Я йду до пекарні.", "Merg la brutărie.", "أذهب إلى المخبز.")],
    ["die Auslage", "Nomen", "die", "Auslagen", "Ich schaue mir die Auslage an.", T("izlog / vitrina", "vitrin", "вітрина", "vitrină", "واجهة العرض"), T("Gledam izlog.", "Vitrine bakıyorum.", "Я дивлюся на вітрину.", "Mă uit la vitrină.", "أنظر إلى واجهة العرض.")],
    ["der Kuchen", "Nomen", "der", "Kuchen", "Der Kuchen sieht gut aus.", T("kolač", "kek", "торт / пиріг", "prăjitură", "كعك"), T("Kolač izgleda dobro.", "Kek güzel görünüyor.", "Пиріг виглядає добре.", "Prăjitura arată bine.", "تبدو الكعكة جيدة.")],
    ["das Stück", "Nomen", "das", "Stücke", "Ich hätte gern ein Stück Kuchen.", T("komad", "parça / dilim", "шматок", "bucată / felie", "قطعة"), T("Htjela bih komad kolača.", "Bir dilim kek istiyorum.", "Я хотіла б шматок пирога.", "Aș dori o felie de prăjitură.", "أود قطعة من الكعك.")],
    ["das Brot", "Nomen", "das", "Brote", "Ich nehme ein Brot.", T("hljeb / kruh", "ekmek", "хліб", "pâine", "خبز"), T("Uzimam jedan hljeb.", "Bir ekmek alıyorum.", "Я беру один хліб.", "Iau o pâine.", "آخذ خبزًا.")],
    ["das Mischbrot", "Nomen", "das", "Mischbrote", "Ich nehme ein Mischbrot.", T("miješani hljeb", "karışık ekmek", "змішаний хліб", "pâine mixtă", "خبز مشكّل"), T("Uzimam jedan miješani hljeb.", "Bir karışık ekmek alıyorum.", "Я беру змішаний хліб.", "Iau o pâine mixtă.", "آخذ خبزًا مشكّلًا.")],
    ["das Brötchen", "Nomen", "das", "Brötchen", "Ich nehme vier Brötchen.", T("pecivo", "küçük ekmek", "булочка", "chiflă", "لفافة خبز"), T("Uzimam četiri peciva.", "Dört küçük ekmek alıyorum.", "Я беру чотири булочки.", "Iau patru chifle.", "آخذ أربع لفائف خبز.")],
    ["die Brezel", "Nomen", "die", "Brezeln", "Zwei Brezeln, bitte.", T("pereca", "pretzel", "крендель", "covrig", "بريتزل"), T("Dvije perece, molim.", "İki pretzel, lütfen.", "Два кренделі, будь ласка.", "Doi covrigi, vă rog.", "قطعتان بريتزل، من فضلك.")],
    ["die Verkäuferin", "Nomen", "die", "Verkäuferinnen", "Die Verkäuferin steht hinter der Theke.", T("prodavačica", "satıcı", "продавчиня", "vânzătoare", "بائعة"), T("Prodavačica stoji iza pulta.", "Satıcı tezgâhın arkasında duruyor.", "Продавчиня стоїть за прилавком.", "Vânzătoarea stă în spatele tejghelei.", "تقف البائعة خلف المنضدة.")],
    ["die Theke", "Nomen", "die", "Theken", "Die Kundin steht vor der Theke.", T("pult", "tezgâh", "прилавок", "tejghea", "منضدة"), T("Kupac stoji ispred pulta.", "Müşteri tezgâhın önünde duruyor.", "Покупчиня стоїть перед прилавком.", "Clienta stă în fața tejghelei.", "تقف الزبونة أمام المنضدة.")],
    ["geschnitten", "Adjektiv", "", "", "Ich möchte das Brot geschnitten.", T("narezano", "dilimlenmiş", "нарізаний", "feliat", "مقطع"), T("Želim hljeb narezan.", "Ekmeği dilimlenmiş istiyorum.", "Я хочу нарізаний хліб.", "Doresc pâinea feliată.", "أريد الخبز مقطعًا.")],
    ["ganz", "Adjektiv", "", "", "Möchten Sie das Brot geschnitten oder ganz?", T("cijelo", "bütün", "цілий", "întreg", "كامل"), T("Želite li hljeb narezan ili cijeli?", "Ekmeği dilimlenmiş mi bütün mü istersiniz?", "Хліб нарізати чи залишити цілим?", "Doriți pâinea feliată sau întreagă?", "هل تريد الخبز مقطعًا أم كاملًا؟")],
    ["schneiden", "Verb", "", "", "Die Verkäuferin schneidet das Brot.", T("rezati", "kesmek", "різати", "a tăia", "يقطع"), T("Prodavačica reže hljeb.", "Satıcı ekmeği kesiyor.", "Продавчиня ріже хліб.", "Vânzătoarea taie pâinea.", "تقطع البائعة الخبز.")],
    ["die Scheibe", "Nomen", "die", "Scheiben", "Das Brot ist in Scheiben geschnitten.", T("kriška", "dilim", "скибка", "felie", "شريحة"), T("Hljeb je narezan na kriške.", "Ekmek dilimlenmiş.", "Хліб нарізаний скибками.", "Pâinea este feliată.", "الخبز مقطع إلى شرائح.")],
    ["die Geldbörse", "Nomen", "die", "Geldbörsen", "Mara schaut in ihre Geldbörse.", T("novčanik", "cüzdan", "гаманець", "portofel", "محفظة"), T("Mara gleda u novčanik.", "Mara cüzdanına bakıyor.", "Мара дивиться в гаманець.", "Mara se uită în portofel.", "تنظر مارا في محفظتها.")],
    ["das Kleingeld", "Nomen", "das", "", "Ich habe nicht genug Kleingeld.", T("sitni novac", "bozuk para", "дрібні гроші", "bani mărunți", "نقود معدنية"), T("Nemam dovoljno sitnog novca.", "Yeterince bozuk param yok.", "У мене недостатньо дрібних грошей.", "Nu am suficienți bani mărunți.", "ليس لدي ما يكفي من النقود المعدنية.")],
    ["bar", "Adverb", "", "", "Kann ich bar zahlen?", T("gotovinom", "nakit", "готівкою", "numerar", "نقدًا"), T("Mogu li platiti gotovinom?", "Nakit ödeyebilir miyim?", "Можна оплатити готівкою?", "Pot plăti numerar?", "هل يمكنني الدفع نقدًا؟")],
    ["mit Karte", "Wendung", "", "", "Kann ich mit Karte zahlen?", T("karticom", "kartla", "карткою", "cu cardul", "بالبطاقة"), T("Mogu li platiti karticom?", "Kartla ödeyebilir miyim?", "Можна оплатити карткою?", "Pot plăti cu cardul?", "هل يمكنني الدفع بالبطاقة؟")],
    ["Sonst noch etwas?", "Wendung", "", "", "Sonst noch etwas?", T("Još nešto?", "Başka bir şey?", "Ще щось?", "Mai doriți ceva?", "هل تريد شيئًا آخر؟"), T("Još nešto?", "Başka bir şey?", "Ще щось?", "Mai doriți ceva?", "هل تريد شيئًا آخر؟")],
    ["Das ist alles.", "Wendung", "", "", "Nein, danke. Das ist alles.", T("To je sve.", "Hepsi bu.", "Це все.", "Asta e tot.", "هذا كل شيء."), T("Ne, hvala. To je sve.", "Hayır, teşekkürler. Hepsi bu.", "Ні, дякую. Це все.", "Nu, mulțumesc. Asta e tot.", "لا، شكرًا. هذا كل شيء.")],
  ].map((v, i) => ({
    id: `bak-v${i + 1}`,
    position: i + 1,
    term: v[0],
    word_class: v[1],
    article: v[2],
    plural: v[3],
    example: v[4],
    translations: v[5],
    example_translations: v[6],
    collocations: [],
  })),

  dialog: [
    [1, "Ein kompletter Einkauf", "A", "Verkäuferin", "Guten Morgen. Was darf es sein?", T("Dobro jutro. Izvolite?", "Günaydın. Ne alırsınız?", "Доброго ранку. Що бажаєте?", "Bună dimineața. Ce doriți?", "صباح الخير. ماذا تريدين؟")],
    [1, "Ein kompletter Einkauf", "B", "Kundin", "Guten Morgen. Ich hätte gern ein Stück Apfelkuchen, bitte.", T("Dobro jutro. Htjela bih komad pite od jabuka, molim.", "Günaydın. Bir dilim elmalı kek istiyorum, lütfen.", "Доброго ранку. Я хотіла б шматок яблучного пирога, будь ласка.", "Bună dimineața. Aș dori o felie de prăjitură cu mere, vă rog.", "صباح الخير. أود قطعة من كعكة التفاح، من فضلك.")],
    [1, "Ein kompletter Einkauf", "A", "Verkäuferin", "Gerne. Möchten Sie sonst noch etwas?", T("Naravno. Želite li još nešto?", "Tabii. Başka bir şey ister misiniz?", "Звичайно. Бажаєте ще щось?", "Sigur. Mai doriți ceva?", "بالطبع. هل تريدين شيئًا آخر؟")],
    [1, "Ein kompletter Einkauf", "B", "Kundin", "Ja, ich nehme noch ein Mischbrot.", T("Da, uzet ću još jedan miješani hljeb.", "Evet, bir karışık ekmek daha alayım.", "Так, я візьму ще один змішаний хліб.", "Da, mai iau și o pâine mixtă.", "نعم، سآخذ أيضًا خبزًا مشكّلًا.")],
    [1, "Ein kompletter Einkauf", "A", "Verkäuferin", "Möchten Sie das Brot geschnitten oder ganz?", T("Želite li hljeb narezan ili cijeli?", "Ekmeği dilimlenmiş mi yoksa bütün mü istersiniz?", "Хліб нарізати чи залишити цілим?", "Doriți pâinea feliată sau întreagă?", "هل تريدين الخبز مقطعًا أم كاملًا؟")],
    [1, "Ein kompletter Einkauf", "B", "Kundin", "Geschnitten, bitte.", T("Narezano, molim.", "Dilimlenmiş, lütfen.", "Нарізаний, будь ласка.", "Feliată, vă rog.", "مقطعًا، من فضلك.")],
    [1, "Ein kompletter Einkauf", "A", "Verkäuferin", "Sonst noch etwas?", T("Još nešto?", "Başka bir şey?", "Ще щось?", "Mai doriți ceva?", "هل تريدين شيئًا آخر؟")],
    [1, "Ein kompletter Einkauf", "B", "Kundin", "Nein, danke. Das ist alles.", T("Ne, hvala. To je sve.", "Hayır, teşekkürler. Hepsi bu.", "Ні, дякую. Це все.", "Nu, mulțumesc. Asta e tot.", "لا، شكرًا. هذا كل شيء.")],
    [1, "Ein kompletter Einkauf", "A", "Verkäuferin", "Das macht zwölf Euro vierzig.", T("To je dvanaest eura i četrdeset.", "On iki euro kırk.", "З вас дванадцять євро сорок.", "Doisprezece euro și patruzeci.", "اثنا عشر يورو وأربعون سنتًا.")],
    [1, "Ein kompletter Einkauf", "B", "Kundin", "Einen Moment. Ich habe nicht genug Kleingeld. Kann ich auch mit Karte zahlen?", T("Trenutak. Nemam dovoljno sitnog novca. Mogu li platiti i karticom?", "Bir dakika. Yeterince bozuk param yok. Kartla da ödeyebilir miyim?", "Хвилинку. У мене недостатньо дрібних грошей. Можна також оплатити карткою?", "O clipă. Nu am suficienți bani mărunți. Pot plăti și cu cardul?", "لحظة. ليس لدي ما يكفي من النقود المعدنية. هل يمكنني الدفع بالبطاقة أيضًا؟")],
    [1, "Ein kompletter Einkauf", "A", "Verkäuferin", "Ja, natürlich.", T("Da, naravno.", "Evet, tabii.", "Так, звичайно.", "Da, bineînțeles.", "نعم، بالطبع.")],
    [1, "Ein kompletter Einkauf", "B", "Kundin", "Danke. Auf Wiedersehen!", T("Hvala. Doviđenja!", "Teşekkürler. Hoşça kalın!", "Дякую. До побачення!", "Mulțumesc. La revedere!", "شكرًا. إلى اللقاء!")],
    [1, "Ein kompletter Einkauf", "A", "Verkäuferin", "Auf Wiedersehen!", T("Doviđenja!", "Hoşça kalın!", "До побачення!", "La revedere!", "إلى اللقاء!")],

    [2, "Nach Zutaten fragen", "A", "Kundin", "Entschuldigung, sind in diesem Kuchen Nüsse?", T("Izvinite, ima li u ovom kolaču orašastih plodova?", "Affedersiniz, bu kekte fındık var mı?", "Перепрошую, у цьому пирозі є горіхи?", "Scuzați-mă, această prăjitură conține nuci?", "عذرًا، هل توجد مكسرات في هذه الكعكة؟")],
    [2, "Nach Zutaten fragen", "B", "Verkäuferin", "Nein, dieser Kuchen ist ohne Nüsse.", T("Ne, ovaj kolač je bez orašastih plodova.", "Hayır, bu kek fındıksız.", "Ні, цей пиріг без горіхів.", "Nu, această prăjitură este fără nuci.", "لا، هذه الكعكة بدون مكسرات.")],
    [2, "Nach Zutaten fragen", "A", "Kundin", "Gut, dann nehme ich ein Stück, bitte.", T("Dobro, onda ću uzeti jedan komad, molim.", "İyi, o zaman bir dilim alayım, lütfen.", "Добре, тоді я візьму один шматок, будь ласка.", "Bine, atunci iau o felie, vă rog.", "حسنًا، إذن سآخذ قطعة، من فضلك.")],
    [2, "Nach Zutaten fragen", "B", "Verkäuferin", "Gerne.", T("Naravno.", "Tabii.", "Звичайно.", "Sigur.", "بالطبع.")],
  ].map((d, i) => ({ id: `bak-d${i + 1}`, position: i + 1, dialog_index: d[0], dialog_title: d[1], speaker: d[2], speaker_role: d[3], german_text: d[4], translations: d[5] })),

  questions: [
    // SPRACHE & GRAMMATIK — eigene Fragen, nicht im Übungsblock und nicht im Test
    { id: "bak-g1", position: 1, kind: "single_choice", section: "grammar", prompt: "Welcher Artikel ist richtig? ___ Kuchen", explanation: "Kuchen ist maskulin: der Kuchen.", data: {}, quiz_answers: [A("bak-g1a", "der", true, 1), A("bak-g1b", "die", false, 2), A("bak-g1c", "das", false, 3)] },
    { id: "bak-g2", position: 2, kind: "single_choice", section: "grammar", prompt: "Welcher Artikel ist richtig? ___ Brezel", explanation: "Brezel ist feminin: die Brezel.", data: {}, quiz_answers: [A("bak-g2a", "die", true, 1), A("bak-g2b", "der", false, 2), A("bak-g2c", "das", false, 3)] },
    { id: "bak-g3", position: 3, kind: "single_choice", section: "grammar", prompt: "Welcher Artikel ist richtig? ___ Brot", explanation: "Brot ist neutral: das Brot.", data: {}, quiz_answers: [A("bak-g3a", "das", true, 1), A("bak-g3b", "der", false, 2), A("bak-g3c", "die", false, 3)] },
    { id: "bak-g4", position: 4, kind: "gap_select", section: "grammar", prompt: "Ich nehme ___ Kuchen.", explanation: "Bei einem maskulinen Nomen steht im Akkusativ: den Kuchen.", data: { options: ["der", "den", "dem", "die"] }, quiz_answers: [A("bak-g4a", "den", true, 1)] },
    { id: "bak-g5", position: 5, kind: "gap_select", section: "grammar", prompt: "Ich nehme ___ Brezel.", explanation: "Feminin: eine Brezel.", data: { options: ["ein", "eine", "einen", "einem"] }, quiz_answers: [A("bak-g5a", "eine", true, 1)] },
    { id: "bak-g6", position: 6, kind: "gap_select", section: "grammar", prompt: "Ich nehme ___ Brot.", explanation: "Neutral: ein Brot.", data: { options: ["ein", "eine", "einen", "einem"] }, quiz_answers: [A("bak-g6a", "ein", true, 1)] },
    { id: "bak-g7", position: 7, kind: "single_choice", section: "grammar", prompt: "Welche Frage ist höflich und passt in einer Bäckerei?", explanation: "„Kann ich mit Karte zahlen?“ ist eine natürliche höfliche Frage.", data: {}, quiz_answers: [A("bak-g7a", "Kann ich mit Karte zahlen?", true, 1), A("bak-g7b", "Karte geben jetzt?", false, 2), A("bak-g7c", "Ich Karte zahlen.", false, 3)] },
    { id: "bak-g8", position: 8, kind: "gap_select", section: "grammar", prompt: "Die Kundin steht ___ der Theke.", explanation: "Die Kundin steht vor der Theke.", data: { options: ["vor", "hinter", "auf", "unter"], image_key: "baeck-bestellen" }, quiz_answers: [A("bak-g8a", "vor", true, 1)] },
    { id: "bak-g9", position: 9, kind: "gap_select", section: "grammar", prompt: "Die Verkäuferin steht ___ der Theke.", explanation: "Die Verkäuferin steht hinter der Theke.", data: { options: ["vor", "hinter", "über", "neben"], image_key: "baeck-bestellen" }, quiz_answers: [A("bak-g9a", "hinter", true, 1)] },
    { id: "bak-g10", position: 10, kind: "sentence_order", section: "grammar", prompt: "Baue die höfliche Frage richtig auf.", explanation: "Richtig: Kann ich mit Karte zahlen?", data: { words: ["Kann", "ich", "mit", "Karte", "zahlen?"] }, quiz_answers: [] },

    // WO IST WAS? — 10 bildbezogene Präpositionsübungen
    { id: "bak-p1", position: 20, kind: "gap_select", section: "places", prompt: "Schau auf das Bild: Wo steht die Kundin? Die Kundin steht ___ der Theke.", explanation: "Sie steht vor der Theke.", data: { options: ["vor", "hinter", "auf", "unter"], image_key: "baeck-bestellen" }, quiz_answers: [A("bak-p1a", "vor", true, 1)] },
    { id: "bak-p2", position: 21, kind: "gap_select", section: "places", prompt: "Schau auf das Bild: Wo steht die Verkäuferin? Sie steht ___ der Theke.", explanation: "Die Verkäuferin steht hinter der Theke.", data: { options: ["hinter", "vor", "unter", "über"], image_key: "baeck-bestellen" }, quiz_answers: [A("bak-p2a", "hinter", true, 1)] },
    { id: "bak-p3", position: 22, kind: "gap_select", section: "places", prompt: "Schau auf das Bild: Wo liegt das Brot? Das Brot liegt ___ Regal.", explanation: "Man sagt: im Regal.", data: { options: ["im", "auf dem", "vor dem", "unter dem"], image_key: "baeck-auslage" }, quiz_answers: [A("bak-p3a", "im", true, 1)] },
    { id: "bak-p4", position: 23, kind: "gap_select", section: "places", prompt: "Schau auf das Bild: Wo liegen die Brezeln? Sie liegen ___ den Brötchen.", explanation: "Hier liegen die Brezeln neben den Brötchen.", data: { options: ["neben", "unter", "vor", "über"], image_key: "baeck-gebaeck" }, quiz_answers: [A("bak-p4a", "neben", true, 1)] },
    { id: "bak-p5", position: 24, kind: "gap_select", section: "places", prompt: "Schau auf das Bild: Der Kuchen liegt ___ dem Tablett.", explanation: "Der Kuchen liegt auf dem Tablett.", data: { options: ["auf", "unter", "hinter", "zwischen"], image_key: "restaurant" }, quiz_answers: [A("bak-p5a", "auf", true, 1)] },
    { id: "bak-p6", position: 25, kind: "gap_select", section: "places", prompt: "Schau auf das Bild: Die Tüte steht ___ der Kasse.", explanation: "In dieser Szene steht die Tüte neben der Kasse.", data: { options: ["neben", "in", "über", "unter"], image_key: "kasse" }, quiz_answers: [A("bak-p6a", "neben", true, 1)] },
    { id: "bak-p7", position: 26, kind: "gap_select", section: "places", prompt: "Schau auf das Bild: Die Karte ist ___ dem Kartenleser.", explanation: "Beim kontaktlosen Bezahlen hält man die Karte über den Kartenleser.", data: { options: ["über", "unter", "hinter", "zwischen"], image_key: "baeck-bezahlen" }, quiz_answers: [A("bak-p7a", "über", true, 1)] },
    { id: "bak-p8", position: 27, kind: "gap_select", section: "places", prompt: "Schau auf das Bild: Das Brot ist ___ der Schneidemaschine.", explanation: "Beim Schneiden liegt das Brot in der Schneidemaschine.", data: { options: ["in", "vor", "unter", "neben"], image_key: "baeck-schneiden" }, quiz_answers: [A("bak-p8a", "in", true, 1)] },
    { id: "bak-p9", position: 28, kind: "gap_select", section: "places", prompt: "Schau auf das Bild: Die Verkäuferin steht ___ der Kundin.", explanation: "Sie steht der Kundin gegenüber.", data: { options: ["gegenüber", "unter", "auf", "zwischen"], image_key: "baeck-bestellen" }, quiz_answers: [A("bak-p9a", "gegenüber", true, 1)] },
    { id: "bak-p10", position: 29, kind: "gap_select", section: "places", prompt: "Schau auf das Bild: Die Brote stehen ___ in der Auslage.", explanation: "Mehrere Brote stehen nebeneinander.", data: { options: ["nebeneinander", "darunter", "dahinter", "darüber"], image_key: "baeck-auslage" }, quiz_answers: [A("bak-p10a", "nebeneinander", true, 1)] },

    // INTERAKTIVER DIALOG — genau ein kompletter Dialog zum selbst Zusammensetzen
    { id: "bak-dialog-builder", position: 40, kind: "dialog_order", section: "dialog_builder", prompt: "Baue den kompletten Einkauf logisch zusammen: Begrüßung → Kuchen → Brot → geschnitten oder ganz → Preis → Karte → Abschied.", explanation: "Achte auf den roten Faden. Eine Antwort muss logisch auf die vorherige Frage folgen.", data: { items: [
      "Verkäuferin: Guten Morgen. Was darf es sein?",
      "Kundin: Guten Morgen. Ich hätte gern ein Stück Apfelkuchen, bitte.",
      "Verkäuferin: Gerne. Möchten Sie sonst noch etwas?",
      "Kundin: Ja, ich nehme noch ein Mischbrot.",
      "Verkäuferin: Möchten Sie das Brot geschnitten oder ganz?",
      "Kundin: Geschnitten, bitte.",
      "Verkäuferin: Sonst noch etwas?",
      "Kundin: Nein, danke. Das ist alles.",
      "Verkäuferin: Das macht zwölf Euro vierzig.",
      "Kundin: Einen Moment. Ich habe nicht genug Kleingeld. Kann ich auch mit Karte zahlen?",
      "Verkäuferin: Ja, natürlich.",
      "Kundin: Danke. Auf Wiedersehen!",
      "Verkäuferin: Auf Wiedersehen!",
    ] }, quiz_answers: [] },

    // ÜBUNGEN — andere Fragen als Grammatik und Test
    { id: "bak-u1", position: 50, kind: "single_choice", section: "uebungen", prompt: "Mara möchte ein Stück Apfelkuchen kaufen. Welcher Satz passt am besten?", explanation: "Die passende Bestellung ist höflich und nennt genau das gewünschte Produkt.", data: {}, quiz_answers: [A("bak-u1a", "Ich hätte gern ein Stück Apfelkuchen, bitte.", true, 1), A("bak-u1b", "Geben Sie mir bitte ein warmes Brot.", false, 2), A("bak-u1c", "Haben Sie heute noch Vollkornbrot?", false, 3), A("bak-u1d", "Kann ich mit Karte zahlen?", false, 4)] },
    { id: "bak-u2", position: 51, kind: "single_choice", section: "uebungen", prompt: "Die Verkäuferin fragt: „Möchten Sie das Brot geschnitten oder ganz?“ Was antwortet Mara?", explanation: "Mara möchte das Brot geschnitten.", data: {}, quiz_answers: [A("bak-u2a", "Geschnitten, bitte.", true, 1), A("bak-u2b", "Nein, ich möchte Kuchen.", false, 2), A("bak-u2c", "Zwölf Euro vierzig.", false, 3)] },
    { id: "bak-u3", position: 52, kind: "multi_choice", section: "uebungen", prompt: "Welche Sätze kann eine Kundin in einer Bäckerei wirklich sagen? Mehrere Antworten sind richtig.", explanation: "Alle richtigen Antworten passen natürlich in einen Einkauf.", data: {}, quiz_answers: [A("bak-u3a", "Ich hätte gern zwei Brötchen, bitte.", true, 1), A("bak-u3b", "Kann ich mit Karte zahlen?", true, 2), A("bak-u3c", "Möchten Sie das Brot geschnitten?", false, 3), A("bak-u3d", "Das ist alles, danke.", true, 4)] },
    { id: "bak-u4", position: 53, kind: "sentence_order", section: "uebungen", prompt: "Baue die Bestellung richtig auf.", explanation: "Richtig: Ich hätte gern ein Stück Apfelkuchen, bitte.", data: { words: ["Ich", "hätte", "gern", "ein", "Stück", "Apfelkuchen,", "bitte."] }, quiz_answers: [] },
    { id: "bak-u5", position: 54, kind: "sentence_order", section: "uebungen", prompt: "Baue die Frage richtig auf.", explanation: "Richtig: Kann ich auch mit Karte zahlen?", data: { words: ["Kann", "ich", "auch", "mit", "Karte", "zahlen?"] }, quiz_answers: [] },
    { id: "bak-u6", position: 55, kind: "single_choice", section: "uebungen", prompt: "Was bedeutet „Das ist alles“ beim Einkaufen?", explanation: "Die Kundin möchte nichts mehr kaufen.", data: {}, quiz_answers: [A("bak-u6a", "Ich möchte nichts mehr.", true, 1), A("bak-u6b", "Alles ist ausverkauft.", false, 2), A("bak-u6c", "Ich möchte alles kaufen.", false, 3)] },
    { id: "bak-u7", position: 56, kind: "true_false", section: "uebungen", prompt: "Mara kauft zuerst Kuchen und danach Brot.", explanation: "Genau so läuft die Fotostory ab.", data: {}, quiz_answers: [A("bak-u7a", "Richtig", true, 1), A("bak-u7b", "Falsch", false, 2)] },
    { id: "bak-u8", position: 57, kind: "single_choice", section: "uebungen", prompt: "Warum fragt Mara nach Kartenzahlung?", explanation: "Sie hat nicht genug Kleingeld.", data: {}, quiz_answers: [A("bak-u8a", "Sie hat nicht genug Kleingeld.", true, 1), A("bak-u8b", "Sie hat ihre Geldbörse vergessen.", false, 2), A("bak-u8c", "Die Verkäuferin hat kein Brot.", false, 3)] },
    { id: "bak-u9", position: 58, kind: "gap_select", section: "uebungen", prompt: "Möchten Sie das Brot geschnitten ___ ganz?", explanation: "Die feste Alternative lautet: geschnitten oder ganz.", data: { options: ["oder", "und", "aber", "weil"] }, quiz_answers: [A("bak-u9a", "oder", true, 1)] },
    { id: "bak-u10", position: 59, kind: "gap_select", section: "uebungen", prompt: "Ich habe nicht genug ___.", explanation: "Kleingeld sind Münzen und kleine Geldbeträge.", data: { options: ["Kleingeld", "Kuchen", "Brot", "Theke"] }, quiz_answers: [A("bak-u10a", "Kleingeld", true, 1)] },
    { id: "bak-u11", position: 60, kind: "match", section: "uebungen", prompt: "Ordne die Wörter ihrer Bedeutung in deiner Hilfssprache zu.", explanation: "Wortschatz aus der Bäckerei.", data: { pairs: [
      { left: "das Brot", right: "bread", translations: T("hljeb / kruh", "ekmek", "хліб", "pâine", "خبز") },
      { left: "die Brezel", right: "pretzel", translations: T("pereca", "pretzel", "крендель", "covrig", "بريتزل") },
      { left: "die Geldbörse", right: "wallet", translations: T("novčanik", "cüzdan", "гаманець", "portofel", "محفظة") },
      { left: "geschnitten", right: "sliced", translations: T("narezano", "dilimlenmiş", "нарізаний", "feliat", "مقطع") },
    ] }, quiz_answers: [] },
    { id: "bak-u12", position: 61, kind: "order", section: "uebungen", prompt: "Bringe die Stationen des Einkaufs in die richtige Reihenfolge.", explanation: "Erst auswählen und bestellen, dann bezahlen, dann verabschieden.", data: { items: ["Kuchen bestellen", "Brot dazunehmen", "Brot schneiden lassen", "Preis hören", "mit Karte bezahlen", "sich verabschieden"] }, quiz_answers: [] },
    { id: "bak-u13", position: 62, kind: "single_choice", section: "uebungen", prompt: "Welche Frage stellt normalerweise die Verkäuferin?", explanation: "„Sonst noch etwas?“ kommt sehr häufig im Verkauf vor.", data: {}, quiz_answers: [A("bak-u13a", "Sonst noch etwas?", true, 1), A("bak-u13b", "Kann ich mit Karte zahlen?", false, 2), A("bak-u13c", "Ich hätte gern ein Brot.", false, 3)] },
    { id: "bak-u14", position: 63, kind: "gap_select", section: "uebungen", prompt: "Nein, danke. Das ___ alles.", explanation: "Die feste Formulierung lautet: Das ist alles.", data: { options: ["ist", "sind", "hat", "macht"] }, quiz_answers: [A("bak-u14a", "ist", true, 1)] },
    { id: "bak-u15", position: 64, kind: "single_choice", section: "uebungen", prompt: "Was bedeutet „Das macht zwölf Euro vierzig“?", explanation: "Die Verkäuferin nennt den Gesamtpreis.", data: {}, quiz_answers: [A("bak-u15a", "Der Einkauf kostet 12,40 Euro.", true, 1), A("bak-u15b", "Die Bäckerei öffnet um 12:40 Uhr.", false, 2), A("bak-u15c", "Mara kauft zwölf Brote.", false, 3)] },

    // ABSCHLUSSTEST — bewusst andere Aufgaben als Übungen
    { id: "bak-t1", position: 100, kind: "single_choice", section: "test", prompt: "Du möchtest zwei Brötchen. Was sagst du?", explanation: "Eine kurze höfliche Bestellung reicht völlig.", data: {}, quiz_answers: [A("bak-t1a", "Zwei Brötchen, bitte.", true, 1), A("bak-t1b", "Zwei Brötchen sind da.", false, 2), A("bak-t1c", "Möchten Sie zwei Brötchen?", false, 3)] },
    { id: "bak-t2", position: 101, kind: "single_choice", section: "test", prompt: "Die Verkäuferin fragt: „Sonst noch etwas?“ Du möchtest nichts mehr. Was sagst du?", explanation: "„Nein, danke. Das ist alles.“ passt perfekt.", data: {}, quiz_answers: [A("bak-t2a", "Nein, danke. Das ist alles.", true, 1), A("bak-t2b", "Ja, mit Karte.", false, 2), A("bak-t2c", "Geschnitten, bitte.", false, 3)] },
    { id: "bak-t3", position: 102, kind: "gap_select", section: "test", prompt: "Ich hätte gern ___ Brezel.", explanation: "die Brezel → eine Brezel.", data: { options: ["eine", "einen", "ein", "einem"] }, quiz_answers: [A("bak-t3a", "eine", true, 1)] },
    { id: "bak-t4", position: 103, kind: "gap_select", section: "test", prompt: "Ich nehme ___ Kuchen.", explanation: "der Kuchen → im Akkusativ: den Kuchen.", data: { options: ["den", "der", "dem", "die"] }, quiz_answers: [A("bak-t4a", "den", true, 1)] },
    { id: "bak-t5", position: 104, kind: "sentence_order", section: "test", prompt: "Baue den Satz richtig auf.", explanation: "Richtig: Ich nehme noch ein Mischbrot.", data: { words: ["Ich", "nehme", "noch", "ein", "Mischbrot."] }, quiz_answers: [] },
    { id: "bak-t6", position: 105, kind: "single_choice", section: "test", prompt: "Was heißt „geschnitten“ bei Brot?", explanation: "Das Brot ist in Scheiben geschnitten.", data: {}, quiz_answers: [A("bak-t6a", "Das Brot ist in Scheiben.", true, 1), A("bak-t6b", "Das Brot ist warm.", false, 2), A("bak-t6c", "Das Brot ist kostenlos.", false, 3)] },
    { id: "bak-t7", position: 106, kind: "gap_select", section: "test", prompt: "Die Kundin steht ___ der Theke.", explanation: "Die Kundin steht vor der Theke.", data: { options: ["vor", "hinter", "unter", "über"], image_key: "baeck-bestellen" }, quiz_answers: [A("bak-t7a", "vor", true, 1)] },
    { id: "bak-t8", position: 107, kind: "single_choice", section: "test", prompt: "Welche Frage passt, wenn du kein passendes Bargeld hast?", explanation: "Dann kann man nach Kartenzahlung fragen.", data: {}, quiz_answers: [A("bak-t8a", "Kann ich auch mit Karte zahlen?", true, 1), A("bak-t8b", "Wo ist die Bäckerei?", false, 2), A("bak-t8c", "Ist das Brot geschnitten?", false, 3)] },
    { id: "bak-t9", position: 108, kind: "order", section: "test", prompt: "Ordne den Schluss des Einkaufs.", explanation: "Preis → bezahlen → Ware nehmen → verabschieden.", data: { items: ["Die Verkäuferin nennt den Preis.", "Mara bezahlt.", "Mara nimmt die Tüte.", "Mara verabschiedet sich."] }, quiz_answers: [] },
    { id: "bak-t10", position: 109, kind: "multi_choice", section: "test", prompt: "Welche Wörter gehören zur Bäckerei? Mehrere Antworten sind richtig.", explanation: "Brot, Brezel und Theke gehören direkt zu dieser Situation.", data: {}, quiz_answers: [A("bak-t10a", "das Brot", true, 1), A("bak-t10b", "die Brezel", true, 2), A("bak-t10c", "die Theke", true, 3), A("bak-t10d", "der Bahnsteig", false, 4)] },
  ],
};
