const t = (bks: string, tr: string, uk: string, ro: string, ar: string) => ({ bks, tr, uk, ro, ar });

const vocab = (
  term: string,
  wordClass: string,
  article: string,
  plural: string,
  example: string,
  translations: Record<string, string>,
  exampleTranslations: Record<string, string>,
  collocations: string[] = [],
) => ({ term, wordClass, article, plural, example, translations, exampleTranslations, collocations });

const vocabRows = [
  vocab("das Brot", "Nomen", "das", "Brote", "Ich hätte gern ein Brot, bitte.", t("hljeb", "ekmek", "хліб", "pâine", "خبز"), t("Htio/Htjela bih jedan hljeb, molim.", "Bir ekmek alabilir miyim, lütfen?", "Я хотів/хотіла б один хліб, будь ласка.", "Aș dori o pâine, vă rog.", "أود خبزًا، من فضلك."), ["ein Brot kaufen", "Brot schneiden"]),
  vocab("das Mischbrot", "Nomen", "das", "Mischbrote", "Ich hätte gern ein Mischbrot, bitte.", t("miješani hljeb", "karışık ekmek", "змішаний хліб", "pâine mixtă", "خبز مخلوط"), t("Htio/Htjela bih jedan miješani hljeb, molim.", "Bir karışık ekmek alabilir miyim, lütfen?", "Я хотів/хотіла б змішаний хліб, будь ласка.", "Aș dori o pâine mixtă, vă rog.", "أود خبزًا مخلوطًا، من فضلك.")),
  vocab("das Brötchen", "Nomen", "das", "Brötchen", "Ich nehme vier Brötchen, bitte.", t("pecivo", "küçük ekmek", "булочка", "chiflă", "لفافة خبز"), t("Uzet ću četiri peciva, molim.", "Dört küçük ekmek alayım, lütfen.", "Я візьму чотири булочки, будь ласка.", "Iau patru chifle, vă rog.", "سآخذ أربع لفائف خبز، من فضلك.")),
  vocab("die Brezel", "Nomen", "die", "Brezeln", "Zwei Brezeln, bitte.", t("pereca", "pretzel", "крендель", "covrig", "بريتزل"), t("Dvije perece, molim.", "İki pretzel, lütfen.", "Два кренделі, будь ласка.", "Doi covrigi, vă rog.", "قطعتان من البريتزل، من فضلك.")),
  vocab("die Bäckerei", "Nomen", "die", "Bäckereien", "Mara geht in die Bäckerei.", t("pekara", "fırın", "пекарня", "brutărie", "مخبز"), t("Mara ide u pekaru.", "Mara fırına gidiyor.", "Мара йде до пекарні.", "Mara merge la brutărie.", "تذهب مارا إلى المخبز.")),
  vocab("die Verkäuferin", "Nomen", "die", "Verkäuferinnen", "Die Verkäuferin steht hinter der Theke.", t("prodavačica", "satıcı", "продавчиня", "vânzătoare", "بائعة"), t("Prodavačica stoji iza pulta.", "Satıcı tezgâhın arkasında duruyor.", "Продавчиня стоїть за прилавком.", "Vânzătoarea stă în spatele tejghelei.", "تقف البائعة خلف المنضدة.")),
  vocab("die Kundin", "Nomen", "die", "Kundinnen", "Die Kundin steht vor der Theke.", t("kupac / mušterija", "müşteri", "покупчиня", "clientă", "زبونة"), t("Kupac stoji ispred pulta.", "Müşteri tezgâhın önünde duruyor.", "Покупчиня стоїть перед прилавком.", "Clienta stă în fața tejghelei.", "تقف الزبونة أمام المنضدة.")),
  vocab("die Theke", "Nomen", "die", "Theken", "Die Tüte liegt auf der Theke.", t("pult", "tezgâh", "прилавок", "tejghea", "منضدة"), t("Kesa je na pultu.", "Poşet tezgâhın üzerinde.", "Пакет лежить на прилавку.", "Punga este pe tejghea.", "الكيس على المنضدة.")),
  vocab("die Tüte", "Nomen", "die", "Tüten", "Mara nimmt die Tüte.", t("kesa", "poşet", "пакет", "pungă", "كيس"), t("Mara uzima kesu.", "Mara poşeti alıyor.", "Мара бере пакет.", "Mara ia punga.", "تأخذ مارا الكيس.")),
  vocab("schneiden", "Verb", "", "", "Die Verkäuferin schneidet das Brot.", t("rezati", "kesmek", "різати", "a tăia", "يقطع"), t("Prodavačica reže hljeb.", "Satıcı ekmeği kesiyor.", "Продавчиня нарізає хліб.", "Vânzătoarea taie pâinea.", "تقطع البائعة الخبز."), ["Brot schneiden", "in Scheiben schneiden"]),
  vocab("geschnitten", "Adjektiv", "", "", "Möchten Sie das Brot geschnitten?", t("narezan", "dilimlenmiş", "нарізаний", "feliat", "مقطّع"), t("Želite li da hljeb bude narezan?", "Ekmeği dilimlenmiş ister misiniz?", "Бажаєте нарізаний хліб?", "Doriți pâinea feliată?", "هل تريدين الخبز مقطعًا؟")),
  vocab("nehmen", "Verb", "", "", "Ich nehme vier Brötchen.", t("uzeti", "almak", "брати", "a lua", "يأخذ"), t("Uzet ću četiri peciva.", "Dört küçük ekmek alıyorum.", "Я візьму чотири булочки.", "Iau patru chifle.", "سآخذ أربع لفائف خبز.")),
  vocab("zahlen", "Verb", "", "", "Kann ich mit Karte zahlen?", t("platiti", "ödemek", "платити", "a plăti", "يدفع"), t("Mogu li platiti karticom?", "Kartla ödeyebilir miyim?", "Можна оплатити карткою?", "Pot plăti cu cardul?", "هل يمكنني الدفع بالبطاقة؟"), ["bar zahlen", "mit Karte zahlen"]),
  vocab("kosten", "Verb", "", "", "Das kostet acht Euro zwanzig.", t("koštati", "tutmak / fiyatı olmak", "коштувати", "a costa", "يكلّف"), t("To košta osam eura i dvadeset.", "Bu sekiz euro yirmi tutuyor.", "Це коштує вісім євро двадцять.", "Costă opt euro și douăzeci.", "هذا يكلف ثمانية يورو وعشرين سنتًا.")),
  vocab("noch", "Adverb", "", "", "Sonst noch etwas?", t("još", "daha", "ще", "încă", "أيضًا / المزيد"), t("Još nešto?", "Başka bir şey?", "Ще щось?", "Mai doriți ceva?", "شيء آخر؟")),
  vocab("bitte", "Partikel", "", "", "Ein Mischbrot, bitte.", t("molim", "lütfen", "будь ласка", "vă rog", "من فضلك"), t("Jedan miješani hljeb, molim.", "Bir karışık ekmek, lütfen.", "Один змішаний хліб, будь ласка.", "O pâine mixtă, vă rog.", "خبز مخلوط، من فضلك.")),
  vocab("danke", "Partikel", "", "", "Danke. Auf Wiedersehen!", t("hvala", "teşekkürler", "дякую", "mulțumesc", "شكرًا"), t("Hvala. Doviđenja!", "Teşekkürler. Hoşça kalın!", "Дякую. До побачення!", "Mulțumesc. La revedere!", "شكرًا. إلى اللقاء!")),
  vocab("mit Karte", "Wendung", "", "", "Ich zahle mit Karte.", t("karticom", "kartla", "карткою", "cu cardul", "بالبطاقة"), t("Plaćam karticom.", "Kartla ödüyorum.", "Я плачу карткою.", "Plătesc cu cardul.", "أدفع بالبطاقة.")),
  vocab("im Regal", "Wendung", "", "", "Das Brot liegt im Regal.", t("na polici", "raftta", "на полиці", "pe raft", "على الرف"), t("Hljeb je na polici.", "Ekmek rafta.", "Хліб лежить на полиці.", "Pâinea este pe raft.", "الخبز على الرف.")),
  vocab("hinter der Theke", "Wendung", "", "", "Die Verkäuferin steht hinter der Theke.", t("iza pulta", "tezgâhın arkasında", "за прилавком", "în spatele tejghelei", "خلف المنضدة"), t("Prodavačica stoji iza pulta.", "Satıcı tezgâhın arkasında duruyor.", "Продавчиня стоїть за прилавком.", "Vânzătoarea stă în spatele tejghelei.", "تقف البائعة خلف المنضدة.")),
];

export const bakeryA1Override = {
  lesson: {
    id: "22222222-2222-2222-2222-222222222222",
    slug: "baeckerei-a1",
    title: "In der Bäckerei",
    description: "Eine echte A1-Alltagssituation: begrüßen, Brot und Gebäck kaufen, nachfragen, bezahlen und sich verabschieden.",
    level: "A1",
    region: "de",
    category_slug: "alltag",
    subcategory_slug: "baeckerei",
    topic_slug: "baeckerei",
    topic_title: "In der Bäckerei",
    duration_seconds: 2700,
    thumbnail_key: "baeckerei",
    video_url: null,
    is_premium: false,
    status: "published",
    popularity: 80,
    grammar_topics: ["Höflich kaufen", "der / die / das", "Akkusativ im Alltag", "Lokale Präpositionen"],
    grammar_notes: [
      {
        title: "So klingt eine Bestellung natürlich",
        explanation: "In einer Bäckerei sagt man sehr oft „Ich hätte gern …“, „Ich nehme …“ oder einfach „Zwei Brötchen, bitte.“. „Ich bestelle ein Brot“ ist grammatisch möglich, klingt an der Theke aber unnötig förmlich.",
        examples: ["Ich hätte gern ein Mischbrot, bitte.", "Ich nehme vier Brötchen, bitte.", "Zwei Brezeln, bitte."],
      },
      {
        title: "der · die · das",
        explanation: "Lerne Nomen immer mit Artikel. Das hilft später bei Fällen und Präpositionen.",
        examples: ["das Brot", "das Brötchen", "die Brezel", "die Bäckerei", "die Theke"],
      },
      {
        title: "Akkusativ beim Kaufen",
        explanation: "Nach „ich hätte gern“ oder „ich nehme“ steht das, was man kauft. Bei neutralen Wörtern bleibt „ein“: ein Brot. Bei femininen Wörtern heißt es „eine“: eine Brezel.",
        examples: ["Ich hätte gern ein Brot.", "Ich nehme eine Brezel.", "Ich nehme zwei Brötchen."],
      },
      {
        title: "Wo ist was?",
        explanation: "Für einen Ort verwenden wir zum Beispiel in, auf, neben, vor, hinter, zwischen, unter, über und an. Bei einem festen Ort folgt oft der Dativ: hinter der Theke, auf dem Regal, neben den Brötchen.",
        examples: ["Die Verkäuferin steht hinter der Theke.", "Die Kundin steht vor der Theke.", "Die Tüte liegt auf der Theke.", "Das Brot liegt im Regal."],
      },
    ],
    place_items: [
      { german_text: "Die Verkäuferin steht hinter der Theke.", preposition: "hinter", image_key: "baeck-bestellen", translations: t("Prodavačica stoji iza pulta.", "Satıcı tezgâhın arkasında duruyor.", "Продавчиня стоїть за прилавком.", "Vânzătoarea stă în spatele tejghelei.", "تقف البائعة خلف المنضدة.") },
      { german_text: "Mara steht vor der Theke.", preposition: "vor", image_key: "baeck-bestellen", translations: t("Mara stoji ispred pulta.", "Mara tezgâhın önünde duruyor.", "Мара стоїть перед прилавком.", "Mara stă în fața tejghelei.", "تقف مارا أمام المنضدة.") },
      { german_text: "Das Brot liegt im Regal.", preposition: "in", image_key: "baeck-auslage", translations: t("Hljeb je na polici.", "Ekmek rafta.", "Хліб лежить на полиці.", "Pâinea este pe raft.", "الخبز على الرف.") },
      { german_text: "Die Brezeln liegen neben den Brötchen.", preposition: "neben", image_key: "baeck-gebaeck", translations: t("Perece su pored peciva.", "Pretzeller küçük ekmeklerin yanında.", "Кренделі лежать поруч із булочками.", "Covrigii sunt lângă chifle.", "البريتزل بجانب لفائف الخبز.") },
      { german_text: "Die Tüte liegt auf der Theke.", preposition: "auf", image_key: "baeck-erhalten", translations: t("Kesa je na pultu.", "Poşet tezgâhın üzerinde.", "Пакет лежить на прилавку.", "Punga este pe tejghea.", "الكيس على المنضدة.") },
    ],
  },
  scenes: [
    { id: "bak-s1", position: 1, scene_group: "eingang", image_key: "baeck-eintreten", german_text: "Mara geht in die Bäckerei.", translations: t("Mara ide u pekaru.", "Mara fırına gidiyor.", "Мара йде до пекарні.", "Mara merge la brutărie.", "تذهب مارا إلى المخبز.") },
    { id: "bak-s2", position: 2, scene_group: "auslage", image_key: "baeck-auslage", german_text: "Sie schaut sich die Brote, Brötchen und Brezeln an.", translations: t("Gleda hljeb, peciva i perece.", "Ekmeklere, küçük ekmeklere ve pretzellere bakıyor.", "Вона дивиться на хліб, булочки та кренделі.", "Se uită la pâini, chifle și covrigi.", "تنظر إلى الخبز واللفائف والبريتزل.") },
    { id: "bak-s3", position: 3, scene_group: "bestellen", image_key: "baeck-bestellen", german_text: "Die Verkäuferin sagt: „Guten Morgen. Was darf es sein?“", translations: t("Prodavačica kaže: „Dobro jutro. Izvolite?“", "Satıcı: „Günaydın. Ne alırsınız?“ diyor.", "Продавчиня каже: «Доброго ранку. Що бажаєте?»", "Vânzătoarea spune: „Bună dimineața. Ce doriți?“", "تقول البائعة: «صباح الخير. ماذا تريدين؟»") },
    { id: "bak-s4", position: 4, scene_group: "bestellen", image_key: "baeck-bestellen", german_text: "Mara sagt: „Guten Morgen. Ich hätte gern ein Mischbrot, bitte.“", translations: t("Mara kaže: „Dobro jutro. Htjela bih jedan miješani hljeb, molim.“", "Mara: „Günaydın. Bir karışık ekmek alabilir miyim, lütfen?“ diyor.", "Мара каже: «Доброго ранку. Я хотіла б змішаний хліб, будь ласка.»", "Mara spune: „Bună dimineața. Aș dori o pâine mixtă, vă rog.“", "تقول مارا: «صباح الخير. أود خبزًا مخلوطًا، من فضلك.»") },
    { id: "bak-s5", position: 5, scene_group: "schneiden", image_key: "baeck-schneiden", german_text: "Die Verkäuferin fragt: „Möchten Sie das Brot geschnitten?“", translations: t("Prodavačica pita: „Želite li da hljeb bude narezan?“", "Satıcı soruyor: „Ekmeği dilimlenmiş ister misiniz?“", "Продавчиня запитує: «Бажаєте нарізаний хліб?»", "Vânzătoarea întreabă: „Doriți pâinea feliată?“", "تسأل البائعة: «هل تريدين الخبز مقطعًا؟»") },
    { id: "bak-s6", position: 6, scene_group: "schneiden", image_key: "baeck-schneiden", german_text: "Mara antwortet: „Ja, bitte.“", translations: t("Mara odgovara: „Da, molim.“", "Mara cevap veriyor: „Evet, lütfen.“", "Мара відповідає: «Так, будь ласка.»", "Mara răspunde: „Da, vă rog.“", "تجيب مارا: «نعم، من فضلك.»") },
    { id: "bak-s7", position: 7, scene_group: "gebaeck", image_key: "baeck-gebaeck", german_text: "Mara sagt: „Ich nehme noch vier Brötchen und zwei Brezeln, bitte.“", translations: t("Mara kaže: „Uzet ću još četiri peciva i dvije perece, molim.“", "Mara: „Dört küçük ekmek ve iki pretzel daha alayım, lütfen.“ diyor.", "Мара каже: «Я візьму ще чотири булочки та два кренделі, будь ласка.»", "Mara spune: „Mai iau patru chifle și doi covrigi, vă rog.“", "تقول مارا: «سآخذ أيضًا أربع لفائف وقطعتين من البريتزل، من فضلك.»") },
    { id: "bak-s8", position: 8, scene_group: "bezahlen", image_key: "baeck-bezahlen", german_text: "Die Verkäuferin sagt: „Das macht acht Euro zwanzig.“", translations: t("Prodavačica kaže: „To je osam eura i dvadeset.“", "Satıcı: „Sekiz euro yirmi.“ diyor.", "Продавчиня каже: «З вас вісім євро двадцять.»", "Vânzătoarea spune: „Opt euro și douăzeci.“", "تقول البائعة: «ثمانية يورو وعشرون سنتًا.»") },
    { id: "bak-s9", position: 9, scene_group: "bezahlen", image_key: "baeck-bezahlen", german_text: "Mara fragt: „Kann ich mit Karte zahlen?“", translations: t("Mara pita: „Mogu li platiti karticom?“", "Mara soruyor: „Kartla ödeyebilir miyim?“", "Мара запитує: «Можна оплатити карткою?»", "Mara întreabă: „Pot plăti cu cardul?“", "تسأل مارا: «هل يمكنني الدفع بالبطاقة؟»") },
    { id: "bak-s10", position: 10, scene_group: "erhalten", image_key: "baeck-erhalten", german_text: "Mara bezahlt, nimmt die Tüte und sagt: „Danke. Auf Wiedersehen!“", translations: t("Mara plaća, uzima kesu i kaže: „Hvala. Doviđenja!“", "Mara ödüyor, poşeti alıyor ve „Teşekkürler. Hoşça kalın!“ diyor.", "Мара платить, бере пакет і каже: «Дякую. До побачення!»", "Mara plătește, ia punga și spune: „Mulțumesc. La revedere!“", "تدفع مارا وتأخذ الكيس وتقول: «شكرًا. إلى اللقاء!»") },
  ],
  vocab: vocabRows.map((v, i) => ({ id: `bak-v${i + 1}`, position: i + 1, term: v.term, word_class: v.wordClass, article: v.article, plural: v.plural, example: v.example, example_translations: v.exampleTranslations, collocations: v.collocations, translations: v.translations })),
  dialog: [
    ["A", "Verkäuferin", "Guten Morgen. Was darf es sein?", t("Dobro jutro. Izvolite?", "Günaydın. Ne alırsınız?", "Доброго ранку. Що бажаєте?", "Bună dimineața. Ce doriți?", "صباح الخير. ماذا تريدين؟")],
    ["B", "Kundin", "Guten Morgen. Ich hätte gern ein Mischbrot, bitte.", t("Dobro jutro. Htjela bih jedan miješani hljeb, molim.", "Günaydın. Bir karışık ekmek alabilir miyim, lütfen?", "Доброго ранку. Я хотіла б змішаний хліб, будь ласка.", "Bună dimineața. Aș dori o pâine mixtă, vă rog.", "صباح الخير. أود خبزًا مخلوطًا، من فضلك.")],
    ["A", "Verkäuferin", "Gern. Möchten Sie das Brot geschnitten?", t("Naravno. Želite li da hljeb bude narezan?", "Tabii. Ekmeği dilimlenmiş ister misiniz?", "Звичайно. Бажаєте нарізаний хліб?", "Sigur. Doriți pâinea feliată?", "بالتأكيد. هل تريدين الخبز مقطعًا؟")],
    ["B", "Kundin", "Ja, bitte.", t("Da, molim.", "Evet, lütfen.", "Так, будь ласка.", "Da, vă rog.", "نعم، من فضلك.")],
    ["A", "Verkäuferin", "Sonst noch etwas?", t("Još nešto?", "Başka bir şey?", "Ще щось?", "Mai doriți ceva?", "شيء آخر؟")],
    ["B", "Kundin", "Ja, ich nehme noch vier Brötchen und zwei Brezeln, bitte.", t("Da, uzet ću još četiri peciva i dvije perece, molim.", "Evet, dört küçük ekmek ve iki pretzel daha alayım, lütfen.", "Так, я візьму ще чотири булочки та два кренделі, будь ласка.", "Da, mai iau patru chifle și doi covrigi, vă rog.", "نعم، سآخذ أيضًا أربع لفائف وقطعتين من البريتزل، من فضلك.")],
    ["A", "Verkäuferin", "Das macht acht Euro zwanzig.", t("To je osam eura i dvadeset.", "Sekiz euro yirmi.", "З вас вісім євро двадцять.", "Opt euro și douăzeci.", "ثمانية يورو وعشرون سنتًا.")],
    ["B", "Kundin", "Kann ich mit Karte zahlen?", t("Mogu li platiti karticom?", "Kartla ödeyebilir miyim?", "Можна оплатити карткою?", "Pot plăti cu cardul?", "هل يمكنني الدفع بالبطاقة؟")],
    ["A", "Verkäuferin", "Ja, natürlich.", t("Da, naravno.", "Evet, tabii.", "Так, звичайно.", "Da, bineînțeles.", "نعم، بالتأكيد.")],
    ["B", "Kundin", "Danke. Auf Wiedersehen!", t("Hvala. Doviđenja!", "Teşekkürler. Hoşça kalın!", "Дякую. До побачення!", "Mulțumesc. La revedere!", "شكرًا. إلى اللقاء!")],
    ["A", "Verkäuferin", "Auf Wiedersehen!", t("Doviđenja!", "Hoşça kalın!", "До побачення!", "La revedere!", "إلى اللقاء!")],
  ].map((d, i) => ({ id: `bak-d${i + 1}`, position: i + 1, dialog_index: 1, dialog_title: "Ein Einkauf in der Bäckerei", speaker: d[0], speaker_role: d[1], german_text: d[2], translations: d[3] })),
  questions: [
    { id: "bak-q1", position: 1, kind: "single_choice", prompt: "Mara möchte ein Mischbrot kaufen. Was sagt sie zur Verkäuferin?", explanation: "Alle Antworten klingen grundsätzlich möglich, aber nur eine erfüllt genau Maras Wunsch nach einem Mischbrot.", section: "uebungen", data: {}, quiz_answers: [
      { id: "bak-q1a", position: 1, text: "Ich hätte gern ein Mischbrot, bitte.", is_correct: true },
      { id: "bak-q1b", position: 2, text: "Geben Sie mir bitte ein warmes Brot.", is_correct: false },
      { id: "bak-q1c", position: 3, text: "Haben Sie heute noch Vollkornbrot?", is_correct: false },
    ] },
    { id: "bak-q2", position: 2, kind: "multi_choice", prompt: "Welche Sätze kann eine Kundin in einer Bäckerei wirklich sagen? Mehrere Antworten sind richtig.", explanation: "Es gibt mehrere natürliche Möglichkeiten, höflich etwas zu kaufen.", section: "uebungen", data: {}, quiz_answers: [
      { id: "bak-q2a", position: 1, text: "Zwei Brezeln, bitte.", is_correct: true },
      { id: "bak-q2b", position: 2, text: "Ich nehme vier Brötchen, bitte.", is_correct: true },
      { id: "bak-q2c", position: 3, text: "Ich hätte gern ein Mischbrot, bitte.", is_correct: true },
      { id: "bak-q2d", position: 4, text: "Die Bäckerei ist hinter der Straße.", is_correct: false },
    ] },
    { id: "bak-q3", position: 3, kind: "gap", prompt: "Ich hätte gern ein Mischbrot, _____.", explanation: "Mit „bitte“ klingt die Bestellung höflich.", section: "uebungen", data: {}, quiz_answers: [{ id: "bak-q3a", position: 1, text: "bitte", is_correct: true }] },
    { id: "bak-q4", position: 4, kind: "sentence_order", prompt: "Baue Maras Bestellung richtig auf.", explanation: "Richtig: Ich hätte gern ein Mischbrot, bitte.", section: "uebungen", data: { words: ["Ich", "hätte", "gern", "ein", "Mischbrot,", "bitte."] }, quiz_answers: [] },
    { id: "bak-p1", position: 5, kind: "preposition", prompt: "Die Verkäuferin steht ___ der Theke.", explanation: "Sie steht hinter der Theke.", section: "uebungen", data: { options: ["vor", "hinter", "auf", "unter"] }, quiz_answers: [{ id: "bak-p1a", position: 1, text: "hinter", is_correct: true }] },
    { id: "bak-p2", position: 6, kind: "preposition", prompt: "Mara steht ___ der Theke.", explanation: "Die Kundin steht vor der Theke.", section: "uebungen", data: { options: ["vor", "hinter", "über", "in"] }, quiz_answers: [{ id: "bak-p2a", position: 1, text: "vor", is_correct: true }] },
    { id: "bak-p3", position: 7, kind: "preposition", prompt: "Das Brot liegt ___ Regal.", explanation: "„im“ bedeutet „in dem“.", section: "uebungen", data: { options: ["im", "am", "vor dem", "über dem"] }, quiz_answers: [{ id: "bak-p3a", position: 1, text: "im", is_correct: true }] },
    { id: "bak-p4", position: 8, kind: "preposition", prompt: "Die Tüte liegt ___ der Theke.", explanation: "Die Tüte liegt auf der Theke.", section: "uebungen", data: { options: ["auf", "unter", "hinter", "zwischen"] }, quiz_answers: [{ id: "bak-p4a", position: 1, text: "auf", is_correct: true }] },
    { id: "bak-p5", position: 9, kind: "preposition", prompt: "Die Brezeln liegen ___ den Brötchen.", explanation: "Die Brezeln liegen neben den Brötchen.", section: "uebungen", data: { options: ["neben", "unter", "vor", "über"] }, quiz_answers: [{ id: "bak-p5a", position: 1, text: "neben", is_correct: true }] },
    { id: "bak-p6", position: 10, kind: "preposition", prompt: "Der Kuchen steht ___ dem Brot und den Brezeln.", explanation: "Wenn etwas in der Mitte von zwei Dingen ist, sagen wir „zwischen“.", section: "uebungen", data: { options: ["zwischen", "hinter", "unter", "an"] }, quiz_answers: [{ id: "bak-p6a", position: 1, text: "zwischen", is_correct: true }] },
    { id: "bak-p7", position: 11, kind: "preposition", prompt: "Die Preisschilder hängen ___ den Broten.", explanation: "Die Schilder hängen über den Broten.", section: "uebungen", data: { options: ["über", "unter", "neben", "vor"] }, quiz_answers: [{ id: "bak-p7a", position: 1, text: "über", is_correct: true }] },
    { id: "bak-p8", position: 12, kind: "preposition", prompt: "Der Mülleimer steht ___ der Theke.", explanation: "In dieser Situation steht er unter der Theke.", section: "uebungen", data: { options: ["unter", "auf", "zwischen", "vor"] }, quiz_answers: [{ id: "bak-p8a", position: 1, text: "unter", is_correct: true }] },
    { id: "bak-p9", position: 13, kind: "preposition", prompt: "Das Schild hängt ___ der Tür.", explanation: "Bei einer Position direkt an etwas sagen wir „an“.", section: "uebungen", data: { options: ["an", "unter", "zwischen", "hinter"] }, quiz_answers: [{ id: "bak-p9a", position: 1, text: "an", is_correct: true }] },
    { id: "bak-p10", position: 14, kind: "preposition", prompt: "Die Brötchen sind ___ der Tüte.", explanation: "Die Brötchen sind in der Tüte.", section: "uebungen", data: { options: ["in", "auf", "hinter", "vor"] }, quiz_answers: [{ id: "bak-p10a", position: 1, text: "in", is_correct: true }] },
    { id: "bak-a1", position: 15, kind: "single_choice", prompt: "Welcher Artikel passt? ___ Brot", explanation: "Brot ist neutral: das Brot.", section: "uebungen", data: {}, quiz_answers: [
      { id: "bak-a1a", position: 1, text: "der", is_correct: false }, { id: "bak-a1b", position: 2, text: "die", is_correct: false }, { id: "bak-a1c", position: 3, text: "das", is_correct: true },
    ] },
    { id: "bak-a2", position: 16, kind: "single_choice", prompt: "Welcher Artikel passt? ___ Brezel", explanation: "Brezel ist feminin: die Brezel.", section: "uebungen", data: {}, quiz_answers: [
      { id: "bak-a2a", position: 1, text: "der", is_correct: false }, { id: "bak-a2b", position: 2, text: "die", is_correct: true }, { id: "bak-a2c", position: 3, text: "das", is_correct: false },
    ] },
    { id: "bak-a3", position: 17, kind: "single_choice", prompt: "Welcher Satz ist richtig?", explanation: "Brezel ist feminin, deshalb: eine Brezel.", section: "uebungen", data: {}, quiz_answers: [
      { id: "bak-a3a", position: 1, text: "Ich nehme eine Brezel.", is_correct: true }, { id: "bak-a3b", position: 2, text: "Ich nehme ein Brezel.", is_correct: false }, { id: "bak-a3c", position: 3, text: "Ich nehme einen Brezel.", is_correct: false },
    ] },
    { id: "bak-dq1", position: 18, kind: "single_choice", prompt: "Verkäuferin: „Sonst noch etwas?“ – Welche Antwort passt am besten?", explanation: "Die Antwort muss auf die Frage nach einem weiteren Wunsch reagieren.", section: "uebungen", data: {}, quiz_answers: [
      { id: "bak-dq1a", position: 1, text: "Ja, ich nehme noch zwei Brezeln, bitte.", is_correct: true }, { id: "bak-dq1b", position: 2, text: "Ja, die Bäckerei ist neben der Bank.", is_correct: false }, { id: "bak-dq1c", position: 3, text: "Nein, ich fahre mit dem Bus.", is_correct: false },
    ] },
    { id: "bak-dq2", position: 19, kind: "dialog_order", prompt: "Bringe das kurze Verkaufsgespräch in die richtige Reihenfolge.", explanation: "Erst fragt die Verkäuferin, dann bestellt Mara, danach kommt die Rückfrage zum Schneiden.", section: "uebungen", data: { items: ["Verkäuferin: Was darf es sein?", "Mara: Ich hätte gern ein Mischbrot, bitte.", "Verkäuferin: Möchten Sie das Brot geschnitten?", "Mara: Ja, bitte."] }, quiz_answers: [] },
    { id: "bak-q20", position: 20, kind: "match", prompt: "Ordne die Wörter ihrer Bedeutung in deiner Hilfssprache zu.", explanation: "Wähle links ein deutsches Wort und rechts die passende Bedeutung.", section: "uebungen", data: { pairs: [
      { left: "das Brot", translations: t("hljeb", "ekmek", "хліб", "pâine", "خبز") }, { left: "die Brezel", translations: t("pereca", "pretzel", "крендель", "covrig", "بريتزل") }, { left: "zahlen", translations: t("platiti", "ödemek", "платити", "a plăti", "يدفع") }, { left: "die Tüte", translations: t("kesa", "poşet", "пакет", "pungă", "كيس") },
    ] }, quiz_answers: [] },
    { id: "bak-q21", position: 21, kind: "sentence_order", prompt: "Baue die Frage an der Kasse richtig auf.", explanation: "Richtig: Kann ich mit Karte zahlen?", section: "uebungen", data: { words: ["Kann", "ich", "mit", "Karte", "zahlen?"] }, quiz_answers: [] },
    { id: "bak-t1", position: 101, kind: "single_choice", prompt: "Mara möchte genau ein Mischbrot. Welche Bestellung passt?", explanation: "Die richtige Antwort nennt genau das Mischbrot.", section: "test", data: {}, quiz_answers: [
      { id: "bak-t1a", position: 1, text: "Ich hätte gern ein Mischbrot, bitte.", is_correct: true }, { id: "bak-t1b", position: 2, text: "Geben Sie mir bitte zwei warme Brötchen.", is_correct: false }, { id: "bak-t1c", position: 3, text: "Haben Sie Kuchen ohne Nüsse?", is_correct: false },
    ] },
    { id: "bak-t2", position: 102, kind: "preposition", prompt: "Die Kundin steht ___ der Theke.", explanation: "Sie steht vor der Theke.", section: "test", data: { options: ["vor", "hinter", "über", "unter"] }, quiz_answers: [{ id: "bak-t2a", position: 1, text: "vor", is_correct: true }] },
    { id: "bak-t3", position: 103, kind: "single_choice", prompt: "Welcher Artikel passt? ___ Bäckerei", explanation: "Bäckerei ist feminin: die Bäckerei.", section: "test", data: {}, quiz_answers: [
      { id: "bak-t3a", position: 1, text: "der", is_correct: false }, { id: "bak-t3b", position: 2, text: "die", is_correct: true }, { id: "bak-t3c", position: 3, text: "das", is_correct: false },
    ] },
    { id: "bak-t4", position: 104, kind: "single_choice", prompt: "Was fragt Mara, wenn sie mit Karte bezahlen möchte?", explanation: "„Kann ich mit Karte zahlen?“ ist eine natürliche Frage an der Kasse.", section: "test", data: {}, quiz_answers: [
      { id: "bak-t4a", position: 1, text: "Kann ich mit Karte zahlen?", is_correct: true }, { id: "bak-t4b", position: 2, text: "Wo ist meine Bushaltestelle?", is_correct: false }, { id: "bak-t4c", position: 3, text: "Ist die Brezel hinter der Karte?", is_correct: false },
    ] },
    { id: "bak-t5", position: 105, kind: "sentence_order", prompt: "Baue die höfliche Bestellung richtig auf.", explanation: "Richtig: Zwei Brezeln, bitte.", section: "test", data: { words: ["Zwei", "Brezeln,", "bitte."] }, quiz_answers: [] },
    { id: "bak-t6", position: 106, kind: "true_false", prompt: "„Die Verkäuferin steht hinter der Theke.“ beschreibt einen Ort.", explanation: "Ja. „hinter“ beschreibt hier die Position der Verkäuferin.", section: "test", data: {}, quiz_answers: [
      { id: "bak-t6a", position: 1, text: "Richtig", is_correct: true }, { id: "bak-t6b", position: 2, text: "Falsch", is_correct: false },
    ] },
    { id: "bak-t7", position: 107, kind: "dialog_order", prompt: "Ordne den Abschluss des Einkaufs.", explanation: "Preis → Zahlungsfrage → Antwort → Verabschiedung.", section: "test", data: { items: ["Verkäuferin: Das macht acht Euro zwanzig.", "Mara: Kann ich mit Karte zahlen?", "Verkäuferin: Ja, natürlich.", "Mara: Danke. Auf Wiedersehen!"] }, quiz_answers: [] },
    { id: "bak-t8", position: 108, kind: "match", prompt: "Ordne die Wörter zu.", explanation: "Die Bedeutungen richten sich nach deiner Hilfssprache.", section: "test", data: { pairs: [
      { left: "die Theke", translations: t("pult", "tezgâh", "прилавок", "tejghea", "منضدة") }, { left: "geschnitten", translations: t("narezan", "dilimlenmiş", "нарізаний", "feliat", "مقطّع") }, { left: "bitte", translations: t("molim", "lütfen", "будь ласка", "vă rog", "من فضلك") },
    ] }, quiz_answers: [] },
  ],
};
