const T = (bks: string, tr: string, uk: string, ro: string, ar: string) => ({ bks, tr, uk, ro, ar });
const A = (id: string, text: string, is_correct: boolean, position: number) => ({ id, text, is_correct, position });
const H = (bks: string, tr: string, uk: string, ro: string, ar: string) => ({ help: T(bks, tr, uk, ro, ar) });

/* Wiederverwendbare Regel-Hilfen (erklären die Regel, nie die Lösung). */
const HELP = {
  nom: H("Subjekt = nominativ: der/die/das.", "Özne = yalın hâl: der/die/das.", "Підмет — називний: der/die/das.", "Subiectul = nominativ: der/die/das.", "الفاعل يأتي بحالة الرفع: der/die/das."),
  akk: H("Objekt uz nehmen/kaufen traži akuzativ: der → den, die → die, das → das.", "nehmen/kaufen nesnesi -i hâli ister: der → den, die → die, das → das.", "Додаток після nehmen/kaufen — знахідний: der → den.", "Complementul cere acuzativ: der → den, die → die, das → das.", "المفعول به بعد nehmen/kaufen: der → den."),
  dat: H("Poslije mit/in/auf/an dolazi dativ: der → dem, die → der, das → dem.", "mit/in/auf/an sonrası -e hâli: der → dem, die → der, das → dem.", "Після mit/in/auf/an — давальний: der → dem, die → der.", "După mit/in/auf/an urmează dativ: der → dem, die → der.", "بعد mit/in/auf/an تأتي حالة الجر: der → dem, die → der."),
  unbest: H("Neodređeni član: muški ein, ženski eine, srednji ein; u akuzativu muški einen.", "Belirsiz artikel: eril ein, dişil eine, nötr ein; -i hâlinde eril einen.", "Неозначений артикль: ein/eine/ein; у знахідному чол. einen.", "Articol nehotărât: ein/eine/ein; la acuzativ masculin einen.", "أداة النكرة: ein/eine/ein، وفي المفعول للمذكر einen."),
  weil: H("weil daje razlog, glagol ide na kraj.", "weil sebep bildirir, fiil sona gider.", "weil вводить причину, дієслово в кінці.", "weil dă motivul, verbul merge la final.", "weil تعطي السبب والفعل في النهاية."),
  deshalb: H("deshalb daje posljedicu, glagol dolazi odmah iza.", "deshalb sonuç bildirir, fiil hemen sonra gelir.", "deshalb вводить наслідок, дієслово одразу після.", "deshalb arată consecința, verbul urmează imediat.", "deshalb تعبّر عن النتيجة والفعل يليها مباشرة."),
  komp: H("Poređenje: pridjev + -er + als.", "Karşılaştırma: sıfat + -er + als.", "Порівняння: прикметник + -er + als.", "Comparativ: adjectiv + -er + als.", "المقارنة: صفة + -er + als."),
  welch: H("welcher/welche/welches slijedi rod imenice.", "welcher/welche/welches ismin cinsine uyar.", "welcher/welche/welches залежить від роду.", "welcher/welche/welches urmează genul substantivului.", "welcher/welche/welches تتبع جنس الاسم."),
  praep: H("Prijedlog opisuje mjesto: gegenüber, auf, in, vor, hinter, neben, zwischen, unter, über, an.", "Edat yeri belirtir: gegenüber, auf, in, vor, hinter, neben, zwischen, unter, über, an.", "Прийменник вказує місце: gegenüber, auf, in, vor, hinter …", "Prepoziția arată locul: gegenüber, auf, in, vor, hinter …", "حرف الجر يحدد المكان: gegenüber, auf, in, vor, hinter …"),
  hoefl: H("Pristojno: Ich hätte gern … / Könnten Sie …?", "Kibarca: Ich hätte gern … / Könnten Sie …?", "Ввічливо: Ich hätte gern … / Könnten Sie …?", "Politicos: Ich hätte gern … / Könnten Sie …?", "بأدب: Ich hätte gern … / Könnten Sie …؟"),
  perfekt: H("Perfekt: haben + particip (ge…t / ge…en) na kraju.", "Perfekt: haben + ge…t / ge…en fiil sonda.", "Perfekt: haben + дієприкметник у кінці.", "Perfect: haben + participiu la final.", "الماضي: haben + اسم المفعول في النهاية."),
  lieber: H("lieber izražava šta više voliš.", "lieber tercihini gösterir.", "lieber показує, що подобається більше.", "lieber arată preferința.", "lieber تعبّر عن التفضيل."),
  menge: H("Količina: ein Stück, eine Scheibe, ein halbes Brot – imenica bez člana iza mjere.", "Miktar: ein Stück, eine Scheibe, ein halbes Brot.", "Кількість: ein Stück, eine Scheibe, ein halbes Brot.", "Cantitate: ein Stück, eine Scheibe, ein halbes Brot.", "الكمية: ein Stück, eine Scheibe, ein halbes Brot."),
  koennen: H("Modalni glagol können: drugi glagol u infinitivu na kraju.", "können modalı: ikinci fiil mastar hâlde sonda.", "Модальне können: другий інфінітив у кінці.", "Modalul können: al doilea verb la infinitiv, la final.", "الفعل können: الفعل الثاني مصدر في النهاية."),
  etwas: H("etwas = nešto, nichts = ništa; pridjev iza njih piše se veliko: etwas Süßes.", "etwas = bir şey, nichts = hiçbir şey; sonrasındaki sıfat büyük yazılır.", "etwas = щось, nichts = нічого; прикметник після них з великої.", "etwas = ceva, nichts = nimic; adjectivul se scrie cu majusculă.", "etwas = شيء، nichts = لا شيء، والصفة بعدهما بحرف كبير."),
  genug: H("genug ide iza imenice/pridjeva: genug Bargeld, nicht genug.", "genug isimden sonra gelir: genug Bargeld, nicht genug.", "genug стоїть після іменника: genug Bargeld.", "genug stă după substantiv: genug Bargeld.", "genug تأتي بعد الاسم: genug Bargeld."),
  wortschatz: H("Razmisli o značenju riječi u ovoj situaciji u pekari.", "Kelimenin fırındaki anlamını düşün.", "Подумай про значення слова в пекарні.", "Gândește-te la sensul cuvântului în brutărie.", "فكّر في معنى الكلمة داخل المخبز."),
};

type Q = { id: string; position: number; kind: string; section: string; prompt: string; explanation: string; data: Record<string, unknown>; quiz_answers: { id: string; text: string; is_correct: boolean; position: number }[] };

let seq = 0;
const P = () => ++seq;
const sc = (id: string, section: string, prompt: string, explanation: string, correct: string, wrong: string[], help?: Record<string, unknown>): Q => ({ id, position: P(), kind: "single_choice", section, prompt, explanation, data: { ...(help ?? {}) }, quiz_answers: [A("a", correct, true, 1), ...wrong.map((w, i) => A(`b${i}`, w, false, i + 2))] });
const mc = (id: string, section: string, prompt: string, explanation: string, correct: string[], wrong: string[], help?: Record<string, unknown>): Q => ({ id, position: P(), kind: "multi_choice", section, prompt, explanation, data: { ...(help ?? {}) }, quiz_answers: [...correct.map((c, i) => A(`a${i}`, c, true, i + 1)), ...wrong.map((w, i) => A(`b${i}`, w, false, correct.length + i + 1))] });
const tf = (id: string, section: string, prompt: string, explanation: string, isTrue: boolean, help?: Record<string, unknown>): Q => ({ id, position: P(), kind: "true_false", section, prompt, explanation, data: { ...(help ?? {}) }, quiz_answers: [A("a", "Richtig", isTrue, 1), A("b", "Falsch", !isTrue, 2)] });
const gap = (id: string, section: string, prompt: string, explanation: string, correct: string, options: string[], help?: Record<string, unknown>): Q => ({ id, position: P(), kind: "gap_select", section, prompt, explanation, data: { options, ...(help ?? {}) }, quiz_answers: [A("a", correct, true, 1)] });
const so = (id: string, section: string, prompt: string, explanation: string, words: string[], help?: Record<string, unknown>): Q => ({ id, position: P(), kind: "sentence_order", section, prompt, explanation, data: { words, ...(help ?? {}) }, quiz_answers: [] });
const dord = (id: string, section: string, prompt: string, explanation: string, items: string[], help?: Record<string, unknown>): Q => ({ id, position: P(), kind: "dialog_order", section, prompt, explanation, data: { items, ...(help ?? {}) }, quiz_answers: [] });
const ordq = (id: string, section: string, prompt: string, explanation: string, items: string[], help?: Record<string, unknown>): Q => ({ id, position: P(), kind: "order", section, prompt, explanation, data: { items, ...(help ?? {}) }, quiz_answers: [] });
const mt = (id: string, section: string, prompt: string, explanation: string, pairs: { left: string; right: string }[], help?: Record<string, unknown>): Q => ({ id, position: P(), kind: "match", section, prompt, explanation, data: { pairs, ...(help ?? {}) }, quiz_answers: [] });
const ic = (id: string, section: string, prompt: string, explanation: string, image_key: string, correct: string, wrong: string[], help?: Record<string, unknown>): Q => ({ id, position: P(), kind: "image_choice", section, prompt, explanation, data: { image_key, ...(help ?? {}) }, quiz_answers: [A("a", correct, true, 1), ...wrong.map((w, i) => A(`b${i}`, w, false, i + 2))] });

/* Kurze A2-Lernhinweise passend zur jeweiligen Szene (Position -> Hinweis). */
const SCENE_HINTS: Record<number, string> = {
  1: "Ort beschreiben: „Die Bäckerei ist gegenüber meiner Wohnung.“",
  2: "Weg beschreiben: „Ich gehe kurz über die Straße.“",
  3: "Auslage ansehen: „In der Auslage liegen frische Brötchen.“",
  4: "Begrüßung im Laden: „Guten Morgen. – Kann ich Ihnen helfen?“",
  5: "Überlegen: „Ich schaue nur kurz, danke.“",
  6: "Wunsch genauer beschreiben: „Ich hätte gern etwas Süßes, aber nicht zu süß.“",
  7: "Nach dem Unterschied fragen: „Was ist der Unterschied zwischen den beiden?“",
  8: "Empfehlung erfragen: „Was können Sie empfehlen?“ – „Der Apfelkuchen ist frisch gebacken.“",
  9: "Vergleichen: „Welcher Kuchen ist weniger süß?“",
  10: "Komparativ mit als: „Der Apfelkuchen ist weniger süß als die Torte.“",
  11: "Menge angeben: „Ein Stück Apfelkuchen, bitte.“",
  12: "Zusätzlich bestellen: „Und ich brauche noch ein Brot fürs Abendessen.“",
  13: "Brotsorten vergleichen: „Roggenbrot ist kräftiger, Mischbrot ist milder.“",
  14: "Vorliebe zeigen: „Ich nehme lieber das Mischbrot.“",
  15: "Größe wählen: „Haben Sie das auch kleiner?“",
  16: "Grund nennen mit weil: „…, weil wir nur zu zweit sind.“",
  17: "Frage im Laden: „Möchten Sie das Brot geschnitten oder ganz?“",
  18: "Folge nennen mit deshalb: „Ich friere die Hälfte ein, deshalb bitte geschnitten.“",
  19: "Scheiben: „Zwei Scheiben reichen mir am Morgen.“",
  20: "Einpacken: „Kommt alles in eine Tüte?“",
  21: "Gesamtpreis erfragen: „Was macht das zusammen?“",
  22: "Problem nennen: „Ich habe nicht genug Bargeld dabei.“",
  23: "Alternative anbieten: „Kann ich mit Karte zahlen?“",
  24: "Kassenbon: „Möchten Sie den Bon?“ – „Ja, bitte.“",
  25: "Abschluss und Rückweg: „Danke, schönen Tag noch!“",
};

export const bakeryA2Override = {
  lesson: {
    id: "22222222-2222-2222-2222-222222222223",
    slug: "baeckerei-a2",
    title: "In der Bäckerei",
    description: "A2: Wünsche genauer beschreiben, Empfehlungen erfragen, zwei Produkte vergleichen, Gründe nennen und mit Bargeld oder Karte bezahlen.",
    level: "A2",
    region: "de",
    category_slug: "alltag",
    subcategory_slug: "baeckerei",
    topic_slug: "baeckerei",
    topic_title: "In der Bäckerei",
    duration_seconds: 3600,
    thumbnail_key: "baeckerei",
    video_url: null,
    is_premium: false,
    status: "published",
    popularity: 99,
    grammar_topics: ["Artikel und Fälle", "Akkusativ", "Dativ nach Präpositionen", "weil und deshalb", "Komparativ mit als", "welcher / welche / welches", "Mengenangaben", "höfliche Wünsche", "Modalverb können", "Perfekt im Alltag"],
    grammar_notes: [
      { title: "Artikel im Nominativ", explanation: "Das Subjekt steht im Nominativ. Merke dir jedes Wort mit dem Artikel: der Kuchen, die Tüte, das Brot.", examples: ["Der Kuchen ist frisch.", "Die Tüte ist klein.", "Das Brot kostet 3,20 Euro."] },
      { title: "Akkusativ – was nehme ich?", explanation: "Nach nehmen, kaufen, möchten, brauchen steht der Akkusativ. Nur der wird zu den. die und das bleiben gleich.", examples: ["Ich nehme den Kuchen.", "Ich kaufe das Brot.", "Ich brauche die Tüte."] },
      { title: "Unbestimmter Artikel", explanation: "ein Kuchen, eine Brezel, ein Brot. Im Akkusativ wird nur männlich zu einen: Ich möchte einen Kuchen.", examples: ["Ich kaufe ein Brot.", "Ich brauche eine Tüte.", "Ich möchte einen Kaffee."] },
      { title: "Dativ nach einfachen Präpositionen", explanation: "Nach mit, in, auf, an, bei steht meistens der Dativ: der/das → dem, die → der.", examples: ["Ich zahle mit der Karte.", "Wir sind in der Bäckerei.", "Das Gerät steht auf der Theke."] },
      { title: "weil und deshalb", explanation: "weil nennt den Grund, das Verb geht ans Ende. deshalb nennt die Folge, das Verb kommt direkt danach.", examples: ["Ich nehme das kleinere Brot, weil wir nur zu zweit sind.", "Ich habe wenig Bargeld, deshalb zahle ich mit Karte."] },
      { title: "Vergleichen mit dem Komparativ", explanation: "Adjektiv + -er + als. Bei kurzen Wörtern oft mit Umlaut: groß → größer.", examples: ["Das Roggenbrot ist kräftiger als das Mischbrot.", "Das kleine Brot ist billiger als das große.", "Ich esse lieber Brot als Kuchen."] },
      { title: "welcher / welche / welches", explanation: "Die Frage richtet sich nach dem Artikel: der Kuchen → welcher Kuchen, die Tüte → welche Tüte, das Brot → welches Brot.", examples: ["Welcher Kuchen ist frisch?", "Welche Brotsorte empfehlen Sie?", "Welches Brot ist kleiner?"] },
      { title: "Mengen angeben", explanation: "Nach der Menge steht das Produkt ohne Artikel: ein Stück Kuchen, zwei Scheiben Brot, ein halbes Brot.", examples: ["Ein Stück Apfelkuchen, bitte.", "Zwei Scheiben reichen mir.", "Ich nehme ein halbes Brot."] },
      { title: "Höflich bestellen und fragen", explanation: "Ich hätte gern … ist höflicher als Ich will … . Mit Könnten Sie …? bittet man freundlich.", examples: ["Ich hätte gern ein Mischbrot.", "Könnten Sie es bitte schneiden?", "Kann ich mit Karte zahlen?"] },
      { title: "Perfekt im Alltag", explanation: "haben + Partizip II am Satzende. So erzählst du kurz, was schon passiert ist.", examples: ["Ich habe den Kuchen schon probiert.", "Wir haben gestern hier Brot gekauft.", "Ich habe die Karte mitgenommen."] },
    ],
    place_items: [
      { german_text: "Die Bäckerei ist gegenüber Maras Wohnung.", preposition: "gegenüber", image_key: "baeck-fenster", translations: T("Pekara je preko puta Marinog stana.", "Fırın, Mara'nın evinin karşısında.", "Пекарня навпроти квартири Мари.", "Brutăria este vizavi de apartamentul Marei.", "المخبز مقابل شقة مارا.") },
      { german_text: "Mara geht über die Straße.", preposition: "über", image_key: "baeck-strasse", translations: T("Mara prelazi preko ulice.", "Mara caddenin karşısına geçiyor.", "Мара переходить через вулицю.", "Mara traversează strada.", "تعبر مارا الشارع.") },
      { german_text: "Die Verkäuferin steht hinter der Theke.", preposition: "hinter", image_key: "baeck-ill-01", translations: T("Prodavačica stoji iza pulta.", "Satıcı tezgâhın arkasında.", "Продавчиня за прилавком.", "Vânzătoarea este în spatele tejghelei.", "البائعة خلف المنضدة.") },
      { german_text: "Die Kuchen liegen in der Auslage.", preposition: "in", image_key: "baeck-ill-02", translations: T("Kolači su u vitrini.", "Pastalar vitrinde.", "Торти лежать у вітрині.", "Prăjiturile sunt în vitrină.", "الكعك في واجهة العرض.") },
      { german_text: "Zwei Kuchen stehen nebeneinander.", preposition: "neben", image_key: "baeck-ill-03", translations: T("Dva kolača stoje jedan pored drugog.", "İki pasta yan yana duruyor.", "Дві торти стоять поруч.", "Două prăjituri stau una lângă alta.", "كعكتان بجانب بعضهما.") },
      { german_text: "Das Kartenlesegerät steht auf der Theke.", preposition: "auf", image_key: "baeck-ill-09", translations: T("Čitač kartica je na pultu.", "Kart okuyucu tezgâhın üstünde.", "Термінал стоїть на прилавку.", "Cititorul de card este pe tejghea.", "جهاز البطاقة على المنضدة.") },
    ],
  },

  scenes: ([
    { id: "a2-s1", position: 1, image_key: "baeck-fenster", scene_type: "context", german_text: "Mara schaut aus dem Fenster ihrer Wohnung. Die Bäckerei liegt direkt gegenüber auf der anderen Straßenseite.", translations: T("Mara gleda kroz prozor svog stana. Pekara je odmah preko puta.", "Mara evinin penceresinden bakıyor. Fırın tam karşıda.", "Мара дивиться з вікна своєї квартири. Пекарня прямо навпроти.", "Mara privește pe fereastra apartamentului. Brutăria este chiar vizavi.", "تنظر مارا من نافذة شقتها. المخبز يقع مباشرة في الجهة المقابلة.") },
    { id: "a2-s2", position: 2, image_key: "baeck-strasse", scene_type: "enter", german_text: "Mara verlässt ihre Wohnung und geht über die Straße zur Bäckerei.", translations: T("Mara izlazi iz stana i prelazi ulicu do pekare.", "Mara evden çıkıp karşıdaki fırına gidiyor.", "Мара виходить з квартири й переходить вулицю до пекарні.", "Mara iese din apartament și traversează strada spre brutărie.", "تخرج مارا من شقتها وتعبر الشارع إلى المخبز.") },
    { id: "a2-s3", position: 3, image_key: "baeck-ill-02", scene_type: "look", german_text: "Sie betritt die Bäckerei und sieht die große Auslage.", translations: T("Ulazi u pekaru i vidi veliku vitrinu.", "Fırına giriyor ve büyük vitrini görüyor.", "Вона заходить до пекарні й бачить велику вітрину.", "Intră în brutărie și vede vitrina mare.", "تدخل المخبز وترى واجهة العرض الكبيرة.") },
    { id: "a2-s4", position: 4, image_key: "baeck-ill-01", scene_type: "greeting", german_text: "Die Verkäuferin begrüßt Mara freundlich und fragt, ob sie helfen kann.", translations: T("Prodavačica ljubazno pozdravlja Maru i pita može li pomoći.", "Satıcı Mara'yı sıcak karşılıyor ve yardım edip edemeyeceğini soruyor.", "Продавчиня привітно вітає Мару й питає, чи може допомогти.", "Vânzătoarea o salută prietenos pe Mara și întreabă dacă o poate ajuta.", "ترحب البائعة بمارا وتسأل إن كانت تستطيع مساعدتها.") },
    { id: "a2-s5", position: 5, image_key: "baeck-ill-02", scene_type: "look", german_text: "Mara schaut sich mehrere Kuchen an und überlegt, was sie nehmen möchte.", translations: T("Mara gleda nekoliko kolača i razmišlja šta želi uzeti.", "Mara birkaç pastaya bakıp hangisini alacağını düşünüyor.", "Мара розглядає кілька тортів і думає, який взяти.", "Mara se uită la mai multe prăjituri și se gândește ce să ia.", "تنظر مارا إلى عدة أنواع من الكعك وتفكر ماذا ستختار.") },
    { id: "a2-s6", position: 6, image_key: "baeck-ill-01", scene_type: "ask", german_text: "Sie erklärt, dass sie etwas Süßes sucht, das nicht zu schwer und nicht zu süß ist.", translations: T("Objašnjava da traži nešto slatko što nije preteško ni preslatko.", "Çok ağır ve çok tatlı olmayan bir şey aradığını söylüyor.", "Вона пояснює, що шукає щось солодке, але не надто важке й солодке.", "Spune că vrea ceva dulce, dar nu prea greu și nu prea dulce.", "توضح أنها تبحث عن شيء حلو لكنه ليس ثقيلاً أو شديد الحلاوة.") },
    { id: "a2-s7", position: 7, image_key: "baeck-ill-03", scene_type: "choice", german_text: "Die Verkäuferin zeigt Mara zwei passende Kuchen und erklärt den Unterschied.", translations: T("Prodavačica pokazuje Mari dva odgovarajuća kolača i objašnjava razliku.", "Satıcı Mara'ya iki uygun pasta gösterip farkı açıklıyor.", "Продавчиня показує Марі два відповідні торти й пояснює різницю.", "Vânzătoarea îi arată Marei două prăjituri potrivite și explică diferența.", "تعرض البائعة على مارا خيارين مناسبين وتشرح الفرق.") },
    { id: "a2-s8", position: 8, image_key: "baeck-ill-03", scene_type: "compare", german_text: "Sie empfiehlt den Apfelkuchen, weil er heute frisch gebacken wurde.", translations: T("Preporučuje kolač od jabuka jer je danas svježe pečen.", "Bugün taze piştiği için elmalı pastayı öneriyor.", "Вона радить яблучний пиріг, бо його сьогодні свіжо спекли.", "Recomandă prăjitura cu mere pentru că a fost coaptă azi.", "توصي بكعكة التفاح لأنها خُبزت اليوم طازجة.") },
    { id: "a2-s9", position: 9, image_key: "baeck-ill-03", scene_type: "ask", german_text: "Mara fragt, welcher Kuchen weniger süß ist.", translations: T("Mara pita koji je kolač manje sladak.", "Mara hangi pastanın daha az tatlı olduğunu soruyor.", "Мара питає, який торт менш солодкий.", "Mara întreabă care prăjitură este mai puțin dulce.", "تسأل مارا أي الكعكين أقل حلاوة.") },
    { id: "a2-s10", position: 10, image_key: "baeck-ill-03", scene_type: "compare", german_text: "Die Verkäuferin erklärt, dass der Apfelkuchen weniger süß als die Torte ist.", translations: T("Prodavačica objašnjava da je kolač od jabuka manje sladak od torte.", "Satıcı elmalı pastanın tortadan daha az tatlı olduğunu açıklıyor.", "Продавчиня пояснює, що яблучний пиріг менш солодкий за торт.", "Vânzătoarea explică faptul că prăjitura cu mere este mai puțin dulce decât tortul.", "توضح البائعة أن كعكة التفاح أقل حلاوة من التورتة.") },
    { id: "a2-s11", position: 11, image_key: "baeck-ill-04", scene_type: "select", german_text: "Mara entscheidet sich für ein Stück Apfelkuchen.", translations: T("Mara se odlučuje za komad kolača od jabuka.", "Mara bir dilim elmalı pasta seçiyor.", "Мара обирає шматок яблучного пирога.", "Mara alege o felie de prăjitură cu mere.", "تختار مارا قطعة من كعكة التفاح.") },
    { id: "a2-s12", position: 12, image_key: "baeck-ill-01", scene_type: "ask", german_text: "Sie fragt zusätzlich nach einem Brot für das Abendessen.", translations: T("Dodatno pita za hljeb za večeru.", "Ayrıca akşam yemeği için ekmek soruyor.", "Вона також питає про хліб на вечерю.", "Mai întreabă și de o pâine pentru cină.", "وتسأل أيضًا عن خبز للعشاء.") },
    { id: "a2-s13", position: 13, image_key: "baeck-ill-06", scene_type: "choice", german_text: "Die Verkäuferin zeigt ein Roggenbrot und ein helleres Mischbrot.", translations: T("Prodavačica pokazuje raženi hljeb i svjetliji miješani hljeb.", "Satıcı bir çavdar ekmeği ve daha açık renkli karışık ekmek gösteriyor.", "Продавчиня показує житній і світліший змішаний хліб.", "Vânzătoarea arată o pâine de secară și una mixtă mai deschisă.", "تعرض البائعة خبز الجاودار وخبزًا مخلوطًا أفتح لونًا.") },
    { id: "a2-s14", position: 14, image_key: "baeck-ill-06", scene_type: "compare", german_text: "Sie erklärt, dass das Roggenbrot kräftiger schmeckt und länger satt macht.", translations: T("Objašnjava da raženi hljeb ima jači okus i duže drži sitost.", "Çavdar ekmeğinin daha yoğun olduğunu ve daha uzun tok tuttuğunu söylüyor.", "Вона пояснює, що житній хліб має насиченіший смак і довше насичує.", "Explică faptul că pâinea de secară are gust mai intens și ține de foame mai mult.", "توضح أن خبز الجاودار أقوى نكهة ويشبع لمدة أطول.") },
    { id: "a2-s15", position: 15, image_key: "baeck-ill-06", scene_type: "select", german_text: "Mara nimmt das kleinere Roggenbrot, weil sie heute nur zu zweit essen.", translations: T("Mara uzima manji raženi hljeb jer danas jedu samo dvoje.", "Mara küçük çavdar ekmeğini alıyor çünkü bugün sadece iki kişiler.", "Мара бере менший житній хліб, бо сьогодні їдять лише вдвох.", "Mara ia pâinea de secară mai mică pentru că azi mănâncă doar doi.", "تأخذ مارا خبز الجاودار الأصغر لأنهما سيأكلان شخصين فقط.") },
    { id: "a2-s16", position: 16, image_key: "baeck-ill-06", scene_type: "ask", german_text: "Die Verkäuferin fragt: Geschnitten oder ganz?", translations: T("Prodavačica pita: Narezano ili cijelo?", "Satıcı soruyor: Dilimlenmiş mi bütün mü?", "Продавчиня питає: Нарізати чи залишити цілим?", "Vânzătoarea întreabă: Feliată sau întreagă?", "تسأل البائعة: مقطع أم كامل؟") },
    { id: "a2-s17", position: 17, image_key: "baeck-ill-06", scene_type: "select", german_text: "Mara möchte das Brot geschnitten, damit sie es später leichter einfrieren kann.", translations: T("Mara želi narezani hljeb da ga kasnije lakše zamrzne.", "Mara ekmeği dilimlenmiş istiyor, böylece sonra daha kolay dondurabilir.", "Мара хоче нарізаний хліб, щоб потім легше заморозити.", "Mara vrea pâinea feliată ca să o poată congela mai ușor.", "تريد مارا الخبز مقطعًا كي تتمكن من تجميده بسهولة لاحقًا.") },
    { id: "a2-s18", position: 18, image_key: "baeck-ill-07", scene_type: "solution", german_text: "Das Brot wird in der Schneidemaschine in gleichmäßige Scheiben geschnitten.", translations: T("Hljeb se u mašini reže na jednake kriške.", "Ekmek dilimleme makinesinde eşit dilimlere kesiliyor.", "Хліб у машині нарізають на рівні скибки.", "Pâinea este tăiată în felii egale în mașina de feliat.", "يُقطع الخبز في آلة التقطيع إلى شرائح متساوية.") },
    { id: "a2-s19", position: 19, image_key: "baeck-ill-08", scene_type: "handover", german_text: "Die Verkäuferin packt Brot und Kuchen getrennt ein.", translations: T("Prodavačica pakuje hljeb i kolač odvojeno.", "Satıcı ekmek ve pastayı ayrı ayrı paketliyor.", "Продавчиня пакує хліб і пиріг окремо.", "Vânzătoarea împachetează separat pâinea și prăjitura.", "تغلف البائعة الخبز والكعك كلًا على حدة.") },
    { id: "a2-s20", position: 20, image_key: "baeck-ill-08", scene_type: "pay_cash", german_text: "An der Kasse fragt Mara nach dem Gesamtpreis und nach einer kleinen Tüte.", translations: T("Na kasi Mara pita za ukupnu cijenu i malu vrećicu.", "Kasada Mara toplam fiyatı ve küçük bir poşeti soruyor.", "На касі Мара питає загальну ціну й маленький пакет.", "La casă, Mara întreabă prețul total și cere o pungă mică.", "عند الصندوق تسأل مارا عن السعر الإجمالي وكيس صغير.") },
    { id: "a2-s21", position: 21, image_key: "baeck-ill-08", scene_type: "pay_cash", german_text: "Die Verkäuferin nennt den Gesamtpreis und zeigt ihn auf der Kasse.", translations: T("Prodavačica kaže ukupnu cijenu i pokazuje je na kasi.", "Satıcı toplam fiyatı söylüyor ve kasada gösteriyor.", "Продавчиня називає загальну суму й показує її на касі.", "Vânzătoarea spune prețul total și îl arată la casă.", "تذكر البائعة السعر الإجمالي وتعرضه على شاشة الصندوق.") },
    { id: "a2-s22", position: 22, image_key: "baeck-wallet", scene_type: "wallet", needs_image: false, german_text: "Mara schaut in ihre Geldbörse und merkt, dass sie nicht genug Bargeld dabeihat.", translations: T("Mara gleda u novčanik i vidi da nema dovoljno gotovine.", "Mara cüzdanına bakıp yeterince nakdi olmadığını fark ediyor.", "Мара дивиться в гаманець і помічає, що має недостатньо готівки.", "Mara se uită în portofel și vede că nu are destui bani cash.", "تنظر مارا في محفظتها وتلاحظ أنه ليس معها ما يكفي من النقود.") },
    { id: "a2-s23", position: 23, image_key: "baeck-ill-09", scene_type: "pay_card", german_text: "Sie fragt, ob sie mit Karte bezahlen kann.", translations: T("Pita može li platiti karticom.", "Kartla ödeyip ödeyemeyeceğini soruyor.", "Вона питає, чи можна заплатити карткою.", "Întreabă dacă poate plăti cu cardul.", "تسأل إن كان بإمكانها الدفع بالبطاقة.") },
    { id: "a2-s24", position: 24, image_key: "baeck-bon", scene_type: "receipt", needs_image: false, german_text: "Mara bezahlt mit Karte und bekommt den Kassenbon.", translations: T("Mara plaća karticom i dobija račun.", "Mara kartla ödüyor ve fişi alıyor.", "Мара платить карткою й отримує чек.", "Mara plătește cu cardul și primește bonul.", "تدفع مارا بالبطاقة وتحصل على الإيصال.") },
    { id: "a2-s25", position: 25, image_key: "baeck-heimweg", scene_type: "return_home", needs_image: false, german_text: "Mara nimmt die Tüte, bedankt sich und geht zurück zu ihrer Wohnung gegenüber.", translations: T("Mara uzima vrećicu, zahvaljuje se i vraća se u stan preko puta.", "Mara poşeti alıyor, teşekkür ediyor ve karşıdaki evine dönüyor.", "Мара бере пакет, дякує й повертається до квартири навпроти.", "Mara ia punga, mulțumește și se întoarce în apartamentul de vizavi.", "تأخذ مارا الكيس وتشكر البائعة وتعود إلى شقتها المقابلة.") }
  ] as { id: string; position: number; image_key: string; scene_type: string; german_text: string; translations: Record<string, string>; needs_image?: boolean }[]).map((s) => ({ ...s, hint: SCENE_HINTS[s.position] ?? null })),

  vocab: ([
    ["die Bäckerei", "Nomen", "die", "die Bäckereien", "Die Bäckerei ist gleich gegenüber.", T("pekara", "fırın", "пекарня", "brutărie", "مخبز")],
    ["die Auslage", "Nomen", "die", "die Auslagen", "In der Auslage liegen frische Brötchen.", T("vitrina", "vitrin", "вітрина", "vitrină", "واجهة العرض")],
    ["die Theke", "Nomen", "die", "die Theken", "Die Verkäuferin steht hinter der Theke.", T("pult", "tezgâh", "прилавок", "tejghea", "منضدة")],
    ["die Empfehlung", "Nomen", "die", "die Empfehlungen", "Haben Sie eine Empfehlung für mich?", T("preporuka", "öneri", "рекомендація", "recomandare", "توصية")],
    ["die Brotsorte", "Nomen", "die", "die Brotsorten", "Welche Brotsorte ist kräftiger?", T("vrsta hljeba", "ekmek çeşidi", "вид хліба", "tip de pâine", "نوع الخبز")],
    ["das Roggenbrot", "Nomen", "das", "die Roggenbrote", "Das Roggenbrot schmeckt kräftig.", T("raženi hljeb", "çavdar ekmeği", "житній хліб", "pâine de secară", "خبز الجاودار")],
    ["das Mischbrot", "Nomen", "das", "die Mischbrote", "Ich nehme lieber ein Mischbrot.", T("miješani hljeb", "karışık ekmek", "змішаний хліб", "pâine mixtă", "خبز مخلوط")],
    ["der Apfelkuchen", "Nomen", "der", "die Apfelkuchen", "Ein Stück Apfelkuchen, bitte.", T("kolač od jabuka", "elmalı pasta", "яблучний пиріг", "prăjitură cu mere", "كعكة التفاح")],
    ["der Unterschied", "Nomen", "der", "die Unterschiede", "Was ist der Unterschied zwischen den beiden?", T("razlika", "fark", "різниця", "diferență", "فرق")],
    ["das Stück", "Nomen", "das", "die Stücke", "Ich hätte gern ein Stück Kuchen.", T("komad", "dilim/parça", "шматок", "bucată", "قطعة")],
    ["die Scheibe", "Nomen", "die", "die Scheiben", "Zwei Scheiben reichen mir am Morgen.", T("kriška", "dilim", "скибка", "felie", "شريحة")],
    ["die Hälfte", "Nomen", "die", "die Hälften", "Die Hälfte friere ich ein.", T("polovina", "yarısı", "половина", "jumătate", "النصف")],
    ["frisch gebacken", "Wendung", null, null, "Der Apfelkuchen ist heute frisch gebacken.", T("svježe pečeno", "taze pişmiş", "свіжоспечений", "proaspăt copt", "مخبوز طازج")],
    ["kräftig", "Adjektiv", null, null, "Roggenbrot schmeckt kräftig.", T("jakog okusa", "yoğun tatlı/sert", "насичений", "intens", "قوي النكهة")],
    ["mild", "Adjektiv", null, null, "Das Mischbrot ist milder.", T("blag", "hafif", "м'який", "blând", "خفيف")],
    ["weniger süß", "Wendung", null, null, "Ich möchte etwas, das weniger süß ist.", T("manje slatko", "daha az tatlı", "менш солодкий", "mai puțin dulce", "أقل حلاوة")],
    ["kleiner", "Adjektiv", null, null, "Haben Sie das Brot auch kleiner?", T("manji", "daha küçük", "менший", "mai mic", "أصغر")],
    ["größer", "Adjektiv", null, null, "Das größere Brot ist für Gäste.", T("veći", "daha büyük", "більший", "mai mare", "أكبر")],
    ["geschnitten", "Adjektiv", null, null, "Möchten Sie das Brot geschnitten?", T("narezano", "dilimlenmiş", "нарізаний", "feliat", "مقطّع")],
    ["ganz", "Adjektiv", null, null, "Oder lieber ganz, ohne Schneiden?", T("cijelo", "bütün", "цілий", "întreg", "كامل")],
    ["einfrieren", "Verb", null, null, "Ich friere die Hälfte ein.", T("zamrznuti", "dondurmak", "заморожувати", "a congela", "يجمّد")],
    ["die Schneidemaschine", "Nomen", "die", "die Schneidemaschinen", "Die Verkäuferin legt das Brot in die Schneidemaschine.", T("mašina za rezanje", "dilimleme makinesi", "хліборізка", "mașina de feliat", "آلة التقطيع")],
    ["der Gesamtpreis", "Nomen", "der", "die Gesamtpreise", "Wie hoch ist der Gesamtpreis?", T("ukupna cijena", "toplam fiyat", "загальна ціна", "preț total", "السعر الإجمالي")],
    ["das Bargeld", "Nomen", "das", "—", "Ich habe heute wenig Bargeld dabei.", T("gotovina", "nakit", "готівка", "numerar", "نقد")],
    ["das Kleingeld", "Nomen", "das", "—", "Ich suche noch Kleingeld in der Tasche.", T("sitniš", "bozuk para", "дрібні гроші", "mărunțiș", "فكة")],
    ["die Geldbörse", "Nomen", "die", "die Geldbörsen", "Meine Geldbörse ist in der Jackentasche.", T("novčanik", "cüzdan", "гаманець", "portofel", "محفظة")],
    ["die Brieftasche (AT)", "Nomen", "die", "die Brieftaschen", "In Österreich sagt man oft Brieftasche.", T("novčanik (AT)", "cüzdan (AT)", "гаманець (AT)", "portofel (AT)", "محفظة (النمسا)")],
    ["das Kartenlesegerät", "Nomen", "das", "die Kartenlesegeräte", "Das Kartenlesegerät steht auf der Theke.", T("čitač kartica", "kart okuyucu", "термінал", "cititor de card", "جهاز البطاقة")],
    ["der Kassenbon", "Nomen", "der", "die Kassenbons", "Möchten Sie den Kassenbon?", T("račun", "fiş", "чек", "bon fiscal", "إيصال")],
    ["die Tüte", "Nomen", "die", "die Tüten", "Eine kleine Tüte, bitte.", T("vrećica", "poşet", "пакет", "pungă", "كيس")],
    ["empfehlen", "Verb", null, null, "Was können Sie empfehlen?", T("preporučiti", "önermek", "рекомендувати", "a recomanda", "يوصي")],
    ["vergleichen", "Verb", null, null, "Ich vergleiche die zwei Brotsorten.", T("uporediti", "karşılaştırmak", "порівнювати", "a compara", "يقارن")],
    ["bezahlen", "Verb", null, null, "Ich bezahle heute mit Karte.", T("platiti", "ödemek", "платити", "a plăti", "يدفع")],
    ["dabeihaben", "Verb", null, null, "Ich habe nicht genug Bargeld dabei.", T("imati sa sobom", "yanında olmak", "мати при собі", "a avea la tine", "يحمل معه")],
    ["probieren", "Verb", null, null, "Ich habe den Kuchen schon probiert.", T("probati", "tatmak", "куштувати", "a gusta", "يتذوق")],
    ["gegenüber", "Präposition", null, null, "Die Bäckerei ist gegenüber meiner Wohnung.", T("preko puta", "karşısında", "навпроти", "vizavi", "مقابل")],
  ] as [string, string, string | null, string | null, string, Record<string, string>][]).map((v, i) => ({ id: `a2-v${i + 1}`, position: i + 1, term: v[0], word_class: v[1], article: v[2], plural: v[3], example: v[4], example_translations: v[5], translations: v[5], collocations: [] })),

  dialog: ([
    [1, "Kuchen und Brot auswählen", "V", "Verkäuferin", "Guten Morgen! Was darf es sein?", T("Dobro jutro! Šta želite?", "Günaydın! Ne arzu edersiniz?", "Доброго ранку! Що бажаєте?", "Bună dimineața! Ce doriți?", "صباح الخير! ماذا تحبين؟")],
    [1, "Kuchen und Brot auswählen", "K", "Kundin", "Guten Morgen. Ich hätte gern etwas Süßes, aber nichts, was zu süß ist.", T("Dobro jutro. Htjela bih nešto slatko, ali ne previše slatko.", "Günaydın. Tatlı bir şey isterim ama çok tatlı olmasın.", "Доброго ранку. Хочу щось солодке, але не надто солодке.", "Bună dimineața. Aș vrea ceva dulce, dar nu prea dulce.", "صباح الخير. أريد شيئًا حلوًا لكن ليس شديد الحلاوة.")],
    [1, "Kuchen und Brot auswählen", "V", "Verkäuferin", "Dann schauen Sie mal hier. Wir haben Apfelkuchen und Schokotorte.", T("Pogledajte ovdje. Imamo kolač od jabuka i čokoladnu tortu.", "Şuraya bakın. Elmalı pasta ve çikolatalı torta var.", "Погляньте сюди. Є яблучний пиріг і шоколадний торт.", "Uitați-vă aici. Avem prăjitură cu mere și tort de ciocolată.", "انظري هنا. لدينا كعكة تفاح وتورتة شوكولاتة.")],
    [1, "Kuchen und Brot auswählen", "K", "Kundin", "Was ist denn der Unterschied?", T("Koja je razlika?", "Aralarındaki fark ne?", "А в чому різниця?", "Care este diferența?", "ما الفرق بينهما؟")],
    [1, "Kuchen und Brot auswählen", "V", "Verkäuferin", "Die Torte ist deutlich süßer. Der Apfelkuchen ist milder und heute frisch gebacken.", T("Torta je znatno slađa. Kolač od jabuka je blaži i danas svježe pečen.", "Torta çok daha tatlı. Elmalı pasta daha hafif ve bugün taze pişti.", "Торт значно солодший. Яблучний пиріг м'якший і сьогодні свіжий.", "Tortul e mult mai dulce. Prăjitura cu mere e mai blândă și e coaptă azi.", "التورتة أحلى بكثير. كعكة التفاح أخف وطازجة اليوم.")],
    [1, "Kuchen und Brot auswählen", "K", "Kundin", "Und welchen würden Sie mir empfehlen?", T("A šta biste mi preporučili?", "Peki hangisini önerirsiniz?", "А що б ви порадили?", "Și pe care mi-ați recomanda?", "وأيهما توصين به؟")],
    [1, "Kuchen und Brot auswählen", "V", "Verkäuferin", "Ich würde den Apfelkuchen nehmen. Der passt gut zum Kaffee.", T("Uzela bih kolač od jabuka. Dobro ide uz kafu.", "Ben elmalı pastayı alırdım. Kahveyle iyi gider.", "Я б узяла яблучний пиріг. Він добре пасує до кави.", "Aș lua prăjitura cu mere. Merge bine cu cafeaua.", "كنت سآخذ كعكة التفاح. تناسب القهوة.")],
    [1, "Kuchen und Brot auswählen", "K", "Kundin", "Gut, dann nehme ich ein Stück Apfelkuchen.", T("Dobro, uzimam komad kolača od jabuka.", "Tamam, bir dilim elmalı pasta alayım.", "Добре, візьму шматок яблучного пирога.", "Bine, iau o felie de prăjitură cu mere.", "حسنًا، سآخذ قطعة من كعكة التفاح.")],
    [1, "Kuchen und Brot auswählen", "V", "Verkäuferin", "Sehr gern. Sonst noch etwas?", T("Vrlo rado. Još nešto?", "Memnuniyetle. Başka bir şey?", "Із задоволенням. Ще щось?", "Cu plăcere. Altceva?", "بكل سرور. شيء آخر؟")],
    [1, "Kuchen und Brot auswählen", "K", "Kundin", "Ja, ich brauche noch ein Brot fürs Abendessen. Welche Brotsorten haben Sie?", T("Da, treba mi hljeb za večeru. Koje vrste imate?", "Evet, akşam için ekmek lazım. Hangi çeşitler var?", "Так, треба хліб на вечерю. Які види у вас є?", "Da, îmi trebuie o pâine pentru cină. Ce sortimente aveți?", "نعم، أحتاج خبزًا للعشاء. ما الأنواع المتوفرة؟")],
    [1, "Kuchen und Brot auswählen", "V", "Verkäuferin", "Heute haben wir Roggenbrot und Mischbrot.", T("Danas imamo raženi i miješani hljeb.", "Bugün çavdar ve karışık ekmek var.", "Сьогодні є житній і змішаний хліб.", "Azi avem pâine de secară și pâine mixtă.", "اليوم لدينا خبز جاودار وخبز مخلوط.")],
    [1, "Kuchen und Brot auswählen", "K", "Kundin", "Welches ist kräftiger?", T("Koji je jačeg okusa?", "Hangisi daha yoğun?", "Який насиченіший?", "Care e mai intensă?", "أيهما أقوى نكهة؟")],
    [1, "Kuchen und Brot auswählen", "V", "Verkäuferin", "Das Roggenbrot ist kräftiger als das Mischbrot. Das Mischbrot schmeckt milder.", T("Raženi je jači od miješanog. Miješani je blaži.", "Çavdar, karışıktan daha yoğun. Karışık daha hafif.", "Житній насиченіший за змішаний. Змішаний м'якший.", "Pâinea de secară e mai intensă decât cea mixtă. Cea mixtă e mai blândă.", "الجاودار أقوى من المخلوط، والمخلوط أخف.")],
    [1, "Kuchen und Brot auswählen", "K", "Kundin", "Dann lieber das Mischbrot. Haben Sie das auch kleiner? Wir sind nur zu zweit.", T("Onda radije miješani. Imate li manji? Samo nas dvoje.", "O zaman karışık olsun. Daha küçüğü var mı? Sadece ikimiz varız.", "Тоді краще змішаний. Є менший? Нас лише двоє.", "Atunci mai bine cea mixtă. Aveți și mai mică? Suntem doar doi.", "إذن المخلوط. هل يوجد أصغر؟ نحن اثنان فقط.")],
    [1, "Kuchen und Brot auswählen", "V", "Verkäuferin", "Ja, hier ist ein kleines. Möchten Sie es geschnitten oder ganz?", T("Da, evo malog. Želite li narezano ili cijelo?", "Evet, küçüğü burada. Dilimli mi bütün mü?", "Так, ось маленький. Нарізати чи цілий?", "Da, aici e una mică. O doriți feliată sau întreagă?", "نعم، هذا صغير. مقطّع أم كامل؟")],
    [1, "Kuchen und Brot auswählen", "K", "Kundin", "Geschnitten, bitte. Ich friere nämlich die Hälfte ein, deshalb ist das praktischer.", T("Narezano, molim. Pola ću zamrznuti, zato je praktičnije.", "Dilimli lütfen. Yarısını dondururum, bu yüzden daha pratik.", "Нарізаний, будь ласка. Половину заморожу, тому так зручніше.", "Feliată, vă rog. Congelez jumătate, de aceea e mai practic.", "مقطّع من فضلك. سأجمّد النصف، لذلك هذا أسهل.")],
    [1, "Kuchen und Brot auswählen", "V", "Verkäuferin", "Mache ich sofort. Einen Moment, ich lege es in die Schneidemaschine.", T("Odmah. Trenutak, stavljam ga u mašinu za rezanje.", "Hemen yapıyorum. Bir saniye, makineye koyuyorum.", "Зараз зроблю. Хвилинку, кладу в хліборізку.", "Imediat. O clipă, o pun în mașina de feliat.", "حالًا. لحظة، سأضعه في آلة التقطيع.")],
    [1, "Kuchen und Brot auswählen", "K", "Kundin", "Danke, das ist super.", T("Hvala, odlično.", "Teşekkürler, harika.", "Дякую, чудово.", "Mulțumesc, perfect.", "شكرًا، ممتاز.")],
    [2, "An der Kasse", "V", "Verkäuferin", "So, das wäre alles. Zusammen macht das 7,40 Euro.", T("Eto, to bi bilo sve. Ukupno 7,40 eura.", "Tamamdır. Toplam 7,40 euro.", "Ось і все. Разом 7,40 євро.", "Gata, asta e tot. În total 7,40 euro.", "هذا كل شيء. المجموع 7,40 يورو.")],
    [2, "An der Kasse", "K", "Kundin", "Einen Moment, ich schaue kurz in meine Geldbörse.", T("Trenutak, pogledat ću u novčanik.", "Bir saniye, cüzdanıma bakayım.", "Хвилинку, гляну в гаманець.", "O clipă, mă uit în portofel.", "لحظة، سأنظر في محفظتي.")],
    [2, "An der Kasse", "K", "Kundin", "Oh, ich habe nur fünf Euro Bargeld dabei. Das reicht leider nicht.", T("Oh, imam samo pet eura gotovine. Nažalost, nije dovoljno.", "Sadece beş euro nakdim var. Maalesef yetmiyor.", "Ой, у мене лише п'ять євро готівкою. На жаль, замало.", "Am doar cinci euro numerar. Din păcate nu ajunge.", "معي خمسة يورو نقدًا فقط. للأسف لا تكفي.")],
    [2, "An der Kasse", "V", "Verkäuferin", "Kein Problem. Sie können auch mit Karte zahlen.", T("Nema problema. Možete platiti i karticom.", "Sorun değil. Kartla da ödeyebilirsiniz.", "Немає проблем. Можете заплатити карткою.", "Nicio problemă. Puteți plăti și cu cardul.", "لا مشكلة. يمكنك الدفع بالبطاقة.")],
    [2, "An der Kasse", "K", "Kundin", "Super, dann zahle ich mit der Karte.", T("Super, onda plaćam karticom.", "Harika, o zaman kartla ödüyorum.", "Чудово, тоді плачу карткою.", "Super, atunci plătesc cu cardul.", "رائع، سأدفع بالبطاقة.")],
    [2, "An der Kasse", "V", "Verkäuferin", "Gern. Das Gerät steht hier auf der Theke. Bitte kurz auflegen.", T("Rado. Uređaj je ovdje na pultu. Molim, prislonite karticu.", "Tabii. Cihaz tezgâhın üstünde. Kartı okutun lütfen.", "Будь ласка. Термінал на прилавку. Прикладіть картку.", "Cu plăcere. Aparatul e pe tejghea. Apropiați cardul.", "تفضلي. الجهاز على المنضدة. قرّبي البطاقة.")],
    [2, "An der Kasse", "K", "Kundin", "Hat es geklappt?", T("Je li prošlo?", "Oldu mu?", "Пройшло?", "A mers?", "هل نجح الدفع؟")],
    [2, "An der Kasse", "V", "Verkäuferin", "Ja, alles in Ordnung. Möchten Sie den Kassenbon?", T("Da, sve je u redu. Želite li račun?", "Evet, tamam. Fişi ister misiniz?", "Так, усе гаразд. Бажаєте чек?", "Da, totul e în regulă. Doriți bonul?", "نعم، تم بنجاح. هل تريدين الإيصال؟")],
    [2, "An der Kasse", "K", "Kundin", "Ja, bitte. Und könnten Sie mir noch eine kleine Tüte geben?", T("Da, molim. I možete li mi dati malu vrećicu?", "Evet lütfen. Bir de küçük poşet verir misiniz?", "Так, будь ласка. І можете дати маленький пакет?", "Da, vă rog. Și îmi dați o pungă mică?", "نعم من فضلك. وهل تعطينني كيسًا صغيرًا؟")],
    [2, "An der Kasse", "V", "Verkäuferin", "Natürlich. Hier sind die Tüte und der Bon.", T("Naravno. Evo vrećice i računa.", "Tabii. İşte poşet ve fiş.", "Звичайно. Ось пакет і чек.", "Sigur. Iată punga și bonul.", "بالطبع. هذا الكيس والإيصال.")],
    [2, "An der Kasse", "K", "Kundin", "Danke schön. Ist das Brot wirklich schon geschnitten?", T("Hvala lijepo. Je li hljeb stvarno već narezan?", "Teşekkürler. Ekmek gerçekten dilimlendi mi?", "Дуже дякую. Хліб справді вже нарізаний?", "Mulțumesc frumos. Pâinea chiar e deja feliată?", "شكرًا جزيلًا. هل الخبز مقطّع فعلًا؟")],
    [2, "An der Kasse", "V", "Verkäuferin", "Ja, unten in der Tüte. Schönen Tag noch!", T("Da, dolje u vrećici. Ugodan dan!", "Evet, poşetin altında. İyi günler!", "Так, унизу в пакеті. Гарного дня!", "Da, jos în pungă. O zi bună!", "نعم، في أسفل الكيس. نهارك سعيد!")],
    [2, "An der Kasse", "K", "Kundin", "Danke, Ihnen auch. Bis bald!", T("Hvala, i vama. Vidimo se!", "Teşekkürler, size de. Görüşürüz!", "Дякую, вам також. До зустрічі!", "Mulțumesc, și dumneavoastră. Pe curând!", "شكرًا، ولك أيضًا. إلى اللقاء!")],
  ] as [number, string, string, string, string, Record<string, string>][]).map((d, i) => ({ id: `a2-d${i + 1}`, position: i + 1, dialog_index: d[0], dialog_title: d[1], speaker: d[2], speaker_role: d[3], german_text: d[4], translations: d[5] })),

  questions: [
    /* ---------- Wo ist was? (12) ---------- */
    gap("a2-p1", "places", "Die Bäckerei ist ___ Maras Wohnung.", "gegenüber = auf der anderen Straßenseite.", "gegenüber", ["gegenüber", "unter", "zwischen", "hinter"], HELP.praep),
    gap("a2-p2", "places", "Die Verkäuferin steht ___ der Theke.", "Sie arbeitet auf der anderen Seite der Theke.", "hinter", ["hinter", "auf", "über", "zwischen"], HELP.praep),
    gap("a2-p3", "places", "Das Kartenlesegerät steht ___ der Theke.", "Es liegt oben auf der Fläche.", "auf", ["auf", "in", "unter", "vor"], HELP.praep),
    gap("a2-p4", "places", "Die Kuchen liegen ___ der Auslage.", "Sie sind innen in der Vitrine.", "in", ["in", "an", "über", "neben"], HELP.praep),
    gap("a2-p5", "places", "Mara steht ___ der Theke und wartet.", "Kundinnen stehen davor.", "vor", ["vor", "hinter", "unter", "in"], HELP.praep),
    gap("a2-p6", "places", "Der Apfelkuchen steht ___ der Torte und dem Brot.", "Zwischen = in der Mitte von zwei Dingen.", "zwischen", ["zwischen", "neben", "über", "an"], HELP.praep),
    sc("a2-p7", "places", "Zwei Kuchen stehen direkt nebeneinander. Was passt?", "neben = direkt daneben.", "Der Apfelkuchen steht neben der Torte.", ["Der Apfelkuchen steht unter der Torte.", "Der Apfelkuchen steht hinter der Straße.", "Der Apfelkuchen steht zwischen der Torte."], HELP.praep),
    sc("a2-p8", "places", "Mara wohnt auf der anderen Straßenseite. Wie geht sie zur Bäckerei?", "über die Straße gehen = auf die andere Seite gehen.", "Sie geht über die Straße.", ["Sie geht unter die Straße.", "Sie geht an der Straße.", "Sie geht zwischen die Straße."], HELP.praep),
    sc("a2-p9", "places", "Die Geldbörse liegt in der Tasche. Wo sucht Mara?", "in = innen.", "Sie sucht in ihrer Tasche.", ["Sie sucht über ihrer Tasche.", "Sie sucht gegenüber ihrer Tasche.", "Sie sucht zwischen ihrer Tasche."], HELP.praep),
    ic("a2-p10", "places", "Schau dir das Bild an: Wo steht die Verkäuferin?", "Sie steht hinter der Theke.", "baeck-ill-01", "Sie steht hinter der Theke.", ["Sie steht vor der Theke.", "Sie steht auf der Theke.", "Sie steht unter der Theke."], HELP.praep),
    ic("a2-p11", "places", "Schau dir das Bild an: Wo liegen die Backwaren?", "Sie liegen in der Auslage.", "baeck-ill-02", "Sie liegen in der Auslage.", ["Sie liegen unter der Auslage.", "Sie liegen neben der Straße.", "Sie liegen hinter der Kasse."], HELP.praep),
    mt("a2-p12", "places", "Ordne die Präposition der passenden Situation zu.", "Jede Präposition beschreibt eine andere Position.", [
      { left: "gegenüber", right: "Die Bäckerei liegt auf der anderen Straßenseite." },
      { left: "hinter", right: "Die Verkäuferin arbeitet auf der anderen Seite der Theke." },
      { left: "auf", right: "Das Kartenlesegerät liegt oben auf der Theke." },
      { left: "in", right: "Die Kuchen sind innen in der Auslage." },
    ], HELP.praep),

    /* ---------- Artikel & Fälle (15) ---------- */
    gap("a2-a1", "grammar", "___ Kuchen ist heute frisch gebacken.", "Kuchen ist männlich: der Kuchen.", "Der", ["Der", "Die", "Das"], HELP.nom),
    gap("a2-a2", "grammar", "___ Tüte ist ziemlich klein.", "Tüte ist weiblich: die Tüte.", "Die", ["Die", "Der", "Das"], HELP.nom),
    gap("a2-a3", "grammar", "___ Brot kostet 3,20 Euro.", "Brot ist sächlich: das Brot.", "Das", ["Das", "Der", "Die"], HELP.nom),
    gap("a2-a4", "grammar", "Ich nehme ___ Kuchen.", "Akkusativ männlich: der → den.", "den", ["den", "der", "dem", "das"], HELP.akk),
    gap("a2-a5", "grammar", "Ich kaufe ___ Brot.", "das bleibt im Akkusativ gleich.", "das", ["das", "dem", "den", "der"], HELP.akk),
    gap("a2-a6", "grammar", "Ich brauche ___ Tüte.", "die bleibt im Akkusativ gleich.", "die", ["die", "der", "den", "dem"], HELP.akk),
    gap("a2-a7", "grammar", "Ich bezahle mit ___ Karte.", "mit + Dativ, die → der.", "der", ["der", "die", "dem", "den"], HELP.dat),
    gap("a2-a8", "grammar", "Wir sind gerade in ___ Bäckerei.", "in + Dativ, die → der.", "der", ["der", "die", "dem", "den"], HELP.dat),
    gap("a2-a9", "grammar", "Das Gerät steht auf ___ Theke.", "auf + Dativ, die → der.", "der", ["der", "die", "dem", "das"], HELP.dat),
    gap("a2-a10", "grammar", "Ich hätte gern ___ Brezel.", "Brezel ist weiblich: eine Brezel.", "eine", ["eine", "ein", "einen", "einem"], HELP.unbest),
    gap("a2-a11", "grammar", "Ich möchte ___ Kaffee dazu.", "Kaffee ist männlich, Akkusativ: einen.", "einen", ["einen", "ein", "eine", "einem"], HELP.unbest),
    gap("a2-a12", "grammar", "Wir kaufen ___ Mischbrot.", "Mischbrot ist sächlich: ein Mischbrot.", "ein", ["ein", "eine", "einen", "einem"], HELP.unbest),
    sc("a2-a13", "grammar", "Welcher Satz ist im Akkusativ richtig?", "nehmen + Akkusativ: den Apfelkuchen.", "Ich nehme den Apfelkuchen.", ["Ich nehme dem Apfelkuchen.", "Ich nehme der Apfelkuchen.", "Ich nehme des Apfelkuchen."], HELP.akk),
    sc("a2-a14", "grammar", "Welcher Satz ist richtig?", "mit + Dativ: mit dem Kleingeld.", "Ich zahle den Rest mit dem Kleingeld.", ["Ich zahle den Rest mit das Kleingeld.", "Ich zahle den Rest mit den Kleingeld.", "Ich zahle den Rest mit der Kleingeld."], HELP.dat),
    mt("a2-a15", "grammar", "Ordne jedem Wort den richtigen Artikel zu.", "Artikel immer mitlernen.", [
      { left: "Kassenbon", right: "der" },
      { left: "Auslage", right: "die" },
      { left: "Kartenlesegerät", right: "das" },
      { left: "Scheibe", right: "die (Plural: Scheiben)" },
    ], HELP.nom),

    /* ---------- Sprache & Grammatik (15) ---------- */
    gap("a2-g1", "grammar", "Ich nehme das kleinere Brot, ___ wir nur zu zweit sind.", "weil nennt den Grund.", "weil", ["weil", "deshalb", "trotzdem", "damit"], HELP.weil),
    gap("a2-g2", "grammar", "Ich habe wenig Bargeld dabei, ___ zahle ich mit Karte.", "deshalb nennt die Folge.", "deshalb", ["deshalb", "weil", "obwohl", "damit"], HELP.deshalb),
    sc("a2-g3", "grammar", "Welcher Satz mit weil ist richtig gebaut?", "Nach weil steht das Verb am Ende.", "Ich friere die Hälfte ein, weil wir nicht so viel essen.", ["Ich friere die Hälfte ein, weil wir essen nicht so viel.", "Ich friere die Hälfte ein, weil essen wir nicht so viel.", "Weil wir nicht so viel essen ich friere die Hälfte ein."], HELP.weil),
    gap("a2-g4", "grammar", "Das Roggenbrot ist ___ als das Mischbrot.", "Komparativ von kräftig.", "kräftiger", ["kräftiger", "kräftig", "am kräftigsten", "kräftigere"], HELP.komp),
    gap("a2-g5", "grammar", "Dieses Brot ist mir zu groß. Haben Sie es auch ___?", "Komparativ von klein.", "kleiner", ["kleiner", "klein", "kleinste", "kleinere"], HELP.komp),
    gap("a2-g6", "grammar", "Die Torte ist süßer ___ der Apfelkuchen.", "Vergleich mit als.", "als", ["als", "wie", "so", "wie als"], HELP.komp),
    gap("a2-g7", "grammar", "___ Kuchen ist heute frisch?", "Kuchen ist männlich: welcher.", "Welcher", ["Welcher", "Welche", "Welches", "Welchem"], HELP.welch),
    gap("a2-g8", "grammar", "___ Brotsorte empfehlen Sie mir?", "Brotsorte ist weiblich: welche.", "Welche", ["Welche", "Welcher", "Welches", "Welchen"], HELP.welch),
    gap("a2-g9", "grammar", "___ Brot ist kleiner?", "Brot ist sächlich: welches.", "Welches", ["Welches", "Welcher", "Welche", "Welchem"], HELP.welch),
    sc("a2-g10", "grammar", "Sie möchten etwas Süßes, aber nicht zu süß. Was sagen Sie?", "etwas + großgeschriebenes Adjektiv.", "Ich hätte gern etwas Süßes, aber nichts Schweres.", ["Ich hätte gern etwas süß, aber nichts schwer.", "Ich hätte gern etwas Süß, aber nichts Schwer.", "Ich hätte gern nichts Süßes, aber etwas Schweres."], HELP.etwas),
    gap("a2-g11", "grammar", "Ich habe leider ___ Bargeld dabei.", "nicht genug = zu wenig.", "nicht genug", ["nicht genug", "genug nicht", "kein genug", "genug kein"], HELP.genug),
    sc("a2-g12", "grammar", "Wie sagt man höflich, dass man ein Mischbrot möchte?", "Ich hätte gern … ist höflich.", "Ich hätte gern ein Mischbrot, bitte.", ["Ich will ein Mischbrot.", "Geben Mischbrot!", "Ich habe gern ein Mischbrot gewollt."], HELP.hoefl),
    sc("a2-g13", "grammar", "Welcher Satz mit können ist richtig?", "Modalverb + Infinitiv am Ende.", "Kann ich hier mit Karte bezahlen?", ["Kann ich hier mit Karte bezahle?", "Kann ich bezahlen hier mit Karte?", "Ich kann mit Karte bezahlt hier?"], HELP.koennen),
    gap("a2-g14", "grammar", "Ich esse morgens ___ Brot als Kuchen.", "lieber zeigt die Vorliebe.", "lieber", ["lieber", "gern", "am liebsten", "besser gern"], HELP.lieber),
    sc("a2-g15", "grammar", "Welcher Satz steht korrekt im Perfekt?", "haben + Partizip II am Ende.", "Ich habe den Apfelkuchen schon probiert.", ["Ich habe den Apfelkuchen schon probieren.", "Ich bin den Apfelkuchen schon probiert.", "Ich habe schon probiert den Apfelkuchen."], HELP.perfekt),

    /* ---------- Übungen (30) ---------- */
    sc("a2-u1", "uebungen", "Mara möchte etwas Süßes, aber nicht zu süß. Was sagt sie an der Theke?", "Wunsch genauer beschreiben.", "Ich hätte gern etwas Süßes, aber nichts, was zu süß ist.", ["Ich möchte alle Kuchen probieren.", "Süß bitte nicht süß.", "Ich hätte gern etwas Salziges."]),
    sc("a2-u2", "uebungen", "Die Verkäuferin sagt: „Das Roggenbrot ist kräftiger.“ Was bedeutet das?", "kräftig = intensiver Geschmack.", "Es schmeckt intensiver als das andere Brot.", ["Es ist schwerer zu tragen.", "Es ist heute günstiger.", "Es ist größer geschnitten."]),
    sc("a2-u3", "uebungen", "Warum möchte Mara das Brot geschnitten?", "Sie friert die Hälfte ein.", "Weil sie die Hälfte einfrieren möchte.", ["Weil sie kein Messer kaufen will.", "Weil das Brot dann billiger ist.", "Weil die Bäckerei gleich schließt."]),
    sc("a2-u4", "uebungen", "Wie fragt man höflich nach einer Empfehlung?", "Frage mit können.", "Was können Sie mir empfehlen?", ["Empfehlen Sie mir sofort etwas.", "Ich brauche eine Empfehlung von Ihnen jetzt.", "Sie empfehlen was?"]),
    sc("a2-u5", "uebungen", "Mara hat nur fünf Euro Bargeld, alles kostet 7,40 Euro. Was sagt sie?", "Problem beschreiben und Lösung suchen.", "Mein Bargeld reicht leider nicht. Kann ich mit Karte zahlen?", ["Ich habe kein Geld, ich gehe wieder.", "Ich zahle morgen den Rest.", "Bitte machen Sie es billiger."]),
    sc("a2-u6", "uebungen", "Was ist ein Kassenbon?", "Der Beleg über den Einkauf.", "Ein Beleg, auf dem der Einkauf steht.", ["Eine kleine Tüte für Brot.", "Ein Gerät für Kartenzahlung.", "Eine Brotsorte mit Roggen."]),
    sc("a2-u7", "uebungen", "Welche Frage passt, wenn du den Unterschied wissen willst?", "Nach dem Unterschied fragen.", "Was ist der Unterschied zwischen den beiden?", ["Was kostet der Unterschied?", "Wo ist der Unterschied gegangen?", "Wie heißt der Unterschied bitte?"]),
    sc("a2-u8", "uebungen", "Die Verkäuferin fragt: „Geschnitten oder ganz?“ Was antwortest du, wenn du Scheiben willst?", "geschnitten = in Scheiben.", "Geschnitten, bitte.", ["Ganz, bitte.", "Beides zusammen, bitte.", "Ohne Brot, bitte."]),
    mc("a2-u9", "uebungen", "Welche Sätze passen zu einer Bestellung in der Bäckerei? (mehrere richtig)", "Höfliche Bestellsätze.", ["Ich hätte gern ein Stück Apfelkuchen.", "Könnten Sie das Brot bitte schneiden?", "Ein Mischbrot, bitte."], ["Wo ist hier der Bahnsteig?", "Ich möchte einen Termin beim Arzt."]),
    mc("a2-u10", "uebungen", "Welche Wörter beschreiben Geschmack oder Größe? (mehrere richtig)", "Adjektive im Laden.", ["kräftig", "mild", "kleiner"], ["der Kassenbon", "die Schneidemaschine"]),
    mc("a2-u11", "uebungen", "Womit kann Mara bezahlen? (mehrere richtig)", "Bargeld oder Karte.", ["mit Bargeld", "mit Karte"], ["mit dem Kassenbon", "mit der Tüte"]),
    mc("a2-u12", "uebungen", "Welche Sätze nennen einen Grund oder eine Folge? (mehrere richtig)", "weil = Grund, deshalb = Folge.", ["Ich nehme das kleine Brot, weil wir zu zweit sind.", "Ich habe wenig Bargeld, deshalb zahle ich mit Karte."], ["Ich hätte gern ein Stück Kuchen.", "Die Bäckerei öffnet um sechs Uhr."]),
    tf("a2-u13", "uebungen", "Die Bäckerei liegt gegenüber von Maras Wohnung.", "Sie geht nur über die Straße.", true),
    tf("a2-u14", "uebungen", "Mara nimmt das größere Brot, weil viele Gäste kommen.", "Sie nimmt das kleinere Brot, weil sie zu zweit sind.", false),
    tf("a2-u15", "uebungen", "Mara bezahlt am Ende mit Karte.", "Ihr Bargeld reicht nicht.", true),
    tf("a2-u16", "uebungen", "Der Apfelkuchen ist süßer als die Schokotorte.", "Die Torte ist süßer.", false),
    gap("a2-u17", "uebungen", "Ich hätte gern ein ___ Apfelkuchen.", "Menge: ein Stück.", "Stück", ["Stück", "Scheibe", "Tüte", "Hälfte"], HELP.menge),
    gap("a2-u18", "uebungen", "Zwei ___ Brot reichen mir zum Frühstück.", "Brot zählt man in Scheiben.", "Scheiben", ["Scheiben", "Stücke", "Tüten", "Bons"], HELP.menge),
    gap("a2-u19", "uebungen", "Können Sie mir das Brot bitte ___?", "schneiden = in Scheiben machen.", "schneiden", ["schneiden", "einfrieren", "empfehlen", "bezahlen"]),
    gap("a2-u20", "uebungen", "Die Verkäuferin legt das Brot in die ___.", "Gerät zum Schneiden.", "Schneidemaschine", ["Schneidemaschine", "Auslage", "Geldbörse", "Tüte"]),
    gap("a2-u21", "uebungen", "Ich suche noch ___ in meiner Geldbörse.", "Kleingeld = Münzen.", "Kleingeld", ["Kleingeld", "Kassenbon", "Auslage", "Empfehlung"]),
    so("a2-u22", "uebungen", "Bau die Frage: nach einer Empfehlung fragen.", "Was können Sie mir empfehlen?", ["Was", "können", "Sie", "mir", "empfehlen?"]),
    so("a2-u23", "uebungen", "Bau den Satz: höflich ein kleines Mischbrot bestellen.", "Ich hätte gern ein kleines Mischbrot.", ["Ich", "hätte", "gern", "ein", "kleines", "Mischbrot."]),
    so("a2-u24", "uebungen", "Bau den Satz mit weil.", "Ich nehme das kleinere Brot, weil wir zu zweit sind.", ["Ich", "nehme", "das", "kleinere", "Brot,", "weil", "wir", "zu", "zweit", "sind."], HELP.weil),
    mt("a2-u25", "uebungen", "Ordne Wort und Bedeutung zu.", "Wortschatz aus der Bäckerei.", [
      { left: "die Auslage", right: "die Vitrine mit den Backwaren" },
      { left: "der Kassenbon", right: "der Beleg nach dem Bezahlen" },
      { left: "einfrieren", right: "etwas ins Gefrierfach legen" },
      { left: "die Empfehlung", right: "ein guter Tipp der Verkäuferin" },
    ]),
    mt("a2-u26", "uebungen", "Ordne Frage und passende Antwort zu.", "Logische Reaktionen im Laden.", [
      { left: "Möchten Sie das Brot geschnitten?", right: "Ja, bitte. Ich friere die Hälfte ein." },
      { left: "Was darf es sein?", right: "Ich hätte gern ein Stück Apfelkuchen." },
      { left: "Möchten Sie den Kassenbon?", right: "Ja, gern." },
      { left: "Kann ich mit Karte zahlen?", right: "Natürlich, das Gerät steht hier." },
    ]),
    ordq("a2-u27", "uebungen", "Bringe den Einkauf in die richtige Reihenfolge.", "So läuft der Besuch ab.", ["Mara geht über die Straße.", "Sie schaut sich die Auslage an.", "Sie bestellt ein Stück Kuchen.", "Sie wählt ein kleines Mischbrot.", "Sie bezahlt mit Karte.", "Sie bekommt den Kassenbon."]),
    ordq("a2-u28", "uebungen", "Bringe die Schritte beim Bezahlen in die richtige Reihenfolge.", "Erst Preis, dann Zahlung, dann Bon.", ["Die Verkäuferin nennt den Gesamtpreis.", "Mara schaut in ihre Geldbörse.", "Sie sagt, dass ihr Bargeld nicht reicht.", "Sie zahlt mit der Karte.", "Sie nimmt den Kassenbon."]),
    sc("a2-u29", "uebungen", "Du willst wissen, ob ein Brot heute gebacken wurde. Was fragst du?", "frisch gebacken erfragen.", "Ist das Brot heute frisch gebacken?", ["Ist das Brot heute teuer gebacken?", "Backen Sie heute mein Brot mit?", "Wann habe ich das Brot gebacken?"]),
    sc("a2-u30", "uebungen", "Die Verkäuferin sagt: „Zusammen 7,40 Euro.“ Worüber spricht sie?", "Gesamtpreis.", "Über den Gesamtpreis des Einkaufs.", ["Über den Preis nur für den Kuchen.", "Über die Öffnungszeit.", "Über das Gewicht des Brotes."]),

    /* ---------- Dialog bauen (3) ---------- */
    dord("a2-db1", "dialog_builder", "Dialog bauen: Empfehlung und Kuchenauswahl.", "Begrüßung → Wunsch → Empfehlung → Vergleich → Entscheidung.", [
      "Verkäuferin: Guten Morgen! Was darf es sein?",
      "Kundin: Ich hätte gern etwas Süßes, aber nichts zu Süßes.",
      "Verkäuferin: Wir haben Apfelkuchen und Schokotorte.",
      "Kundin: Was ist der Unterschied?",
      "Verkäuferin: Die Torte ist süßer, der Apfelkuchen ist milder und frisch gebacken.",
      "Kundin: Dann nehme ich ein Stück Apfelkuchen.",
    ]),
    dord("a2-db2", "dialog_builder", "Dialog bauen: Brotauswahl und Schneiden.", "Frage → Vergleich → Vorliebe → Grund → Schneiden.", [
      "Kundin: Welche Brotsorten haben Sie heute?",
      "Verkäuferin: Roggenbrot und Mischbrot.",
      "Kundin: Welches ist kräftiger?",
      "Verkäuferin: Das Roggenbrot ist kräftiger als das Mischbrot.",
      "Kundin: Dann lieber das Mischbrot, aber kleiner, weil wir nur zu zweit sind.",
      "Verkäuferin: Möchten Sie es geschnitten oder ganz?",
      "Kundin: Geschnitten, bitte. Ich friere die Hälfte ein.",
    ]),
    dord("a2-db3", "dialog_builder", "Dialog bauen: Bezahlen und Kassenbon.", "Preis → Bargeld → Karte → Bon → Abschied.", [
      "Verkäuferin: Zusammen macht das 7,40 Euro.",
      "Kundin: Einen Moment, ich schaue in meine Geldbörse.",
      "Kundin: Mein Bargeld reicht leider nicht. Kann ich mit Karte zahlen?",
      "Verkäuferin: Natürlich, das Gerät steht hier auf der Theke.",
      "Verkäuferin: Möchten Sie den Kassenbon?",
      "Kundin: Ja, bitte. Und eine kleine Tüte?",
      "Verkäuferin: Gern. Schönen Tag noch!",
    ]),

    /* ---------- Abschlusstest: 50 Fragen ---------- */
    /* 18 Single Choice */
    sc("a2-t1", "test", "Mara wohnt gegenüber der Bäckerei. Was bedeutet das?", "gegenüber = andere Straßenseite.", "Die Bäckerei ist auf der anderen Straßenseite.", ["Die Bäckerei ist im selben Haus.", "Die Bäckerei ist weit außerhalb.", "Die Bäckerei ist hinter dem Bahnhof."], HELP.praep),
    sc("a2-t2", "test", "Welche Frage passt, wenn du eine Empfehlung willst?", "Empfehlung erfragen.", "Was würden Sie mir empfehlen?", ["Was empfehle ich Ihnen?", "Wollen Sie eine Empfehlung von mir?", "Empfehlung, bitte sofort."]),
    sc("a2-t3", "test", "Was bedeutet „weniger süß“?", "Vergleich mit etwas anderem.", "Nicht so süß wie das andere Produkt.", ["Ganz ohne Zucker.", "Süßer als alles andere.", "Salzig statt süß."], HELP.komp),
    sc("a2-t4", "test", "Welcher Satz ist im Akkusativ korrekt?", "der → den.", "Ich nehme den Kuchen und das Brot.", ["Ich nehme dem Kuchen und dem Brot.", "Ich nehme der Kuchen und die Brot.", "Ich nehme den Kuchen und dem Brot."], HELP.akk),
    sc("a2-t5", "test", "Welcher Satz ist im Dativ korrekt?", "mit + Dativ.", "Ich bezahle mit der Karte.", ["Ich bezahle mit die Karte.", "Ich bezahle mit den Karte.", "Ich bezahle mit das Karte."], HELP.dat),
    sc("a2-t6", "test", "Wie bestellt man höflich?", "Ich hätte gern …", "Ich hätte gern zwei Brötchen, bitte.", ["Ich will zwei Brötchen.", "Zwei Brötchen sofort!", "Ich habe zwei Brötchen gern gewollt."], HELP.hoefl),
    sc("a2-t7", "test", "Was macht die Verkäuferin mit der Schneidemaschine?", "Sie schneidet das Brot.", "Sie schneidet das Brot in Scheiben.", ["Sie friert das Brot ein.", "Sie wiegt den Kuchen.", "Sie druckt den Kassenbon."]),
    sc("a2-t8", "test", "Warum zahlt Mara mit Karte?", "Ihr Bargeld reicht nicht.", "Weil sie nicht genug Bargeld dabeihat.", ["Weil die Bäckerei kein Bargeld nimmt.", "Weil sie ihre Geldbörse verloren hat.", "Weil das Brot zu teuer war."], HELP.weil),
    sc("a2-t9", "test", "Was ist der Gesamtpreis?", "Alles zusammen.", "Der Preis für alle Waren zusammen.", ["Der Preis nur für das Brot.", "Der Preis ohne Kuchen.", "Der Preis für die Tüte."]),
    sc("a2-t10", "test", "Welche Antwort passt auf „Möchten Sie das Brot geschnitten oder ganz?“", "Logische Reaktion.", "Geschnitten, bitte.", ["Ja, gerne mit Karte.", "Nein, ich wohne gegenüber.", "Zwei Euro, bitte."]),
    sc("a2-t11", "test", "Welche Antwort passt auf „Kann ich Ihnen helfen?“", "Logische Reaktion.", "Ja, gern. Ich suche ein Brot fürs Abendessen.", ["Nein, das Brot ist zu süß.", "Ja, hier ist der Kassenbon.", "Danke, ich bin die Verkäuferin."]),
    sc("a2-t12", "test", "Welches Wort passt: „Das Mischbrot schmeckt ___ als das Roggenbrot.“", "mild → milder.", "milder", ["mild", "am mildesten", "mildere"], HELP.komp),
    sc("a2-t13", "test", "Was bedeutet „einfrieren“?", "Ins Gefrierfach legen.", "Etwas ins Gefrierfach legen, damit es haltbar bleibt.", ["Etwas im Ofen backen.", "Etwas in Scheiben schneiden.", "Etwas kalt trinken."]),
    sc("a2-t14", "test", "Was steht in der Auslage?", "Die Backwaren.", "Brot, Brötchen und Kuchen.", ["Das Kartenlesegerät.", "Die Geldbörse der Kundin.", "Die Kassenbons."]),
    sc("a2-t15", "test", "Welcher Satz nennt eine Folge?", "deshalb = Folge.", "Ich habe wenig Bargeld, deshalb zahle ich mit Karte.", ["Ich zahle mit Karte, weil ich wenig Bargeld habe.", "Ich habe wenig Bargeld und viel Zeit.", "Ich zahle mit Karte oder mit Bargeld."], HELP.deshalb),
    sc("a2-t16", "test", "Welcher Satz steht korrekt im Perfekt?", "haben + Partizip II.", "Wir haben das Brot gestern gekauft.", ["Wir sind das Brot gestern gekauft.", "Wir haben gestern das Brot kaufen.", "Wir haben gekauft gestern das Brot."], HELP.perfekt),
    sc("a2-t17", "test", "Mara sagt: „Wir sind nur zu zweit.“ Warum sagt sie das?", "Grund für das kleinere Brot.", "Sie erklärt, warum sie das kleinere Brot nimmt.", ["Sie fragt nach dem Preis.", "Sie möchte zwei Tüten.", "Sie will zwei Stück Kuchen."]),
    sc("a2-t18", "test", "Was sagt man am Ende des Einkaufs?", "Freundliche Verabschiedung.", "Danke, schönen Tag noch!", ["Guten Morgen, was darf es sein?", "Ich hätte gern ein Brot.", "Kann ich mit Karte zahlen?"]),

    /* 6 Multiple Choice */
    mc("a2-t19", "test", "Welche Wörter sind Backwaren? (mehrere richtig)", "Produkte aus der Bäckerei.", ["das Roggenbrot", "der Apfelkuchen", "die Brezel"], ["das Kartenlesegerät", "die Geldbörse"]),
    mc("a2-t20", "test", "Welche Sätze sind höflich? (mehrere richtig)", "Höfliche Formen.", ["Könnten Sie das bitte schneiden?", "Ich hätte gern ein kleines Brot."], ["Schneiden Sie das jetzt!", "Ich will sofort ein Brot."], HELP.hoefl),
    mc("a2-t21", "test", "Welche Sätze stehen korrekt im Dativ? (mehrere richtig)", "mit/in/auf + Dativ.", ["Ich zahle mit der Karte.", "Wir stehen in der Bäckerei."], ["Das Gerät steht auf die Theke.", "Ich zahle mit den Karte."], HELP.dat),
    mc("a2-t22", "test", "Welche Aussagen zur Story sind richtig? (mehrere richtig)", "Inhalt der 25 Szenen.", ["Mara geht über die Straße zur Bäckerei.", "Sie lässt das Brot schneiden.", "Sie bekommt am Ende einen Kassenbon."], ["Sie kauft nur Kaffee.", "Sie bezahlt mit Bargeld."]),
    mc("a2-t23", "test", "Welche Wörter beschreiben Geld? (mehrere richtig)", "Wortfeld Bezahlen.", ["das Bargeld", "das Kleingeld", "die Geldbörse"], ["die Auslage", "die Scheibe"]),
    mc("a2-t24", "test", "Welche Fragen passen zum Vergleichen? (mehrere richtig)", "Vergleichsfragen.", ["Welches Brot ist kräftiger?", "Was ist der Unterschied zwischen den beiden?"], ["Wann schließen Sie heute?", "Wo ist die Toilette?"], HELP.komp),

    /* 7 Richtig/Falsch */
    tf("a2-t25", "test", "„Ich nehme den Kuchen“ steht im Akkusativ.", "nehmen + Akkusativ.", true, HELP.akk),
    tf("a2-t26", "test", "Nach „mit“ steht immer der Nominativ.", "Nach mit steht der Dativ.", false, HELP.dat),
    tf("a2-t27", "test", "Mit „weil“ nennt man einen Grund.", "Richtig.", true, HELP.weil),
    tf("a2-t28", "test", "„Welches“ passt zu weiblichen Nomen wie die Tüte.", "Zu die passt welche.", false, HELP.welch),
    tf("a2-t29", "test", "Ein Kassenbon zeigt, was man gekauft und bezahlt hat.", "Richtig.", true),
    tf("a2-t30", "test", "„Geschnitten“ bedeutet, dass das Brot in Scheiben ist.", "Richtig.", true),
    tf("a2-t31", "test", "Mara nimmt das Roggenbrot, weil es milder ist.", "Sie nimmt das Mischbrot, das Roggenbrot ist kräftiger.", false),

    /* 10 Lückenauswahl */
    gap("a2-t32", "test", "Ich hätte gern ___ Stück Apfelkuchen.", "Stück ist sächlich: ein Stück.", "ein", ["ein", "eine", "einen", "einem"], HELP.unbest),
    gap("a2-t33", "test", "Ich nehme ___ Mischbrot, bitte.", "das Mischbrot bleibt im Akkusativ gleich.", "das", ["das", "den", "der", "dem"], HELP.akk),
    gap("a2-t34", "test", "Könnten Sie mir bitte ___ Tüte geben?", "die Tüte, Akkusativ: eine.", "eine", ["eine", "ein", "einen", "einem"], HELP.unbest),
    gap("a2-t35", "test", "Das Kartenlesegerät steht auf ___ Theke.", "auf + Dativ, die → der.", "der", ["der", "die", "dem", "den"], HELP.dat),
    gap("a2-t36", "test", "Wir kaufen oft in ___ Bäckerei gegenüber.", "in + Dativ, die → der.", "der", ["der", "die", "dem", "das"], HELP.dat),
    gap("a2-t37", "test", "Das große Brot ist teurer ___ das kleine.", "Vergleich mit als.", "als", ["als", "wie", "so", "denn wie"], HELP.komp),
    gap("a2-t38", "test", "___ Kuchen möchten Sie: den Apfelkuchen oder die Torte?", "Kuchen ist männlich: welchen im Akkusativ.", "Welchen", ["Welchen", "Welche", "Welches", "Welcher"], HELP.welch),
    gap("a2-t39", "test", "Ich zahle mit Karte, ___ mein Bargeld nicht reicht.", "weil nennt den Grund.", "weil", ["weil", "deshalb", "trotzdem", "damit"], HELP.weil),
    gap("a2-t40", "test", "Wir sind nur zu zweit, ___ nehmen wir das kleinere Brot.", "deshalb nennt die Folge.", "deshalb", ["deshalb", "weil", "obwohl", "wenn"], HELP.deshalb),
    gap("a2-t41", "test", "Zwei ___ Brot bitte, mehr brauche ich nicht.", "Scheiben für Brot.", "Scheiben", ["Scheiben", "Stücke", "Tüten", "Hälften"], HELP.menge),

    /* 4 Satzbau / Reihenfolge */
    so("a2-t42", "test", "Bau den Satz: höflich nach Kartenzahlung fragen.", "Kann ich bitte mit Karte zahlen?", ["Kann", "ich", "bitte", "mit", "Karte", "zahlen?"], HELP.koennen),
    so("a2-t43", "test", "Bau den Satz mit deshalb.", "Ich friere die Hälfte ein, deshalb möchte ich es geschnitten.", ["Ich", "friere", "die", "Hälfte", "ein,", "deshalb", "möchte", "ich", "es", "geschnitten."], HELP.deshalb),
    ordq("a2-t44", "test", "Bringe die Story in die richtige Reihenfolge.", "Ablauf der 25 Szenen.", ["Mara schaut aus dem Fenster.", "Sie geht über die Straße.", "Sie sieht sich die Auslage an.", "Sie bestellt Kuchen und Brot.", "Sie zahlt mit Karte.", "Sie geht mit der Tüte nach Hause."]),
    dord("a2-t45", "test", "Bringe den Dialog in die richtige Reihenfolge.", "Logische Reaktionen.", [
      "Verkäuferin: Was darf es sein?",
      "Kundin: Ich hätte gern ein kleines Mischbrot.",
      "Verkäuferin: Geschnitten oder ganz?",
      "Kundin: Geschnitten, bitte.",
      "Verkäuferin: Sonst noch etwas?",
      "Kundin: Nein, danke. Das ist alles.",
    ]),

    /* 3 Zuordnungen */
    mt("a2-t46", "test", "Ordne Artikel und Nomen richtig zu.", "Artikel mitlernen.", [
      { left: "der", right: "Kassenbon" },
      { left: "die", right: "Auslage" },
      { left: "das", right: "Kartenlesegerät" },
    ], HELP.nom),
    mt("a2-t47", "test", "Ordne Präposition und Situation zu.", "Ort beschreiben.", [
      { left: "hinter", right: "Die Verkäuferin steht dort, hinter der Theke." },
      { left: "auf", right: "Das Kartenlesegerät liegt oben auf der Theke." },
      { left: "gegenüber", right: "Die Bäckerei ist auf der anderen Straßenseite." },
    ], HELP.praep),
    mt("a2-t48", "test", "Ordne Wort und Erklärung zu.", "Wortschatz.", [
      { left: "die Empfehlung", right: "ein Tipp, was gut ist" },
      { left: "der Gesamtpreis", right: "alles zusammen kostet …" },
      { left: "die Hälfte", right: "50 Prozent von etwas" },
    ], HELP.wortschatz),

    /* 2 Bild-/Situationsfragen */
    ic("a2-t49", "test", "Schau das Bild an: Was passiert hier gerade?", "Bezahlen mit Karte.", "baeck-ill-09", "Die Kundin bezahlt mit der Karte.", ["Die Kundin wählt einen Kuchen aus.", "Die Verkäuferin schneidet das Brot.", "Die Kundin geht nach Hause."]),
    ic("a2-t50", "test", "Schau das Bild an: Was macht Mara in dieser Situation?", "Sie sieht, dass ihr Bargeld nicht reicht.", "baeck-wallet", "Sie schaut in ihre Geldbörse und hat zu wenig Bargeld.", ["Sie gibt der Verkäuferin den Kassenbon.", "Sie packt das Brot in die Tüte.", "Sie bestellt noch einen Kaffee."]),
  ],
};

export const BAKERY_A2_SCENE_HINTS = SCENE_HINTS;
