export const bakeryA1Override = {
  lesson: {
    id: "22222222-2222-2222-2222-222222222222",
    slug: "in-der-baeckerei",
    title: "In der Bäckerei",
    description:
      "Eine echte Alltagssituation in der Bäckerei: begrüßen, Brot und Brötchen kaufen, nach Zutaten fragen, bezahlen und sich verabschieden.",
    level: "A1",
    region: "de",
    category_slug: "alltag",
    subcategory_slug: "baeckerei",
    topic_slug: "baeckerei",
    topic_title: "In der Bäckerei",
    duration_seconds: 900,
    thumbnail_key: "baeckerei",
    video_url: null,
    is_premium: false,
    status: "published",
    popularity: 80,
    grammar_topics: ["Höflich etwas kaufen", "Mengenangaben", "Lokale Präpositionen"],
    grammar_notes: [
      {
        title: "Natürlich in der Bäckerei sprechen",
        explanation:
          "Im echten Gespräch sagt man zum Beispiel: „Ich hätte gern …“, „Ich nehme …“ oder einfach „Zwei Brötchen, bitte.“",
        examples: [
          "Ich hätte gern ein Mischbrot, bitte.",
          "Ich nehme vier Brötchen, bitte.",
          "Zwei Brezeln, bitte.",
        ],
      },
      {
        title: "Wo ist was?",
        explanation: "Mit in, auf, neben, vor und hinter beschreiben wir Orte.",
        examples: [
          "Das Brot liegt im Regal.",
          "Die Brezeln liegen neben den Brötchen.",
          "Die Verkäuferin steht hinter der Theke.",
        ],
      },
    ],
    place_items: [
      {
        german_text: "Das Brot liegt im Regal.",
        preposition: "in",
        image_key: "baeckerei",
        translations: { bks: "Hljeb je na polici.", tr: "Ekmek rafta.", uk: "Хліб лежить на полиці.", ro: "Pâinea este pe raft.", ar: "الخبز على الرف." },
      },
      {
        german_text: "Die Brezeln liegen neben den Brötchen.",
        preposition: "neben",
        image_key: "baeckerei",
        translations: { bks: "Perece su pored peciva.", tr: "Pretzeller küçük ekmeklerin yanında.", uk: "Кренделі лежать поруч із булочками.", ro: "Covrigii sunt lângă chifle.", ar: "البريتزل بجانب اللفائف." },
      },
      {
        german_text: "Die Verkäuferin steht hinter der Theke.",
        preposition: "hinter",
        image_key: "baeckerei",
        translations: { bks: "Prodavačica stoji iza pulta.", tr: "Satıcı tezgâhın arkasında duruyor.", uk: "Продавчиня стоїть за прилавком.", ro: "Vânzătoarea stă în spatele tejghelei.", ar: "البائعة تقف خلف المنضدة." },
      },
      {
        german_text: "Die Kundin steht vor der Theke.",
        preposition: "vor",
        image_key: "baeckerei",
        translations: { bks: "Kupac stoji ispred pulta.", tr: "Müşteri tezgâhın önünde duruyor.", uk: "Покупчиня стоїть перед прилавком.", ro: "Clienta stă în fața tejghelei.", ar: "الزبونة تقف أمام المنضدة." },
      },
    ],
  },
  scenes: [
    { id: "bak-s1", position: 1, scene_group: "eingang", image_key: "baeckerei", german_text: "Mara geht in die Bäckerei.", translations: { bks: "Mara ide u pekaru.", tr: "Mara fırına gidiyor.", uk: "Мара йде до пекарні.", ro: "Mara merge la brutărie.", ar: "تذهب مارا إلى المخبز." } },
    { id: "bak-s2", position: 2, scene_group: "auslage", image_key: "baeckerei", german_text: "Sie schaut sich die Brote und Brötchen an.", translations: { bks: "Gleda hljeb i peciva.", tr: "Ekmeklere ve küçük ekmeklere bakıyor.", uk: "Вона дивиться на хліб і булочки.", ro: "Se uită la pâini și chifle.", ar: "تنظر إلى الخبز واللفائف." } },
    { id: "bak-s3", position: 3, scene_group: "begruesung", image_key: "baeckerei", german_text: "Die Verkäuferin sagt: „Guten Morgen!“", translations: { bks: "Prodavačica kaže: „Dobro jutro!“", tr: "Satıcı: „Günaydın!“ diyor.", uk: "Продавчиня каже: «Доброго ранку!»", ro: "Vânzătoarea spune: „Bună dimineața!“", ar: "تقول البائعة: «صباح الخير!»" } },
    { id: "bak-s4", position: 4, scene_group: "brot", image_key: "baeckerei", german_text: "Mara sagt: „Ich hätte gern ein Mischbrot, bitte.“", translations: { bks: "Mara kaže: „Htjela bih jedan miješani hljeb, molim.“", tr: "Mara: „Bir karışık ekmek alabilir miyim, lütfen?“ diyor.", uk: "Мара каже: «Я хотіла б один змішаний хліб, будь ласка.»", ro: "Mara spune: „Aș dori o pâine mixtă, vă rog.“", ar: "تقول مارا: «أود خبزًا مشكّلًا، من فضلك.»" } },
    { id: "bak-s5", position: 5, scene_group: "schneiden", image_key: "baeckerei", german_text: "Die Verkäuferin fragt: „Möchten Sie das Brot geschnitten?“", translations: { bks: "Prodavačica pita: „Želite li da hljeb bude narezan?“", tr: "Satıcı soruyor: „Ekmeği dilimlenmiş ister misiniz?“", uk: "Продавчиня запитує: «Бажаєте нарізаний хліб?»", ro: "Vânzătoarea întreabă: „Doriți pâinea feliată?“", ar: "تسأل البائعة: «هل تريدين الخبز مقطعًا؟»" } },
    { id: "bak-s6", position: 6, scene_group: "schneiden", image_key: "baeckerei", german_text: "Mara antwortet: „Ja, bitte.“", translations: { bks: "Mara odgovara: „Da, molim.“", tr: "Mara cevap veriyor: „Evet, lütfen.“", uk: "Мара відповідає: «Так, будь ласка.»", ro: "Mara răspunde: „Da, vă rog.“", ar: "تجيب مارا: «نعم، من فضلك.»" } },
    { id: "bak-s7", position: 7, scene_group: "schneiden", image_key: "baeckerei", german_text: "Die Verkäuferin schneidet das Brot.", translations: { bks: "Prodavačica reže hljeb.", tr: "Satıcı ekmeği dilimliyor.", uk: "Продавчиня нарізає хліб.", ro: "Vânzătoarea feliază pâinea.", ar: "تقطع البائعة الخبز." } },
    { id: "bak-s8", position: 8, scene_group: "broetchen", image_key: "baeckerei", german_text: "Mara sagt: „Ich nehme auch vier Brötchen, bitte.“", translations: { bks: "Mara kaže: „Uzet ću i četiri peciva, molim.“", tr: "Mara: „Dört küçük ekmek de alayım, lütfen.“ diyor.", uk: "Мара каже: «Я візьму ще чотири булочки, будь ласка.»", ro: "Mara spune: „Mai iau și patru chifle, vă rog.“", ar: "تقول مارا: «سآخذ أيضًا أربع لفائف، من فضلك.»" } },
    { id: "bak-s9", position: 9, scene_group: "weiter", image_key: "baeckerei", german_text: "Die Verkäuferin fragt: „Sonst noch etwas?“", translations: { bks: "Prodavačica pita: „Još nešto?“", tr: "Satıcı soruyor: „Başka bir şey?“", uk: "Продавчиня запитує: «Ще щось?»", ro: "Vânzătoarea întreabă: „Mai doriți ceva?“", ar: "تسأل البائعة: «هل تريدين شيئًا آخر؟»" } },
    { id: "bak-s10", position: 10, scene_group: "brezeln", image_key: "baeckerei", german_text: "Mara sagt: „Ja, zwei Brezeln, bitte.“", translations: { bks: "Mara kaže: „Da, dvije perece, molim.“", tr: "Mara: „Evet, iki pretzel, lütfen.“ diyor.", uk: "Мара каже: «Так, два кренделі, будь ласка.»", ro: "Mara spune: „Da, doi covrigi, vă rog.“", ar: "تقول مارا: «نعم، قطعتان من البريتزل، من فضلك.»" } },
    { id: "bak-s11", position: 11, scene_group: "zahlen", image_key: "baeckerei", german_text: "Die Verkäuferin sagt: „Das macht acht Euro zwanzig.“", translations: { bks: "Prodavačica kaže: „To je osam eura i dvadeset.“", tr: "Satıcı: „Sekiz euro yirmi.“ diyor.", uk: "Продавчиня каже: «З вас вісім євро двадцять.»", ro: "Vânzătoarea spune: „Opt euro și douăzeci.“", ar: "تقول البائعة: «ثمانية يورو وعشرون سنتًا.»" } },
    { id: "bak-s12", position: 12, scene_group: "zahlen", image_key: "baeckerei", german_text: "Mara fragt: „Kann ich mit Karte zahlen?“", translations: { bks: "Mara pita: „Mogu li platiti karticom?“", tr: "Mara soruyor: „Kartla ödeyebilir miyim?“", uk: "Мара запитує: «Можна оплатити карткою?»", ro: "Mara întreabă: „Pot plăti cu cardul?“", ar: "تسأل مارا: «هل يمكنني الدفع بالبطاقة؟»" } },
    { id: "bak-s13", position: 13, scene_group: "zahlen", image_key: "baeckerei", german_text: "Die Verkäuferin antwortet: „Ja, natürlich.“", translations: { bks: "Prodavačica odgovara: „Da, naravno.“", tr: "Satıcı cevap veriyor: „Evet, tabii.“", uk: "Продавчиня відповідає: «Так, звичайно.»", ro: "Vânzătoarea răspunde: „Da, bineînțeles.“", ar: "تجيب البائعة: «نعم، بالتأكيد.»" } },
    { id: "bak-s14", position: 14, scene_group: "abschied", image_key: "baeckerei", german_text: "Mara bezahlt und nimmt die Tüte.", translations: { bks: "Mara plaća i uzima kesu.", tr: "Mara ödüyor ve poşeti alıyor.", uk: "Мара платить і бере пакет.", ro: "Mara plătește și ia punga.", ar: "تدفع مارا وتأخذ الكيس." } },
    { id: "bak-s15", position: 15, scene_group: "abschied", image_key: "baeckerei", german_text: "Mara sagt: „Danke. Auf Wiedersehen!“", translations: { bks: "Mara kaže: „Hvala. Doviđenja!“", tr: "Mara: „Teşekkürler. Hoşça kalın!“ diyor.", uk: "Мара каже: «Дякую. До побачення!»", ro: "Mara spune: „Mulțumesc. La revedere!“", ar: "تقول مارا: «شكرًا. إلى اللقاء!»" } },
    { id: "bak-s16", position: 16, scene_group: "abschied", image_key: "baeckerei", german_text: "Die Verkäuferin sagt: „Auf Wiedersehen!“", translations: { bks: "Prodavačica kaže: „Doviđenja!“", tr: "Satıcı: „Hoşça kalın!“ diyor.", uk: "Продавчиня каже: «До побачення!»", ro: "Vânzătoarea spune: „La revedere!“", ar: "تقول البائعة: «إلى اللقاء!»" } },
  ],
  vocab: [
    ["das Brot", "Nomen", "das", "Brote", "Ich hätte gern ein Brot, bitte."],
    ["das Mischbrot", "Nomen", "das", "Mischbrote", "Ich hätte gern ein Mischbrot, bitte."],
    ["das Brötchen", "Nomen", "das", "Brötchen", "Ich nehme vier Brötchen, bitte."],
    ["die Brezel", "Nomen", "die", "Brezeln", "Zwei Brezeln, bitte."],
    ["die Bäckerei", "Nomen", "die", "Bäckereien", "Ich gehe in die Bäckerei."],
    ["die Verkäuferin", "Nomen", "die", "Verkäuferinnen", "Die Verkäuferin steht hinter der Theke."],
    ["die Kundin", "Nomen", "die", "Kundinnen", "Die Kundin steht vor der Theke."],
    ["die Theke", "Nomen", "die", "Theken", "Die Verkäuferin steht hinter der Theke."],
    ["die Tüte", "Nomen", "die", "Tüten", "Mara nimmt die Tüte."],
    ["schneiden", "Verb", "", "", "Die Verkäuferin schneidet das Brot."],
    ["geschnitten", "Adjektiv", "", "", "Möchten Sie das Brot geschnitten?"],
    ["nehmen", "Verb", "", "", "Ich nehme vier Brötchen."],
    ["zahlen", "Verb", "", "", "Kann ich mit Karte zahlen?"],
    ["kosten", "Verb", "", "", "Das kostet acht Euro zwanzig."],
    ["noch", "Adverb", "", "", "Sonst noch etwas?"],
    ["etwas", "Pronomen", "", "", "Möchten Sie noch etwas?"],
    ["bitte", "Partikel", "", "", "Ein Mischbrot, bitte."],
    ["danke", "Partikel", "", "", "Danke. Auf Wiedersehen!"],
    ["mit Karte", "Wendung", "", "", "Ich zahle mit Karte."],
    ["Auf Wiedersehen", "Wendung", "", "", "Danke. Auf Wiedersehen!"],
    ["im Regal", "Wendung", "", "", "Das Brot liegt im Regal."],
    ["hinter der Theke", "Wendung", "", "", "Die Verkäuferin steht hinter der Theke."],
  ].map((v, i) => ({ id: `bak-v${i + 1}`, position: i + 1, term: v[0], word_class: v[1], article: v[2], plural: v[3], example: v[4], example_translations: {}, collocations: [], translations: {} })),
  dialog: [
    [1, "Beim Brot", "A", "Verkäuferin", "Guten Morgen. Was darf es sein?"],
    [1, "Beim Brot", "B", "Kundin", "Guten Morgen. Ich hätte gern ein Mischbrot, bitte."],
    [1, "Beim Brot", "A", "Verkäuferin", "Gern. Möchten Sie das Brot geschnitten?"],
    [1, "Beim Brot", "B", "Kundin", "Ja, bitte."],
    [2, "Noch etwas dazu", "A", "Verkäuferin", "Sonst noch etwas?"],
    [2, "Noch etwas dazu", "B", "Kundin", "Ja, vier Brötchen und zwei Brezeln, bitte."],
    [2, "Noch etwas dazu", "A", "Verkäuferin", "Gerne. Sonst noch etwas?"],
    [2, "Noch etwas dazu", "B", "Kundin", "Nein, danke."],
    [3, "Bezahlen", "A", "Verkäuferin", "Das macht acht Euro zwanzig."],
    [3, "Bezahlen", "B", "Kundin", "Kann ich mit Karte zahlen?"],
    [3, "Bezahlen", "A", "Verkäuferin", "Ja, natürlich."],
    [3, "Bezahlen", "B", "Kundin", "Danke. Auf Wiedersehen!"],
    [3, "Bezahlen", "A", "Verkäuferin", "Auf Wiedersehen!"],
  ].map((d, i) => ({ id: `bak-d${i + 1}`, position: i + 1, dialog_index: d[0], dialog_title: d[1], speaker: d[2], speaker_role: d[3], german_text: d[4], translations: {} })),
  questions: [
    { id: "bak-q1", position: 1, kind: "single_choice", prompt: "Was sagt Mara natürlich, wenn sie ein Brot möchte?", explanation: "In einer Bäckerei ist „Ich hätte gern …“ eine sehr natürliche Formulierung.", section: "uebungen", data: {}, quiz_answers: [
      { id: "bak-q1a", position: 1, text: "Ich hätte gern ein Mischbrot, bitte.", is_correct: true },
      { id: "bak-q1b", position: 2, text: "Ich bestelle ein Brot.", is_correct: false },
      { id: "bak-q1c", position: 3, text: "Geben Brot.", is_correct: false },
    ] },
    { id: "bak-q2", position: 2, kind: "multi_choice", prompt: "Welche Sätze passen in einer Bäckerei? Mehrere Antworten sind richtig.", explanation: "Kurze höfliche Bestellungen sind im Alltag üblich.", section: "uebungen", data: {}, quiz_answers: [
      { id: "bak-q2a", position: 1, text: "Zwei Brezeln, bitte.", is_correct: true },
      { id: "bak-q2b", position: 2, text: "Ich nehme vier Brötchen, bitte.", is_correct: true },
      { id: "bak-q2c", position: 3, text: "Ich würde gern diese Ware akquirieren.", is_correct: false },
      { id: "bak-q2d", position: 4, text: "Ich hätte gern ein Mischbrot, bitte.", is_correct: true },
    ] },
    { id: "bak-q3", position: 3, kind: "gap", prompt: "Ich hätte gern ein Mischbrot, _____.", explanation: "„bitte“ macht die Bestellung höflich.", section: "uebungen", data: {}, quiz_answers: [{ id: "bak-q3a", position: 1, text: "bitte", is_correct: true }] },
    { id: "bak-q4", position: 4, kind: "sentence_order", prompt: "Baue den Satz richtig auf.", explanation: "Die Wortstellung lautet: Ich hätte gern ein Mischbrot, bitte.", section: "uebungen", data: { words: ["Ich", "hätte", "gern", "ein", "Mischbrot,", "bitte."] }, quiz_answers: [] },
    { id: "bak-q5", position: 5, kind: "gap_select", prompt: "Die Verkäuferin steht ___ der Theke.", explanation: "Die Verkäuferin arbeitet hinter der Theke.", section: "uebungen", data: { options: ["hinter", "unter", "auf", "vor"] }, quiz_answers: [{ id: "bak-q5a", position: 1, text: "hinter", is_correct: true }] },
    { id: "bak-q6", position: 6, kind: "order", prompt: "Bringe den Einkauf in eine logische Reihenfolge.", explanation: "Zuerst begrüßt man sich, dann bestellt man, danach bezahlt man und verabschiedet sich.", section: "uebungen", data: { items: ["Begrüßen", "Brot auswählen", "Brötchen und Brezeln nehmen", "Bezahlen", "Verabschieden"] }, quiz_answers: [] },
    { id: "bak-q7", position: 7, kind: "single_choice", prompt: "Was fragt die Verkäuferin, wenn sie wissen möchte, ob Mara noch etwas möchte?", explanation: "„Sonst noch etwas?“ ist eine sehr häufige Frage im Verkauf.", section: "uebungen", data: {}, quiz_answers: [
      { id: "bak-q7a", position: 1, text: "Sonst noch etwas?", is_correct: true },
      { id: "bak-q7b", position: 2, text: "Wo wohnen Sie?", is_correct: false },
      { id: "bak-q7c", position: 3, text: "Wie spät ist es?", is_correct: false },
    ] },
    { id: "bak-q8", position: 8, kind: "true_false", prompt: "Mara bezahlt mit Karte.", explanation: "Sie fragt: „Kann ich mit Karte zahlen?“", section: "uebungen", data: {}, quiz_answers: [
      { id: "bak-q8a", position: 1, text: "Richtig", is_correct: true },
      { id: "bak-q8b", position: 2, text: "Falsch", is_correct: false },
    ] },
    { id: "bak-q9", position: 9, kind: "dialog_order", prompt: "Bringe diesen kurzen Dialog in die richtige Reihenfolge.", explanation: "Achte auf Begrüßung, Bestellung und Rückfrage.", section: "uebungen", data: { items: ["Verkäuferin: Guten Morgen. Was darf es sein?", "Kundin: Guten Morgen. Ich hätte gern ein Mischbrot, bitte.", "Verkäuferin: Möchten Sie das Brot geschnitten?", "Kundin: Ja, bitte."] }, quiz_answers: [] },
    { id: "bak-q10", position: 10, kind: "single_choice", prompt: "Was bedeutet „geschnitten“ hier?", explanation: "Das Brot wird in Scheiben geschnitten.", section: "uebungen", data: {}, quiz_answers: [
      { id: "bak-q10a", position: 1, text: "Das Brot ist in Scheiben.", is_correct: true },
      { id: "bak-q10b", position: 2, text: "Das Brot ist warm.", is_correct: false },
      { id: "bak-q10c", position: 3, text: "Das Brot ist kostenlos.", is_correct: false },
    ] },
    { id: "bak-t1", position: 101, kind: "single_choice", prompt: "Welche Bestellung klingt natürlich?", explanation: "„Ich hätte gern …“ ist höflich und alltäglich.", section: "test", data: {}, quiz_answers: [
      { id: "bak-t1a", position: 1, text: "Ich hätte gern ein Mischbrot, bitte.", is_correct: true },
      { id: "bak-t1b", position: 2, text: "Ich bestelle Brotobjekt.", is_correct: false },
    ] },
    { id: "bak-t2", position: 102, kind: "gap_select", prompt: "Die Kundin steht ___ der Theke.", explanation: "Die Kundin steht vor der Theke.", section: "test", data: { options: ["vor", "hinter", "unter"] }, quiz_answers: [{ id: "bak-t2a", position: 1, text: "vor", is_correct: true }] },
    { id: "bak-t3", position: 103, kind: "true_false", prompt: "„Sonst noch etwas?“ bedeutet: Möchten Sie noch etwas?", explanation: "Ja, genau.", section: "test", data: {}, quiz_answers: [
      { id: "bak-t3a", position: 1, text: "Richtig", is_correct: true },
      { id: "bak-t3b", position: 2, text: "Falsch", is_correct: false },
    ] },
    { id: "bak-t4", position: 104, kind: "sentence_order", prompt: "Baue die Frage richtig auf.", explanation: "Kann ich mit Karte zahlen?", section: "test", data: { words: ["Kann", "ich", "mit", "Karte", "zahlen?"] }, quiz_answers: [] },
    { id: "bak-t5", position: 105, kind: "order", prompt: "Ordne die Schritte.", explanation: "So läuft der Einkauf logisch ab.", section: "test", data: { items: ["Begrüßen", "Bestellen", "Nachfragen", "Bezahlen", "Verabschieden"] }, quiz_answers: [] },
    { id: "bak-t6", position: 106, kind: "single_choice", prompt: "Was sagt man beim Abschied?", explanation: "„Auf Wiedersehen!“ passt hier.", section: "test", data: {}, quiz_answers: [
      { id: "bak-t6a", position: 1, text: "Auf Wiedersehen!", is_correct: true },
      { id: "bak-t6b", position: 2, text: "Gute Nacht!", is_correct: false },
      { id: "bak-t6c", position: 3, text: "Herzlichen Glückwunsch!", is_correct: false },
    ] },
  ],
};
