const T = (bks: string, tr: string, uk: string, ro: string, ar: string) => ({ bks, tr, uk, ro, ar });
const A = (id: string, text: string, is_correct: boolean, position: number) => ({ id, text, is_correct, position });
const H = (bks: string, tr: string, uk: string, ro: string, ar: string) => ({ help: T(bks, tr, uk, ro, ar) });

export const bakeryA2Override = {
  lesson: {
    id: "22222222-2222-2222-2222-222222222223",
    slug: "baeckerei-a2",
    title: "In der Bäckerei",
    description: "A2: Routinen, Vorlieben, Mengen, Alternativen, Empfehlungen und einfache Probleme beim Einkauf verständlich besprechen.",
    level: "A2",
    region: "de",
    category_slug: "alltag",
    subcategory_slug: "baeckerei",
    topic_slug: "baeckerei",
    topic_title: "In der Bäckerei",
    duration_seconds: 3000,
    thumbnail_key: "baeckerei",
    video_url: null,
    is_premium: false,
    status: "published",
    popularity: 99,
    grammar_topics: ["weil und deshalb", "welcher / welche / welches", "Komparativ", "Mengenangaben", "Perfekt im Alltag", "Modalverben", "Wünsche und Alternativen", "freundlich nachfragen"],
    grammar_notes: [
      { title: "A2: mehr als nur bestellen", explanation: "Auf A2 kann man Wünsche genauer beschreiben, Alternativen vergleichen, nachfragen und einfache Gründe nennen.", examples: ["Ich hätte gern etwas, das nicht zu süß ist.", "Welcher Kuchen ist heute frisch?", "Ich nehme das kleinere Brot, weil wir nur zu zweit sind."] },
      { title: "weil / deshalb", explanation: "Mit weil nennt man einen Grund. Mit deshalb nennt man eine Folge.", examples: ["Ich nehme nur ein kleines Brot, weil wir zu zweit sind.", "Ich habe wenig Bargeld, deshalb zahle ich mit Karte."] },
      { title: "Komparativ", explanation: "Mit -er und als vergleicht man Dinge.", examples: ["Das Roggenbrot ist kräftiger als das Weißbrot.", "Der Apfelkuchen ist weniger süß als die Torte."] },
      { title: "Perfekt für kurze Alltagserfahrungen", explanation: "A2-Lernende können kurz sagen, was schon passiert ist.", examples: ["Ich habe gestern dieses Brot gekauft.", "Wir haben die Torte schon probiert."] }
    ],
    place_items: [
      { german_text: "Die Verkäuferin steht hinter der Theke.", preposition: "hinter", image_key: "baeck-ill-01", translations: T("Prodavačica stoji iza pulta.", "Satıcı tezgâhın arkasında.", "Продавчиня за прилавком.", "Vânzătoarea este în spatele tejghelei.", "البائعة خلف المنضدة.") },
      { german_text: "Die Kuchen stehen nebeneinander in der Auslage.", preposition: "nebeneinander", image_key: "baeck-ill-03", translations: T("Kolači stoje jedan pored drugog u vitrini.", "Pastalar vitrinde yan yana.", "Торти стоять поруч у вітрині.", "Prăjiturile sunt una lângă alta în vitrină.", "الكعكات بجانب بعضها في الواجهة.") },
      { german_text: "Das Kartenlesegerät steht auf der Theke.", preposition: "auf", image_key: "baeck-ill-09", translations: T("Čitač kartica je na pultu.", "Kart okuyucu tezgâhın üstünde.", "Термінал стоїть на прилавку.", "Cititorul de card este pe tejghea.", "جهاز البطاقة على المنضدة.") }
    ]
  },

  scenes: [
    { id: "a2-s1", position: 1, image_key: "baeck-fenster", scene_type: "context", german_text: "Mara schaut aus dem Fenster ihrer Wohnung. Die Bäckerei liegt direkt gegenüber auf der anderen Straßenseite.", translations: T("Mara gleda kroz prozor svog stana. Pekara je odmah preko puta.", "Mara evinin penceresinden bakıyor. Fırın tam karşıda.", "Мара дивиться з вікна своєї квартири. Пекарня прямо навпроти.", "Mara privește pe fereastra apartamentului. Brutăria este chiar vizavi.", "تنظر مارا من نافذة شقتها. المخبز يقع مباشرة في الجهة المقابلة.") },
    { id: "a2-s2", position: 2, image_key: "baeck-strasse", scene_type: "enter", german_text: "Mara verlässt ihre Wohnung und geht über die Straße zur Bäckerei.", translations: T("Mara izlazi iz stana i prelazi ulicu do pekare.", "Mara evden çıkıp karşıdaki fırına gidiyor.", "Мара виходить з квартири й переходить вулицю до пекарні.", "Mara iese din apartament și traversează strada spre brutărie.", "تخرج مارا من شقتها وتعبر الشارع إلى المخبز.") },
    { id: "a2-s3", position: 3, image_key: "baeck-ill-02", scene_type: "look", german_text: "Sie betritt die Bäckerei und sieht die große Auslage.", translations: T("Ulazi u pekaru i vidi veliku vitrinu.", "Fırına giriyor ve büyük vitrini görüyor.", "Вона заходить до пекарні й бачить велику вітрину.", "Intră în brutărie și vede vitrina mare.", "تدخل المخبز وترى واجهة العرض الكبيرة.") },
    { id: "a2-s4", position: 4, image_key: "baeck-ill-01", scene_type: "greeting", german_text: "Die Verkäuferin begrüßt Mara freundlich und fragt, ob sie helfen kann.", translations: T("Prodavačica ljubazno pozdravlja Maru i pita može li pomoći.", "Satıcı Mara'yı sıcak karşılıyor ve yardım edip edemeyeceğini soruyor.", "Продавчиня привітно вітає Мару й питає, чи може допомогти.", "Vânzătoarea o salută prietenos pe Mara și întreabă dacă o poate ajuta.", "ترحب البائعة بمارا وتسأل إن كانت تستطيع مساعدتها.") },
    { id: "a2-s5", position: 5, image_key: "baeck-ill-02", scene_type: "look", german_text: "Mara schaut sich mehrere Kuchen an und überlegt, was sie nehmen möchte.", translations: T("Mara gleda nekoliko kolača i razmišlja šta želi uzeti.", "Mara birkaç pastaya bakıp hangisini alacağını düşünüyor.", "Мара розглядає кілька тортів і думає, який взяти.", "Mara se uită la mai multe prăjituri și se gândește ce să ia.", "تنظر مارا إلى عدة أنواع من الكعك وتفكر ماذا ستختار.") },
    { id: "a2-s6", position: 6, image_key: "baeck-ill-01", scene_type: "ask", german_text: "Sie erklärt, dass sie etwas Süßes sucht, das nicht zu schwer und nicht zu süß ist.", translations: T("Objašnjava da traži nešto slatko što nije preteško ni preslatko.", "Çok ağır ve çok tatlı olmayan bir şey aradığını söylüyor.", "Вона пояснює, що шукає щось солодке, але не надто важке й солодке.", "Spune că vrea ceva dulce, dar nu prea greu și nu prea dulce.", "توضح أنها تبحث عن شيء حلو لكنه ليس ثقيلاً أو شديد الحلاوة.") },
    { id: "a2-s7", position: 7, image_key: "baeck-ill-03", scene_type: "choice", german_text: "Die Verkäuferin zeigt Mara zwei passende Kuchen und erklärt den Unterschied.", translations: T("Prodavačica pokazuje Mari dva odgovarajuća kolača i objašnjava razliku.", "Satıcı Mara'ya iki uygun pasta gösterip farkı açıklıyor.", "Продавчиня показує Марі два відповідні торти й пояснює різницю.", "Vânzătoarea îi arată Marei două prăjituri potrivite și explică diferența.", "تعرض البائعة على مارا خيارين مناسبين وتشرح الفرق.") },
    { id: "a2-s8", position: 8, image_key: "baeck-ill-03", scene_type: "compare", german_text: "Sie empfiehlt den Apfelkuchen, weil er heute frisch gebacken wurde.", translations: T("Preporučuje kolač od jabuka jer je danas svježe pečen.", "Bugün taze piştiği için elmalı pastayı öneriyor.", "Вона радить яблучний пиріг, бо його сьогодні свіжо спекли.", "Recomandă prăjitura cu mere pentru că a fost coaptă azi.", "توصي بكعكة التفاح لأنها خُبزت اليوم طازجة.") },
    { id: "a2-s9", position: 9, image_key: "baeck-ill-03", scene_type: "ask", german_text: "Mara fragt, welcher Kuchen weniger süß ist.", translations: T("Mara pita koji je kolač manje sladak.", "Mara hangi pastanın daha az tatlı olduğunu soruyor.", "Мара питає, який торт менш солодкий.", "Mara întreabă care prăjitură este mai puțin dulce.", "تسأل مارا أي الكعكين أقل حلاوة.") },
    { id: "a2-s10", position: 10, image_key: "baeck-ill-03", scene_type: "compare", german_text: "Die Verkäuferin erklärt, dass der Apfelkuchen weniger süß als die Torte ist.", translations: T("Prodavačica objašnjava da je kolač od jabuka manje sladak od torte.", "Satıcı elmalı pastanın tortadan daha az tatlı olduğunu açıklıyor.", "Продавчиня пояснює, що яблучний пиріг менш солодкий за торт.", "Vânzătoarea explică faptul că prăjitura cu mere este mai puțin dulce decât tortul.", "توضح البائعة أن كعكة التفاح أقل حلاوة من التورتة.") },
    { id: "a2-s11", position: 11, image_key: "baeck-ill-04", scene_type: "select", german_text: "Mara entscheidet sich für ein Stück Apfelkuchen.", translations: T("Mara se odlučuje za komad kolača od jabuka.", "Mara bir dilim elmalı pasta seçiyor.", "Мара обирає шматок яблучного пирога.", "Mara alege o felie de prăjitură cu mere.", "تختار مارا قطعة من كعكة التفاح.") },
    { id: "a2-s12", position: 12, image_key: "baeck-ill-01", scene_type: "ask", german_text: "Sie fragt zusätzlich nach einem Brot für das Abendessen.", translations: T("Dodatno pita za hljeb za večeru.", "Ayrıca akşam yemeği için ekmek soruyor.", "Вона також питає про хліб на вечерю.", "Mai întreabă și de o pâine pentru cină.", "وتسأل أيضًا عن خبز للعشاء.") },
    { id: "a2-s13", position: 13, image_key: "baeck-ill-06", scene_type: "choice", german_text: "Die Verkäuferin zeigt ein Roggenbrot und ein helleres Mischbrot.", translations: T("Prodavačica pokazuje raženi hljeb i svjetliji miješani hljeb.", "Satıcı bir çavdar ekmeği ve daha açık renkli karışık ekmek gösteriyor.", "Продавчиня показує житній і світліший змішаний хліб.", "Vânzătoarea arată o pâine de secară și una mixtă mai deschisă.", "تعرض البائعة خبز الجاودار وخبزًا مخلوطًا أفتح لونًا.") },
    { id: "a2-s14", position: 14, image_key: "baeck-ill-06", scene_type: "compare", german_text: "Sie erklärt, dass das Roggenbrot kräftiger schmeckt und länger satt macht.", translations: T("Objašnjava da raženi hljeb ima jači okus i duže drži sitost.", "Çavdar ekmeğinin daha yoğun olduğunu ve daha uzun tok tuttuğunu söylüyor.", "Вона пояснює, що житній хліб має насиченіший смак і довше насичує.", "Explică faptul că pâinea de secară are gust mai intens și ține de foame mai mult.", "توضح أن خبز الجاودار أقوى نكهة ويشبع لمدة أطول.") },
    { id: "a2-s15", position: 15, image_key: "baeck-ill-06", scene_type: "select", german_text: "Mara nimmt das kleinere Roggenbrot, weil sie heute nur zu zweit essen.", translations: T("Mara uzima manji raženi hljeb jer danas jedu samo dvoje.", "Mara küçük çavdar ekmeğini alıyor çünkü bugün sadece iki kişiler.", "Мара бере менший житній хліб, бо сьогодні їдять лише вдвох.", "Mara ia pâinea de secară mai mică pentru că azi mănâncă doar doi.", "تأخذ مارا خبز الجاودار الأصغر لأنهما سيأكلان شخصين فقط.") },
    { id: "a2-s16", position: 16, image_key: "baeck-ill-06", scene_type: "ask", german_text: "Die Verkäuferin fragt: Geschnitten oder ganz?", translations: T("Prodavačica pita: Narezano ili cijelo?", "Satıcı soruyor: Dilimlenmiş mi bütün mü?", "Продавчиня питає: Нарізати чи залишити цілим?", "Vânzătoarea întreabă: Feliată sau întreagă?", "تسأل البائعة: مقطع أم كامل؟") },
    { id: "a2-s17", position: 17, image_key: "baeck-ill-06", scene_type: "select", german_text: "Mara möchte das Brot geschnitten, damit sie es später leichter einfrieren kann.", translations: T("Mara želi narezani hljeb da ga kasnije lakše zamrzne.", "Mara ekmeği dilimlenmiş istiyor, böylece sonra daha kolay dondurabilir.", "Мара хоче нарізаний хліб, щоб потім легше заморозити.", "Mara vrea pâinea feliată ca să o poată congela mai ușor.", "تريد مارا الخبز مقطعًا كي تتمكن من تجميده بسهولة لاحقًا.") },
    { id: "a2-s18", position: 18, image_key: "baeck-ill-07", scene_type: "solution", german_text: "Das Brot wird in der Schneidemaschine in gleichmäßige Scheiben geschnitten.", translations: T("Hljeb se u mašini reže na jednake kriške.", "Ekmek dilimleme makinesinde eşit dilimlere kesiliyor.", "Хліб у машині нарізають на рівні скибки.", "Pâinea este tăiată în felii egale în mașina de feliat.", "يُقطع الخبز في آلة التقطيع إلى شرائح متساوية.") },
    { id: "a2-s19", position: 19, image_key: "baeck-ill-08", scene_type: "handover", german_text: "Die Verkäuferin packt Brot und Kuchen getrennt ein.", translations: T("Prodavačica pakuje hljeb i kolač odvojeno.", "Satıcı ekmek ve pastayı ayrı ayrı paketliyor.", "Продавчиня пакує хліб і пиріг окремо.", "Vânzătoarea împachetează separat pâinea și prăjitura.", "تغلف البائعة الخبز والكعك كلًا على حدة.") },
    { id: "a2-s20", position: 20, image_key: "baeck-ill-08", scene_type: "pay_cash", german_text: "An der Kasse fragt Mara nach dem Gesamtpreis und nach einer kleinen Tüte.", translations: T("Na kasi Mara pita za ukupnu cijenu i malu vrećicu.", "Kasada Mara toplam fiyatı ve küçük bir poşeti soruyor.", "На касі Мара питає загальну ціну й маленький пакет.", "La casă, Mara întreabă prețul total și cere o pungă mică.", "عند الصندوق تسأل مارا عن السعر الإجمالي وكيس صغير.") },
    { id: "a2-s21", position: 21, image_key: "baeck-ill-08", scene_type: "pay_cash", german_text: "Die Verkäuferin nennt den Gesamtpreis und zeigt ihn auf der Kasse.", translations: T("Prodavačica kaže ukupnu cijenu i pokazuje je na kasi.", "Satıcı toplam fiyatı söylüyor ve kasada gösteriyor.", "Продавчиня називає загальну суму й показує її на касі.", "Vânzătoarea spune prețul total și îl arată la casă.", "تذكر البائعة السعر الإجمالي وتعرضه على شاشة الصندوق.") },
    { id: "a2-s22", position: 22, image_key: "baeck-wallet", scene_type: "wallet", needs_image: false, german_text: "Mara schaut in ihre Geldbörse und merkt, dass sie nicht genug Bargeld dabeihat.", translations: T("Mara gleda u novčanik i vidi da nema dovoljno gotovine.", "Mara cüzdanına bakıp yeterince nakdi olmadığını fark ediyor.", "Мара дивиться в гаманець і помічає, що має недостатньо готівки.", "Mara se uită în portofel și vede că nu are destui bani cash.", "تنظر مارا في محفظتها وتلاحظ أنه ليس معها ما يكفي من النقود.") },
    { id: "a2-s23", position: 23, image_key: "baeck-ill-09", scene_type: "pay_card", german_text: "Sie fragt, ob sie mit Karte bezahlen kann.", translations: T("Pita može li platiti karticom.", "Kartla ödeyip ödeyemeyeceğini soruyor.", "Вона питає, чи можна заплатити карткою.", "Întreabă dacă poate plăti cu cardul.", "تسأل إن كان بإمكانها الدفع بالبطاقة.") },
    { id: "a2-s24", position: 24, image_key: "baeck-bon", scene_type: "receipt", needs_image: false, german_text: "Mara bezahlt mit Karte und bekommt den Kassenbon.", translations: T("Mara plaća karticom i dobija račun.", "Mara kartla ödüyor ve fişi alıyor.", "Мара платить карткою й отримує чек.", "Mara plătește cu cardul și primește bonul.", "تدفع مارا بالبطاقة وتحصل على الإيصال.") },
    { id: "a2-s25", position: 25, image_key: "baeck-heimweg", scene_type: "return_home", needs_image: false, german_text: "Mara nimmt die Tüte, bedankt sich und geht zurück zu ihrer Wohnung gegenüber.", translations: T("Mara uzima vrećicu, zahvaljuje se i vraća se u stan preko puta.", "Mara poşeti alıyor, teşekkür ediyor ve karşıdaki evine dönüyor.", "Мара бере пакет, дякує й повертається до квартири навпроти.", "Mara ia punga, mulțumește și se întoarce în apartamentul de vizavi.", "تأخذ مارا الكيس وتشكر البائعة وتعود إلى شقتها المقابلة.") }
  ],

  vocab: [
    ["die Empfehlung", "Nomen", "die", "die Empfehlungen", "Haben Sie eine Empfehlung?", T("preporuka", "öneri", "рекомендація", "recomandare", "توصية")],
    ["die Brotsorte", "Nomen", "die", "die Brotsorten", "Welche Brotsorte ist kräftiger?", T("vrsta hljeba", "ekmek çeşidi", "вид хліба", "tip de pâine", "نوع الخبز")],
    ["das Roggenbrot", "Nomen", "das", "die Roggenbrote", "Ich nehme ein Roggenbrot.", T("raženi hljeb", "çavdar ekmeği", "житній хліб", "pâine de secară", "خبز الجاودار")],
    ["frisch gebacken", "Wendung", null, null, "Der Kuchen ist heute frisch gebacken.", T("svježe pečeno", "taze pişmiş", "свіжоспечений", "proaspăt copt", "مخبوز طازج")],
    ["nicht zu süß", "Wendung", null, null, "Ich suche etwas, das nicht zu süß ist.", T("ne previše slatko", "çok tatlı olmayan", "не надто солодкий", "nu prea dulce", "ليس حلوًا جدًا")],
    ["kleiner / größer", "Adjektiv", null, null, "Ich nehme das kleinere Brot.", T("manji / veći", "daha küçük / daha büyük", "менший / більший", "mai mic / mai mare", "أصغر / أكبر")],
    ["kräftig", "Adjektiv", null, null, "Roggenbrot schmeckt kräftiger.", T("jak okus", "yoğun", "насичений", "intens", "قوي النكهة")],
    ["der Unterschied", "Nomen", "der", "die Unterschiede", "Was ist der Unterschied?", T("razlika", "fark", "різниця", "diferență", "فرق")],
    ["einfrieren", "Verb", null, null, "Ich friere das Brot ein.", T("zamrznuti", "dondurmak", "заморожувати", "a congela", "يجمّد")],
    ["der Gesamtpreis", "Nomen", "der", "die Gesamtpreise", "Wie hoch ist der Gesamtpreis?", T("ukupna cijena", "toplam fiyat", "загальна ціна", "preț total", "السعر الإجمالي")],
    ["der Kassenbon", "Nomen", "der", "die Kassenbons", "Kann ich den Kassenbon haben?", T("račun", "fiş", "чек", "bon", "إيصال")],
    ["Bargeld", "Nomen", "das", "—", "Ich habe nicht genug Bargeld dabei.", T("gotovina", "nakit", "готівка", "numerar", "نقد")],
    ["dabeihaben", "Verb", null, null, "Ich habe meine Karte dabei.", T("imati sa sobom", "yanında bulundurmak", "мати при собі", "a avea la tine", "يحمل معه")],
    ["empfehlen", "Verb", null, null, "Was können Sie empfehlen?", T("preporučiti", "önermek", "рекомендувати", "a recomanda", "يوصي")],
    ["probieren", "Verb", null, null, "Ich habe den Kuchen schon probiert.", T("probati", "denemek", "спробувати", "a încerca", "يجرّب")],
    ["weniger", "Adverb", null, null, "Der Kuchen ist weniger süß.", T("manje", "daha az", "менше", "mai puțin", "أقل")],
    ["deshalb", "Konjunktion", null, null, "Ich habe wenig Bargeld, deshalb zahle ich mit Karte.", T("zato", "bu yüzden", "тому", "de aceea", "لذلك")],
    ["weil", "Konjunktion", null, null, "Ich nehme das kleine Brot, weil wir zu zweit sind.", T("jer", "çünkü", "тому що", "pentru că", "لأن")]
  ].map((v, i) => ({ id: `a2-v${i + 1}`, position: i + 1, term: v[0], word_class: v[1], article: v[2], plural: v[3], example: v[4], example_translations: v[5], translations: v[5], collocations: [] })),

  dialog: [
    [1, "Eine Empfehlung bekommen", "V", "Verkäuferin", "Guten Morgen. Kann ich Ihnen helfen?", T("Dobro jutro. Mogu li vam pomoći?", "Günaydın. Yardımcı olabilir miyim?", "Доброго ранку. Чим можу допомогти?", "Bună dimineața. Vă pot ajuta?", "صباح الخير. هل يمكنني مساعدتك؟")],
    [1, "Eine Empfehlung bekommen", "K", "Kundin", "Ja, gern. Ich suche etwas Süßes, aber nicht zu süß. Was können Sie empfehlen?", T("Da. Tražim nešto slatko, ali ne preslatko. Šta preporučujete?", "Evet. Tatlı ama çok tatlı olmayan bir şey arıyorum. Ne önerirsiniz?", "Так. Я шукаю щось солодке, але не надто солодке. Що порадите?", "Da. Caut ceva dulce, dar nu prea dulce. Ce recomandați?", "نعم. أبحث عن شيء حلو لكن ليس شديد الحلاوة. ماذا تنصحين؟")],
    [1, "Eine Empfehlung bekommen", "V", "Verkäuferin", "Unser Apfelkuchen ist heute frisch gebacken und weniger süß als die Schokotorte.", T("Naš kolač od jabuka je danas svježe pečen i manje sladak od čokoladne torte.", "Elmalı pastamız bugün taze ve çikolatalı pastadan daha az tatlı.", "Наш яблучний пиріг сьогодні свіжий і менш солодкий, ніж шоколадний торт.", "Prăjitura cu mere e proaspătă azi și mai puțin dulce decât tortul de ciocolată.", "كعكة التفاح طازجة اليوم وأقل حلاوة من كعكة الشوكولاتة.")],
    [1, "Eine Empfehlung bekommen", "K", "Kundin", "Dann nehme ich ein Stück Apfelkuchen. Und welches Brot ist gut fürs Abendessen?", T("Onda uzimam komad kolača od jabuka. A koji hljeb je dobar za večeru?", "O zaman bir dilim elmalı pasta alayım. Akşam yemeği için hangi ekmek iyi?", "Тоді я візьму шматок яблучного пирога. А який хліб добрий на вечерю?", "Atunci iau o felie de prăjitură cu mere. Și ce pâine e bună pentru cină?", "إذن سأأخذ قطعة من كعكة التفاح. وأي خبز مناسب للعشاء؟")],
    [1, "Eine Empfehlung bekommen", "V", "Verkäuferin", "Wenn Sie etwas Kräftigeres mögen, würde ich das Roggenbrot empfehlen.", T("Ako volite nešto jačeg okusa, preporučila bih raženi hljeb.", "Daha yoğun bir şey seviyorsanız çavdar ekmeğini öneririm.", "Якщо любите більш насичений смак, раджу житній хліб.", "Dacă vă place un gust mai intens, recomand pâinea de secară.", "إذا كنت تحبين نكهة أقوى، أنصح بخبز الجاودار.")],
    [1, "Eine Empfehlung bekommen", "K", "Kundin", "Gut, dann nehme ich das kleinere. Wir sind heute nur zu zweit.", T("Dobro, onda uzimam manji. Danas smo samo dvoje.", "Tamam, o zaman küçüğünü alayım. Bugün sadece iki kişiyiz.", "Добре, тоді візьму менший. Сьогодні нас лише двоє.", "Bine, atunci îl iau pe cel mai mic. Azi suntem doar doi.", "حسنًا، سأأخذ الأصغر. نحن شخصان فقط اليوم.")],
    [1, "Eine Empfehlung bekommen", "V", "Verkäuferin", "Möchten Sie es geschnitten?", T("Želite li ga narezanog?", "Dilimlenmiş ister misiniz?", "Нарізати?", "Doriți să fie feliată?", "هل تريدينه مقطعًا؟")],
    [1, "Eine Empfehlung bekommen", "K", "Kundin", "Ja, bitte. Dann kann ich einen Teil einfrieren.", T("Da, molim. Onda mogu dio zamrznuti.", "Evet lütfen. Böylece bir kısmını dondurabilirim.", "Так, будь ласка. Тоді частину зможу заморозити.", "Da, vă rog. Așa pot congela o parte.", "نعم من فضلك. عندها أستطيع تجميد جزء منه.")],
    [2, "An der Kasse", "V", "Verkäuferin", "Das macht zusammen vierzehn Euro zwanzig.", T("Ukupno je četrnaest eura i dvadeset.", "Toplam on dört euro yirmi.", "Разом чотирнадцять євро двадцять.", "În total sunt paisprezece euro și douăzeci.", "المجموع أربعة عشر يورو وعشرون سنتًا.")],
    [2, "An der Kasse", "K", "Kundin", "Ich habe heute nicht genug Bargeld dabei. Kann ich mit Karte zahlen?", T("Danas nemam dovoljno gotovine. Mogu li platiti karticom?", "Bugün yeterince nakdim yok. Kartla ödeyebilir miyim?", "Сьогодні в мене недостатньо готівки. Можна карткою?", "Nu am suficient numerar la mine azi. Pot plăti cu cardul?", "ليس معي نقد كافٍ اليوم. هل يمكنني الدفع بالبطاقة؟")],
    [2, "An der Kasse", "V", "Verkäuferin", "Natürlich. Möchten Sie den Kassenbon?", T("Naravno. Želite li račun?", "Tabii. Fişi ister misiniz?", "Звичайно. Вам потрібен чек?", "Desigur. Doriți bonul?", "بالطبع. هل تريدين الإيصال؟")],
    [2, "An der Kasse", "K", "Kundin", "Ja, bitte. Und könnten Sie mir noch eine kleine Tüte geben?", T("Da, molim. I možete li mi dati malu vrećicu?", "Evet lütfen. Bir de küçük poşet verebilir misiniz?", "Так, будь ласка. І можете дати маленький пакет?", "Da, vă rog. Și îmi puteți da o pungă mică?", "نعم من فضلك. وهل يمكنك إعطائي كيسًا صغيرًا؟")],
    [2, "An der Kasse", "V", "Verkäuferin", "Gerne. Hier sind die Tüte und der Bon.", T("Naravno. Evo vrećice i računa.", "Tabii. İşte poşet ve fiş.", "Звичайно. Ось пакет і чек.", "Sigur. Iată punga și bonul.", "بكل سرور. هذا الكيس والإيصال.")],
    [2, "An der Kasse", "K", "Kundin", "Danke. Der Apfelkuchen war letztes Mal sehr gut. Den nehme ich bestimmt wieder.", T("Hvala. Kolač od jabuka je prošli put bio odličan. Sigurno ću ga opet uzeti.", "Teşekkürler. Elmalı pasta geçen sefer çok iyiydi. Kesin yine alırım.", "Дякую. Минулого разу яблучний пиріг був дуже смачний. Обов'язково візьму знову.", "Mulțumesc. Prăjitura cu mere a fost foarte bună data trecută. Sigur o voi lua din nou.", "شكرًا. كانت كعكة التفاح ممتازة في المرة الماضية. سأشتريها بالتأكيد مرة أخرى.")]
  ].map((d, i) => ({ id: `a2-d${i + 1}`, position: i + 1, dialog_index: d[0], dialog_title: d[1], speaker: d[2], speaker_role: d[3], german_text: d[4], translations: d[5] })),

  questions: [
    { id: "a2-g1", position: 1, kind: "single_choice", section: "grammar", prompt: "Welche Formulierung passt zu A2, wenn man eine Empfehlung möchte?", explanation: "A2 kann Wünsche genauer beschreiben und nach Empfehlungen fragen.", data: H("Kako pristojno tražiti preporuku?", "Öneri nasıl istenir?", "Як попросити рекомендацію?", "Cum ceri o recomandare?", "كيف تطلب توصية؟"), quiz_answers: [A("a", "Ich suche etwas, das nicht zu süß ist. Was können Sie empfehlen?", true, 1), A("b", "Kuchen!", false, 2), A("c", "Ich sein süß.", false, 3)] },
    { id: "a2-g2", position: 2, kind: "gap_select", section: "grammar", prompt: "Ich nehme das kleinere Brot, ___ wir heute nur zu zweit sind.", explanation: "weil nennt den Grund.", data: { options: ["weil", "deshalb", "aber", "oder"], ...H("jer = weil", "çünkü = weil", "тому що = weil", "pentru că = weil", "لأن = weil") }, quiz_answers: [A("a", "weil", true, 1)] },
    { id: "a2-g3", position: 3, kind: "gap_select", section: "grammar", prompt: "Ich habe wenig Bargeld, ___ zahle ich mit Karte.", explanation: "deshalb nennt die Folge.", data: { options: ["deshalb", "weil", "obwohl", "denn"], ...H("zato = deshalb", "bu yüzden = deshalb", "тому = deshalb", "de aceea = deshalb", "لذلك = deshalb") }, quiz_answers: [A("a", "deshalb", true, 1)] },
    { id: "a2-g4", position: 4, kind: "single_choice", section: "grammar", prompt: "Welcher Satz vergleicht zwei Produkte?", explanation: "Der Komparativ vergleicht.", data: H("Koja rečenica poredi dva proizvoda?", "Hangi cümle iki ürünü karşılaştırıyor?", "Яке речення порівнює два продукти?", "Ce propoziție compară două produse?", "أي جملة تقارن منتجين؟"), quiz_answers: [A("a", "Das Roggenbrot ist kräftiger als das Weißbrot.", true, 1), A("b", "Ich nehme Brot.", false, 2), A("c", "Guten Morgen.", false, 3)] },
    { id: "a2-g5", position: 5, kind: "single_choice", section: "grammar", prompt: "Welche Form ist korrekt?", explanation: "Perfekt: ich habe gekauft.", data: H("Koja je Perfekt forma?", "Perfekt hangisi?", "Яка форма Perfekt?", "Care este forma de perfect compus?", "ما صيغة الماضي؟"), quiz_answers: [A("a", "Ich habe gestern dieses Brot gekauft.", true, 1), A("b", "Ich habe gestern dieses Brot kaufen.", false, 2), A("c", "Ich gekauft Brot gestern.", false, 3)] },
    { id: "a2-u1", position: 20, kind: "single_choice", section: "uebungen", prompt: "Mara möchte etwas Leichtes und nicht zu Süßes. Was sagt sie?", explanation: "Sie beschreibt eine Vorliebe genauer.", data: H("Mara želi nešto lagano i ne preslatko.", "Mara hafif ve çok tatlı olmayan bir şey istiyor.", "Мара хоче щось легке й не надто солодке.", "Mara vrea ceva ușor și nu prea dulce.", "مارا تريد شيئًا خفيفًا وغير شديد الحلاوة."), quiz_answers: [A("a", "Ich suche etwas Süßes, aber nicht zu süß.", true, 1), A("b", "Ich möchte alles.", false, 2), A("c", "Ist hier ein Bahnhof?", false, 3)] },
    { id: "a2-u2", position: 21, kind: "single_choice", section: "uebungen", prompt: "Die Verkäuferin sagt: „Das Roggenbrot ist kräftiger.“ Was meint sie?", explanation: "kräftiger beschreibt einen intensiveren Geschmack.", data: H("Šta znači kräftiger?", "kräftiger ne demek?", "Що означає kräftiger?", "Ce înseamnă kräftiger?", "ماذا تعني kräftiger؟"), quiz_answers: [A("a", "Es hat einen intensiveren Geschmack.", true, 1), A("b", "Es ist kostenlos.", false, 2), A("c", "Es ist flüssig.", false, 3)] },
    { id: "a2-u3", position: 22, kind: "single_choice", section: "uebungen", prompt: "Warum möchte Mara das Brot geschnitten?", explanation: "Sie möchte einen Teil einfrieren.", data: H("Zašto želi narezani hljeb?", "Neden dilimlenmiş istiyor?", "Чому вона хоче нарізаний хліб?", "De ce îl vrea feliat?", "لماذا تريده مقطعًا؟"), quiz_answers: [A("a", "Damit sie einen Teil leichter einfrieren kann.", true, 1), A("b", "Weil sie keinen Kuchen mag.", false, 2), A("c", "Weil die Bäckerei schließt.", false, 3)] },
    { id: "a2-u4", position: 23, kind: "sentence_order", section: "uebungen", prompt: "Baue die Frage richtig auf.", explanation: "Was können Sie empfehlen?", data: { words: ["Was", "können", "Sie", "empfehlen?"], ...H("Šta možete preporučiti?", "Ne önerebilirsiniz?", "Що можете порадити?", "Ce puteți recomanda?", "ماذا يمكنك أن توصي؟") }, quiz_answers: [] },
    { id: "a2-u5", position: 24, kind: "true_false", section: "uebungen", prompt: "Auf A2 kann man einfache Gründe und Vorlieben nennen.", explanation: "Richtig.", data: H("Na A2 možeš navesti jednostavne razloge i preference.", "A2'de basit neden ve tercihler söylenebilir.", "На A2 можна називати прості причини й уподобання.", "La A2 poți exprima motive simple și preferințe.", "في A2 يمكن ذكر أسباب وتفضيلات بسيطة."), quiz_answers: [A("a", "Richtig", true, 1), A("b", "Falsch", false, 2)] },
    { id: "a2-db1", position: 40, kind: "sentence_order", section: "dialog_builder", prompt: "Dialog bauen: Empfehlung → Auswahl → Brot → Grund → Schneiden.", explanation: "Ordne die Gesprächsteile logisch.", data: { words: ["Verkäuferin: Kann ich Ihnen helfen?", "Kundin: Ich suche etwas, das nicht zu süß ist.", "Verkäuferin: Ich empfehle den Apfelkuchen.", "Kundin: Dann nehme ich ein Stück.", "Kundin: Welches Brot ist gut fürs Abendessen?", "Verkäuferin: Das Roggenbrot ist kräftiger.", "Kundin: Ich nehme das kleinere, weil wir zu zweit sind.", "Verkäuferin: Möchten Sie es geschnitten?", "Kundin: Ja, bitte."], ...H("Složi dijalog.", "Diyaloğu sırala.", "Склади діалог.", "Ordonează dialogul.", "رتّب الحوار.") }, quiz_answers: [] },
    { id: "a2-t1", position: 100, kind: "single_choice", section: "test", prompt: "Welche Aussage zeigt A2-Niveau am besten?", explanation: "A2 beschreibt routinemäßige Situationen etwas genauer.", data: H("Koja rečenica najbolje odgovara A2?", "Hangisi A2'ye daha uygun?", "Яке речення найбільше відповідає A2?", "Care propoziție corespunde cel mai bine A2?", "أي جملة تناسب مستوى A2 أكثر؟"), quiz_answers: [A("a", "Ich nehme das kleinere Brot, weil wir heute nur zu zweit sind.", true, 1), A("b", "Brot bitte.", false, 2), A("c", "Die ökonomische Entwicklung der Bäckereibranche ist komplex.", false, 3)] },
    { id: "a2-t2", position: 101, kind: "single_choice", section: "test", prompt: "Was ist eine natürliche Frage nach einer Empfehlung?", explanation: "Was können Sie empfehlen?", data: H("Prirodno pitanje za preporuku?", "Doğal öneri sorusu?", "Природне питання про рекомендацію?", "Întrebare naturală pentru recomandare?", "سؤال طبيعي لطلب توصية؟"), quiz_answers: [A("a", "Was können Sie empfehlen?", true, 1), A("b", "Empfehlung geben!", false, 2), A("c", "Wo ist der Arzt?", false, 3)] },
    { id: "a2-t3", position: 102, kind: "single_choice", section: "test", prompt: "Was bedeutet „weniger süß“?", explanation: "Es enthält bzw. schmeckt nicht so süß wie etwas anderes.", data: H("Šta znači manje slatko?", "Daha az tatlı ne demek?", "Що означає менш солодкий?", "Ce înseamnă mai puțin dulce?", "ماذا يعني أقل حلاوة؟"), quiz_answers: [A("a", "Nicht so süß wie etwas anderes.", true, 1), A("b", "Süßer als alles andere.", false, 2), A("c", "Ganz salzig.", false, 3)] },
    { id: "a2-t4", position: 103, kind: "gap_select", section: "test", prompt: "Wir sind nur zu zweit, ___ nehme ich das kleinere Brot.", explanation: "deshalb = Folge.", data: { options: ["deshalb", "weil", "obwohl", "wenn"], ...H("zato = deshalb", "bu yüzden = deshalb", "тому = deshalb", "de aceea = deshalb", "لذلك = deshalb") }, quiz_answers: [A("a", "deshalb", true, 1)] },
    { id: "a2-t5", position: 104, kind: "single_choice", section: "test", prompt: "Was ist ein Kassenbon?", explanation: "Der Beleg über den Einkauf.", data: H("račun", "fiş", "чек", "bon", "إيصال"), quiz_answers: [A("a", "Ein Beleg über den Einkauf.", true, 1), A("b", "Eine Brotsorte.", false, 2), A("c", "Ein Messer.", false, 3)] },
    { id: "a2-t6", position: 105, kind: "single_choice", section: "test", prompt: "Welche Aussage ist im Perfekt korrekt?", explanation: "haben + Partizip II.", data: H("Koja rečenica u perfektu je tačna?", "Doğru Perfekt cümlesi?", "Правильне речення в Perfekt?", "Propoziție corectă la perfect?", "الجملة الصحيحة في الماضي؟"), quiz_answers: [A("a", "Ich habe den Kuchen schon probiert.", true, 1), A("b", "Ich bin den Kuchen probiert.", false, 2), A("c", "Ich habe probieren den Kuchen.", false, 3)] },
    { id: "a2-t7", position: 106, kind: "single_choice", section: "test", prompt: "Warum zahlt Mara mit Karte?", explanation: "Sie hat nicht genug Bargeld dabei.", data: H("Zašto plaća karticom?", "Neden kartla ödüyor?", "Чому платить карткою?", "De ce plătește cu cardul?", "لماذا تدفع بالبطاقة؟"), quiz_answers: [A("a", "Weil sie nicht genug Bargeld dabeihat.", true, 1), A("b", "Weil das Brot zu süß ist.", false, 2), A("c", "Weil sie den Bus verpasst hat.", false, 3)] },
    { id: "a2-t8", position: 107, kind: "single_choice", section: "test", prompt: "Was ist eine Brotsorte?", explanation: "Eine bestimmte Art von Brot.", data: H("vrsta hljeba", "ekmek çeşidi", "вид хліба", "tip de pâine", "نوع الخبز"), quiz_answers: [A("a", "Eine bestimmte Art von Brot.", true, 1), A("b", "Ein Zahlungsgerät.", false, 2), A("c", "Eine Person.", false, 3)] }
  ]
};

bakeryA2Override.scenes = bakeryA2Override.scenes.map((scene) => ({ ...scene, scene_group: scene.id }));