const T = (bks: string, tr: string, uk: string, ro: string, ar: string) => ({ bks, tr, uk, ro, ar });
const A = (id: string, text: string, is_correct: boolean, position: number) => ({ id, text, is_correct, position });
const H = (bks: string, tr: string, uk: string, ro: string, ar: string) => ({ help: T(bks, tr, uk, ro, ar) });

export const bakeryB1Override = {
  lesson: {
    id: "22222222-2222-2222-2222-222222222224",
    slug: "baeckerei-b1",
    title: "In der Bäckerei",
    description: "B1: Weniger routinemäßige Situationen bewältigen, Probleme erklären, Informationen prüfen und kurze Begründungen geben.",
    level: "B1",
    region: "de",
    category_slug: "alltag",
    subcategory_slug: "baeckerei",
    topic_slug: "baeckerei",
    topic_title: "In der Bäckerei",
    duration_seconds: 3300,
    thumbnail_key: "baeckerei",
    video_url: null,
    is_premium: true,
    status: "published",
    popularity: 98,
    grammar_topics: ["Nebensätze mit obwohl / damit", "Konjunktiv II für höfliche Lösungen", "Relativsätze", "Perfekt und Präteritum im Bericht", "Meinung und Begründung", "Probleme erklären", "Informationen bestätigen", "Alternativen aushandeln"],
    grammar_notes: [
      { title: "B1: ein Problem verständlich erklären", explanation: "Auf B1 kann man sagen, was passiert ist, warum etwas problematisch ist und welche Lösung man möchte.", examples: ["Ich glaube, ich habe das falsche Brot bekommen.", "Das ist problematisch, weil ich eine Nussallergie habe.", "Könnten Sie bitte prüfen, ob dieser Kuchen Nüsse enthält?"] },
      { title: "obwohl / trotzdem", explanation: "Mit obwohl beschreibt man einen Gegensatz. trotzdem steht oft im Hauptsatz.", examples: ["Obwohl ich wenig Zeit hatte, bin ich noch zur Bäckerei gegangen.", "Das Brot war etwas teurer, trotzdem habe ich es genommen."] },
      { title: "Konjunktiv II für höfliche Lösungen", explanation: "würde, könnte, hätte machen Vorschläge und Wünsche höflicher.", examples: ["Könnten Sie das bitte noch einmal prüfen?", "Ich würde lieber ein anderes Brot nehmen.", "Ich hätte gern eine Lösung ohne Aufpreis."] },
      { title: "Relativsätze", explanation: "Relativsätze beschreiben Nomen genauer.", examples: ["Ich suche ein Brot, das lange frisch bleibt.", "Das ist der Kuchen, den ich gestern gekauft habe."] }
    ],
    place_items: [
      { german_text: "Mara steht der Verkäuferin gegenüber und erklärt ein Problem.", preposition: "gegenüber", image_key: "baeck-ill-01", translations: T("Mara stoji nasuprot prodavačici i objašnjava problem.", "Mara satıcının karşısında durup bir sorunu açıklıyor.", "Мара стоїть навпроти продавчині й пояснює проблему.", "Mara stă vizavi de vânzătoare și explică o problemă.", "تقف مارا مقابل البائعة وتشرح مشكلة.") },
      { german_text: "Der Kassenbon liegt neben dem Kartenlesegerät.", preposition: "neben", image_key: "baeck-ill-09", translations: T("Račun leži pored čitača kartica.", "Fiş kart okuyucunun yanında.", "Чек лежить біля термінала.", "Bonul este lângă cititorul de card.", "الإيصال بجانب جهاز البطاقة.") }
    ]
  },

  scenes: [
    { id: "b1-s1", position: 1, image_key: "baeck-ill-10", german_text: "Mara kommt zurück in die Bäckerei, weil sie zu Hause gemerkt hat, dass etwas mit ihrem Einkauf nicht stimmt.", translations: T("Mara se vraća u pekaru jer je kod kuće primijetila da nešto nije u redu s kupovinom.", "Mara alışverişinde bir sorun olduğunu evde fark ettiği için fırına geri dönüyor.", "Мара повертається до пекарні, бо вдома помітила проблему з покупкою.", "Mara se întoarce la brutărie pentru că acasă a observat o problemă cu cumpărăturile.", "تعود مارا إلى المخبز لأنها لاحظت في المنزل أن هناك مشكلة في مشترياتها.") },
    { id: "b1-s2", position: 2, image_key: "baeck-ill-01", german_text: "Sie erklärt ruhig, dass sie statt Roggenbrot offenbar ein anderes Brot bekommen hat.", translations: T("Mirno objašnjava da je umjesto raženog hljeba očito dobila drugi hljeb.", "Çavdar ekmeği yerine başka bir ekmek aldığını sakin bir şekilde açıklıyor.", "Вона спокійно пояснює, що замість житнього хліба, схоже, отримала інший.", "Explică calm că în loc de pâine de secară pare să fi primit altă pâine.", "تشرح بهدوء أنها حصلت على خبز آخر بدل خبز الجاودار.") },
    { id: "b1-s3", position: 3, image_key: "baeck-ill-08", german_text: "Die Verkäuferin bittet um den Kassenbon, damit sie den Einkauf prüfen kann.", translations: T("Prodavačica traži račun kako bi mogla provjeriti kupovinu.", "Satıcı alışverişi kontrol edebilmek için fişi istiyor.", "Продавчиня просить чек, щоб перевірити покупку.", "Vânzătoarea cere bonul pentru a putea verifica cumpărăturile.", "تطلب البائعة الإيصال كي تتمكن من التحقق من الشراء.") },
    { id: "b1-s4", position: 4, image_key: "baeck-ill-01", german_text: "Mara sagt, dass der Fehler für sie nicht schlimm wäre, wenn sie keine Unverträglichkeit hätte.", translations: T("Mara kaže da greška ne bi bila velika da nema intoleranciju.", "Mara, intoleransı olmasa hatanın çok önemli olmayacağını söylüyor.", "Мара каже, що помилка не була б серйозною, якби не непереносимість.", "Mara spune că greșeala nu ar fi gravă dacă nu ar avea o intoleranță.", "تقول مارا إن الخطأ لن يكون خطيرًا لولا وجود عدم تحمّل غذائي.") },
    { id: "b1-s5", position: 5, image_key: "baeck-ill-03", german_text: "Die Verkäuferin prüft die Angaben und erklärt, welche Zutaten in den betreffenden Produkten enthalten sind.", translations: T("Prodavačica provjerava informacije i objašnjava koji sastojci su u proizvodima.", "Satıcı bilgileri kontrol edip ürünlerde hangi malzemelerin olduğunu açıklıyor.", "Продавчиня перевіряє інформацію й пояснює склад продуктів.", "Vânzătoarea verifică informațiile și explică ingredientele produselor.", "تتحقق البائعة من المعلومات وتشرح مكونات المنتجات.") },
    { id: "b1-s6", position: 6, image_key: "baeck-ill-06", german_text: "Mara fragt nach einer Alternative, die ähnlich schmeckt, aber die problematische Zutat nicht enthält.", translations: T("Mara pita za alternativu sličnog okusa bez problematičnog sastojka.", "Mara benzer tadı olan ama sorunlu içeriği olmayan bir alternatif soruyor.", "Мара просить альтернативу зі схожим смаком, але без проблемного інгредієнта.", "Mara cere o alternativă cu gust asemănător, dar fără ingredientul problematic.", "تسأل مارا عن بديل بطعم مشابه لكن من دون المكوّن المسبب للمشكلة.") },
    { id: "b1-s7", position: 7, image_key: "baeck-ill-06", german_text: "Die Verkäuferin schlägt ein anderes Brot vor und erklärt kurz, warum es besser passen könnte.", translations: T("Prodavačica predlaže drugi hljeb i ukratko objašnjava zašto bi bolje odgovarao.", "Satıcı başka bir ekmek önerip neden daha uygun olabileceğini açıklıyor.", "Продавчиня пропонує інший хліб і пояснює, чому він краще підходить.", "Vânzătoarea propune altă pâine și explică de ce s-ar potrivi mai bine.", "تقترح البائعة خبزًا آخر وتشرح لماذا قد يكون أنسب.") },
    { id: "b1-s8", position: 8, image_key: "baeck-ill-01", german_text: "Mara sagt, dass sie mit dem Vorschlag einverstanden ist, möchte aber sicher sein, dass kein Aufpreis entsteht.", translations: T("Mara se slaže s prijedlogom, ali želi biti sigurna da nema doplate.", "Mara öneriyi kabul ediyor ama ek ücret olmadığından emin olmak istiyor.", "Мара погоджується, але хоче переконатися, що доплати не буде.", "Mara este de acord, dar vrea să fie sigură că nu există cost suplimentar.", "توافق مارا على الاقتراح لكنها تريد التأكد من عدم وجود تكلفة إضافية.") },
    { id: "b1-s9", position: 9, image_key: "baeck-ill-08", german_text: "Die Verkäuferin bestätigt, dass der Umtausch ohne Aufpreis möglich ist.", translations: T("Prodavačica potvrđuje da je zamjena moguća bez doplate.", "Satıcı değişimin ek ücret olmadan mümkün olduğunu doğruluyor.", "Продавчиня підтверджує, що обмін можливий без доплати.", "Vânzătoarea confirmă că schimbul este posibil fără cost suplimentar.", "تؤكد البائعة أن الاستبدال ممكن من دون تكلفة إضافية.") },
    { id: "b1-s10", position: 10, image_key: "baeck-ill-07", german_text: "Das neue Brot wird auf Wunsch geschnitten, damit Mara es zu Hause portionieren kann.", translations: T("Novi hljeb se na zahtjev reže kako bi ga Mara kod kuće mogla podijeliti u porcije.", "Yeni ekmek Mara'nın evde porsiyonlayabilmesi için dilimleniyor.", "Новий хліб нарізають, щоб Мара могла вдома поділити його на порції.", "Noua pâine este feliată pentru ca Mara să o poată porționa acasă.", "يتم تقطيع الخبز الجديد كي تتمكن مارا من تقسيمه في المنزل.") },
    { id: "b1-s11", position: 11, image_key: "baeck-ill-10", german_text: "Am Ende bedankt sich Mara dafür, dass die Situation schnell und freundlich gelöst wurde.", translations: T("Na kraju Mara zahvaljuje što je situacija brzo i ljubazno riješena.", "Sonunda Mara durumun hızlı ve nazikçe çözülmesi için teşekkür ediyor.", "Наприкінці Мара дякує за швидке й ввічливе вирішення ситуації.", "La final, Mara mulțumește pentru rezolvarea rapidă și amabilă.", "في النهاية تشكر مارا على حل المشكلة بسرعة وبلطف.") }
  ],

  vocab: [
    ["der Umtausch", "Nomen", "der", "die Umtausche", "Ist ein Umtausch möglich?", T("zamjena", "değişim", "обмін", "schimb", "استبدال")],
    ["die Unverträglichkeit", "Nomen", "die", "die Unverträglichkeiten", "Ich habe eine Unverträglichkeit.", T("intolerancija", "intolerans", "непереносимість", "intoleranță", "عدم تحمّل")],
    ["die Zutat", "Nomen", "die", "die Zutaten", "Welche Zutaten sind enthalten?", T("sastojak", "malzeme", "інгредієнт", "ingredient", "مكوّن")],
    ["der Aufpreis", "Nomen", "der", "die Aufpreise", "Entsteht ein Aufpreis?", T("doplata", "ek ücret", "доплата", "cost suplimentar", "تكلفة إضافية")],
    ["prüfen", "Verb", null, null, "Könnten Sie das bitte prüfen?", T("provjeriti", "kontrol etmek", "перевірити", "a verifica", "يتحقق")],
    ["bestätigen", "Verb", null, null, "Können Sie das bestätigen?", T("potvrditi", "doğrulamak", "підтвердити", "a confirma", "يؤكد")],
    ["enthalten", "Verb", null, null, "Der Kuchen enthält Nüsse.", T("sadržavati", "içermek", "містити", "a conține", "يحتوي")],
    ["ähnlich", "Adjektiv", null, null, "Gibt es etwas Ähnliches?", T("slično", "benzer", "схожий", "asemănător", "مشابه")],
    ["problematisch", "Adjektiv", null, null, "Das wäre für mich problematisch.", T("problematično", "sorunlu", "проблемний", "problematic", "مشكلة")],
    ["einverstanden sein", "Wendung", null, null, "Damit bin ich einverstanden.", T("slagati se", "kabul etmek", "погоджуватися", "a fi de acord", "يوافق")],
    ["eine Lösung finden", "Wendung", null, null, "Wir finden sicher eine Lösung.", T("naći rješenje", "çözüm bulmak", "знайти рішення", "a găsi o soluție", "إيجاد حل")],
    ["ohne Aufpreis", "Wendung", null, null, "Der Umtausch ist ohne Aufpreis möglich.", T("bez doplate", "ek ücret olmadan", "без доплати", "fără cost suplimentar", "من دون تكلفة إضافية")],
    ["offenbar", "Adverb", null, null, "Ich habe offenbar das falsche Brot bekommen.", T("očigledno", "görünüşe göre", "очевидно", "se pare", "على ما يبدو")],
    ["trotzdem", "Adverb", null, null, "Es war teurer, trotzdem habe ich es genommen.", T("ipak", "yine de", "проте", "totuși", "مع ذلك")],
    ["obwohl", "Konjunktion", null, null, "Obwohl ich wenig Zeit hatte, bin ich zurückgegangen.", T("iako", "-mesine rağmen", "хоча", "deși", "رغم أن")]
  ].map((v, i) => ({ id: `b1-v${i + 1}`, position: i + 1, term: v[0], word_class: v[1], article: v[2], plural: v[3], example: v[4], example_translations: v[5], translations: v[5], collocations: [] })),

  dialog: [
    [1, "Ein Problem erklären", "K", "Kundin", "Guten Tag. Ich war vor etwa einer Stunde hier und glaube, dass ich versehentlich das falsche Brot bekommen habe.", T("Dobar dan. Bila sam ovdje prije otprilike sat vremena i mislim da sam greškom dobila pogrešan hljeb.", "Merhaba. Yaklaşık bir saat önce buradaydım ve yanlışlıkla yanlış ekmeği aldığımı düşünüyorum.", "Добрий день. Я була тут приблизно годину тому й думаю, що помилково отримала не той хліб.", "Bună ziua. Am fost aici acum aproximativ o oră și cred că am primit din greșeală pâinea greșită.", "مرحبًا. كنت هنا قبل نحو ساعة وأعتقد أنني حصلت بالخطأ على الخبز غير الصحيح.")],
    [1, "Ein Problem erklären", "V", "Verkäuferin", "Das tut mir leid. Haben Sie den Kassenbon noch dabei?", T("Žao mi je. Imate li još račun?", "Üzgünüm. Fiş yanınızda mı?", "Мені шкода. У вас є чек?", "Îmi pare rău. Mai aveți bonul?", "آسفة. هل ما زال الإيصال معك؟")],
    [1, "Ein Problem erklären", "K", "Kundin", "Ja, hier ist er. Normalerweise wäre das kein großes Problem, aber ich habe eine Unverträglichkeit.", T("Da, evo ga. Obično to ne bi bio veliki problem, ali imam intoleranciju.", "Evet, burada. Normalde büyük bir sorun olmazdı ama intoleransım var.", "Так, ось він. Зазвичай це не було б великою проблемою, але в мене непереносимість.", "Da, poftiți. În mod normal nu ar fi o problemă mare, dar am o intoleranță.", "نعم، هذا هو. عادةً لن تكون مشكلة كبيرة، لكن لدي عدم تحمّل غذائي.")],
    [1, "Ein Problem erklären", "V", "Verkäuferin", "Verstehe. Ich prüfe sofort, welches Brot auf dem Bon steht.", T("Razumijem. Odmah ću provjeriti koji hljeb piše na računu.", "Anlıyorum. Fişte hangi ekmeğin yazdığını hemen kontrol edeyim.", "Розумію. Я одразу перевірю, який хліб зазначений у чеку.", "Înțeleg. Verific imediat ce pâine apare pe bon.", "أفهم. سأتحقق فورًا من نوع الخبز الموجود على الإيصال.")],
    [1, "Ein Problem erklären", "K", "Kundin", "Könnten Sie bitte auch prüfen, ob das andere Brot Nüsse oder Spuren von Nüssen enthält?", T("Možete li provjeriti sadrži li drugi hljeb orašaste plodove ili tragove?", "Diğer ekmeğin kuruyemiş veya izlerini içerip içermediğini de kontrol edebilir misiniz?", "Можете також перевірити, чи інший хліб містить горіхи або їх сліди?", "Puteți verifica și dacă cealaltă pâine conține nuci sau urme de nuci?", "هل يمكنك أيضًا التحقق مما إذا كان الخبز الآخر يحتوي على مكسرات أو آثار منها؟")],
    [1, "Ein Problem erklären", "V", "Verkäuferin", "Ja. Dieses Brot enthält keine Nüsse, aber es wird in einer Umgebung hergestellt, in der auch Nüsse verarbeitet werden.", T("Da. Ovaj hljeb ne sadrži orašaste plodove, ali se proizvodi gdje se obrađuju i orašasti plodovi.", "Evet. Bu ekmek kuruyemiş içermiyor ama kuruyemiş de işlenen bir ortamda üretiliyor.", "Так. Цей хліб не містить горіхів, але виготовляється там, де їх також обробляють.", "Da. Această pâine nu conține nuci, dar este produsă într-un mediu unde se procesează și nuci.", "نعم. هذا الخبز لا يحتوي على مكسرات، لكنه يُنتج في مكان تُعالج فيه المكسرات أيضًا.")],

    [2, "Eine Lösung aushandeln", "K", "Kundin", "Dann würde ich lieber ein anderes Brot nehmen. Gibt es etwas Ähnliches, das sicherer für mich ist?", T("Onda bih radije uzela drugi hljeb. Ima li nešto slično što je sigurnije za mene?", "O zaman başka bir ekmek tercih ederim. Benim için daha güvenli benzer bir şey var mı?", "Тоді я краще візьму інший хліб. Є щось схоже, але безпечніше для мене?", "Atunci aș prefera altă pâine. Aveți ceva asemănător, dar mai sigur pentru mine?", "إذن أفضل خبزًا آخر. هل يوجد شيء مشابه وأكثر أمانًا بالنسبة لي؟")],
    [2, "Eine Lösung aushandeln", "V", "Verkäuferin", "Ja, ich würde Ihnen dieses Dinkelbrot empfehlen. Es ist ähnlich kräftig, aber laut Zutatenliste ohne Nüsse.", T("Da, preporučila bih ovaj pirov hljeb. Sličnog je jakog okusa, ali prema sastojcima bez orašastih plodova.", "Evet, bu kavuzlu buğday ekmeğini öneririm. Benzer yoğunlukta ama içerik listesine göre kuruyemişsiz.", "Так, раджу цей хліб зі спельти. Він схожий за смаком, але за складом без горіхів.", "Da, vă recomand această pâine de speltă. Are un gust asemănător, dar conform listei de ingrediente nu conține nuci.", "نعم، أوصي بخبز الحنطة. طعمه مشابه، ووفقًا لقائمة المكونات فهو من دون مكسرات.")],
    [2, "Eine Lösung aushandeln", "K", "Kundin", "Das klingt gut. Entsteht beim Umtausch ein Aufpreis?", T("Zvuči dobro. Da li se zamjena dodatno plaća?", "Kulağa iyi geliyor. Değişimde ek ücret var mı?", "Звучить добре. Чи буде доплата при обміні?", "Sună bine. Există un cost suplimentar pentru schimb?", "يبدو جيدًا. هل توجد تكلفة إضافية عند الاستبدال؟")],
    [2, "Eine Lösung aushandeln", "V", "Verkäuferin", "Nein, in diesem Fall nicht. Wir tauschen es ohne Aufpreis um.", T("Ne, u ovom slučaju ne. Zamijenit ćemo ga bez doplate.", "Hayır, bu durumda yok. Ek ücret almadan değiştireceğiz.", "Ні, у цьому випадку ні. Ми обміняємо без доплати.", "Nu, în acest caz nu. Îl schimbăm fără cost suplimentar.", "لا، في هذه الحالة لا. سنستبدله من دون تكلفة إضافية.")],
    [2, "Eine Lösung aushandeln", "K", "Kundin", "Perfekt, danke. Könnten Sie es bitte noch schneiden? Dann kann ich es zu Hause besser portionieren.", T("Odlično, hvala. Možete li ga još narezati? Onda ga kod kuće mogu lakše podijeliti.", "Harika, teşekkürler. Dilimleyebilir misiniz? Böylece evde daha kolay porsiyonlayabilirim.", "Чудово, дякую. Можете ще нарізати? Тоді вдома легше поділю на порції.", "Perfect, mulțumesc. Îl puteți felia? Așa îl pot porționa mai ușor acasă.", "ممتاز، شكرًا. هل يمكنك تقطيعه أيضًا؟ عندها أستطيع تقسيمه في المنزل بسهولة.")],
    [2, "Eine Lösung aushandeln", "V", "Verkäuferin", "Natürlich. Und entschuldigen Sie bitte noch einmal die Verwechslung.", T("Naravno. I još jednom se izvinjavamo zbog zamjene.", "Tabii. Karışıklık için tekrar özür dileriz.", "Звичайно. І ще раз перепрошуємо за плутанину.", "Desigur. Și ne cerem încă o dată scuze pentru confuzie.", "بالطبع. ونعتذر مرة أخرى عن الالتباس.")]
  ].map((d, i) => ({ id: `b1-d${i + 1}`, position: i + 1, dialog_index: d[0], dialog_title: d[1], speaker: d[2], speaker_role: d[3], german_text: d[4], translations: d[5] })),

  questions: [
    { id: "b1-g1", position: 1, kind: "single_choice", section: "grammar", prompt: "Welche Formulierung erklärt ein Problem sachlich und passend für B1?", explanation: "B1 kann ein Problem beschreiben und begründen.", data: H("Koja rečenica jasno objašnjava problem?", "Hangi cümle sorunu açıklar?", "Яке речення пояснює проблему?", "Ce propoziție explică problema?", "أي جملة تشرح المشكلة؟"), quiz_answers: [A("a", "Ich glaube, ich habe versehentlich das falsche Brot bekommen.", true, 1), A("b", "Falsches Brot!", false, 2), A("c", "Ich möchte einen Bus.", false, 3)] },
    { id: "b1-g2", position: 2, kind: "gap_select", section: "grammar", prompt: "___ ich wenig Zeit hatte, bin ich noch einmal zur Bäckerei zurückgegangen.", explanation: "obwohl zeigt einen Gegensatz.", data: { options: ["Obwohl", "Weil", "Damit", "Deshalb"], ...H("iako = obwohl", "-mesine rağmen = obwohl", "хоча = obwohl", "deși = obwohl", "رغم أن = obwohl") }, quiz_answers: [A("a", "Obwohl", true, 1)] },
    { id: "b1-g3", position: 3, kind: "single_choice", section: "grammar", prompt: "Welche Bitte klingt höflich und lösungsorientiert?", explanation: "Konjunktiv II passt gut.", data: H("Koja molba je pristojna?", "Hangi rica nazik?", "Яке прохання ввічливе?", "Care cerere este politicoasă?", "أي طلب مهذب؟"), quiz_answers: [A("a", "Könnten Sie das bitte noch einmal prüfen?", true, 1), A("b", "Prüfen Sie sofort!", false, 2), A("c", "Du musst prüfen.", false, 3)] },
    { id: "b1-g4", position: 4, kind: "single_choice", section: "grammar", prompt: "Welcher Satz enthält einen Relativsatz?", explanation: "Relativsatz: das lange frisch bleibt.", data: H("Koja rečenica ima odnosnu rečenicu?", "Hangi cümlede ilgi cümlesi var?", "Яке речення має відносне підрядне?", "Care propoziție are o relativă?", "أي جملة فيها جملة موصولة؟"), quiz_answers: [A("a", "Ich suche ein Brot, das lange frisch bleibt.", true, 1), A("b", "Ich suche Brot.", false, 2), A("c", "Brot ist frisch.", false, 3)] },
    { id: "b1-u1", position: 20, kind: "single_choice", section: "uebungen", prompt: "Warum ist der Fehler für Mara wichtig?", explanation: "Sie hat eine Unverträglichkeit und muss Zutaten prüfen.", data: H("Zašto je greška važna?", "Hata neden önemli?", "Чому помилка важлива?", "De ce este importantă greșeala?", "لماذا الخطأ مهم؟"), quiz_answers: [A("a", "Weil sie eine Unverträglichkeit hat.", true, 1), A("b", "Weil sie kein Geld hat.", false, 2), A("c", "Weil die Bäckerei geschlossen ist.", false, 3)] },
    { id: "b1-u2", position: 21, kind: "single_choice", section: "uebungen", prompt: "Was möchte Mara vor dem Umtausch wissen?", explanation: "Ob ein Aufpreis entsteht.", data: H("Šta želi znati prije zamjene?", "Değişimden önce ne bilmek istiyor?", "Що хоче знати перед обміном?", "Ce vrea să știe înainte de schimb?", "ماذا تريد أن تعرف قبل الاستبدال؟"), quiz_answers: [A("a", "Ob ein Aufpreis entsteht.", true, 1), A("b", "Wann der Bus kommt.", false, 2), A("c", "Wie alt die Verkäuferin ist.", false, 3)] },
    { id: "b1-u3", position: 22, kind: "sentence_order", section: "uebungen", prompt: "Baue die höfliche Bitte richtig auf.", explanation: "Könnten Sie das bitte noch einmal prüfen?", data: { words: ["Könnten", "Sie", "das", "bitte", "noch", "einmal", "prüfen?"], ...H("Možete li to još jednom provjeriti?", "Bunu bir kez daha kontrol edebilir misiniz?", "Можете перевірити ще раз?", "Puteți verifica încă o dată?", "هل يمكنك التحقق مرة أخرى؟") }, quiz_answers: [] },
    { id: "b1-u4", position: 23, kind: "single_choice", section: "uebungen", prompt: "Welche Reaktion ist lösungsorientiert?", explanation: "Sie nennt eine Alternative und einen Wunsch.", data: H("Koja reakcija traži rješenje?", "Hangi tepki çözüm odaklı?", "Яка реакція орієнтована на рішення?", "Care reacție caută o soluție?", "أي رد يركز على الحل؟"), quiz_answers: [A("a", "Dann würde ich lieber ein anderes Brot nehmen. Gibt es etwas Ähnliches?", true, 1), A("b", "Das ist alles schlecht.", false, 2), A("c", "Ich sage nichts.", false, 3)] },
    { id: "b1-u5", position: 24, kind: "true_false", section: "uebungen", prompt: "Auf B1 kann man kurze Begründungen geben und weniger routinemäßige Probleme bewältigen.", explanation: "Richtig.", data: H("Na B1 možeš objasniti razloge i rješavati manje rutinske probleme.", "B1'de kısa gerekçeler verip rutin olmayan sorunları çözebilirsin.", "На B1 можна коротко обґрунтовувати й вирішувати менш рутинні проблеми.", "La B1 poți da explicații scurte și gestiona situații mai puțin obișnuite.", "في B1 يمكن إعطاء تبريرات قصيرة والتعامل مع مواقف أقل اعتيادًا."), quiz_answers: [A("a", "Richtig", true, 1), A("b", "Falsch", false, 2)] },
    { id: "b1-db1", position: 40, kind: "sentence_order", section: "dialog_builder", prompt: "Dialog bauen: Problem → Beleg → Risiko → Prüfung → Alternative → Aufpreis → Lösung.", explanation: "Ordne die Schritte einer sachlichen Reklamation.", data: { words: ["Kundin: Ich glaube, ich habe das falsche Brot bekommen.", "Verkäuferin: Haben Sie den Kassenbon?", "Kundin: Ja. Wegen meiner Unverträglichkeit ist das wichtig.", "Verkäuferin: Ich prüfe die Zutaten.", "Kundin: Gibt es eine sichere Alternative?", "Verkäuferin: Ich empfehle dieses andere Brot.", "Kundin: Entsteht ein Aufpreis?", "Verkäuferin: Nein, der Umtausch ist ohne Aufpreis möglich.", "Kundin: Dann bin ich damit einverstanden."], ...H("Složi tok reklamacije.", "Şikâyet akışını sırala.", "Упорядкуй скаргу.", "Ordonează reclamația.", "رتّب خطوات الشكوى.") }, quiz_answers: [] },
    { id: "b1-t1", position: 100, kind: "single_choice", section: "test", prompt: "Welche Aussage passt am besten zu B1?", explanation: "B1 erklärt ein Problem und begründet eine Reaktion.", data: H("Koja rečenica najbolje odgovara B1?", "Hangisi B1'e daha uygun?", "Яке речення найбільше відповідає B1?", "Care propoziție corespunde cel mai bine B1?", "أي جملة تناسب B1 أكثر؟"), quiz_answers: [A("a", "Normalerweise wäre das kein Problem, aber wegen meiner Unverträglichkeit muss ich die Zutaten genau prüfen.", true, 1), A("b", "Brot bitte.", false, 2), A("c", "Die makroökonomischen Folgen sind erheblich.", false, 3)] },
    { id: "b1-t2", position: 101, kind: "single_choice", section: "test", prompt: "Was bedeutet „ohne Aufpreis“?", explanation: "Es kostet nicht zusätzlich.", data: H("bez doplate", "ek ücret olmadan", "без доплати", "fără cost suplimentar", "من دون تكلفة إضافية"), quiz_answers: [A("a", "Es entstehen keine zusätzlichen Kosten.", true, 1), A("b", "Es ist doppelt so teuer.", false, 2), A("c", "Es gibt kein Brot.", false, 3)] },
    { id: "b1-t3", position: 102, kind: "single_choice", section: "test", prompt: "Welche Formulierung bittet um Bestätigung?", explanation: "Können Sie bestätigen ...?", data: H("Kako tražiti potvrdu?", "Nasıl teyit istenir?", "Як попросити підтвердження?", "Cum ceri confirmare?", "كيف تطلب تأكيدًا؟"), quiz_answers: [A("a", "Können Sie bestätigen, dass kein Aufpreis entsteht?", true, 1), A("b", "Warum Brot?", false, 2), A("c", "Ich bin Kasse.", false, 3)] },
    { id: "b1-t4", position: 103, kind: "gap_select", section: "test", prompt: "___ ich wenig Zeit hatte, bin ich noch einmal zurückgegangen.", explanation: "obwohl = Gegensatz.", data: { options: ["Obwohl", "Weil", "Damit", "Wenn"], ...H("iako = obwohl", "-mesine rağmen = obwohl", "хоча = obwohl", "deși = obwohl", "رغم أن = obwohl") }, quiz_answers: [A("a", "Obwohl", true, 1)] },
    { id: "b1-t5", position: 104, kind: "single_choice", section: "test", prompt: "Was ist eine sinnvolle Lösung bei einem falschen Produkt?", explanation: "Problem erklären, prüfen, Alternative oder Umtausch vereinbaren.", data: H("Razumna reakcija na pogrešan proizvod?", "Yanlış üründe mantıklı çözüm?", "Розумне рішення при неправильному товарі?", "Soluție rezonabilă pentru produs greșit?", "حل منطقي لمنتج خاطئ؟"), quiz_answers: [A("a", "Den Fehler erklären und nach Umtausch oder Alternative fragen.", true, 1), A("b", "Ohne Erklärung gehen.", false, 2), A("c", "Einfach alles kaufen.", false, 3)] },
    { id: "b1-t6", position: 105, kind: "single_choice", section: "test", prompt: "Welche Bitte klingt am höflichsten?", explanation: "Konjunktiv II.", data: H("Koja molba zvuči najpristojnije?", "En nazik rica hangisi?", "Яке прохання найввічливіше?", "Care cerere este cea mai politicoasă?", "أي طلب هو الأكثر تهذيبًا؟"), quiz_answers: [A("a", "Könnten Sie bitte prüfen, ob das Produkt Nüsse enthält?", true, 1), A("b", "Prüfen!", false, 2), A("c", "Du prüfst jetzt.", false, 3)] },
    { id: "b1-t7", position: 106, kind: "single_choice", section: "test", prompt: "Welcher Satz enthält eine Begründung?", explanation: "weil gibt einen Grund an.", data: H("Koja rečenica sadrži razlog?", "Hangi cümlede gerekçe var?", "Яке речення містить причину?", "Care propoziție conține o explicație?", "أي جملة تحتوي على سبب؟"), quiz_answers: [A("a", "Ich möchte eine Alternative, weil ich eine Unverträglichkeit habe.", true, 1), A("b", "Ich nehme Brot.", false, 2), A("c", "Guten Tag.", false, 3)] },
    { id: "b1-t8", position: 107, kind: "single_choice", section: "test", prompt: "Was bedeutet „offenbar“ in „Ich habe offenbar das falsche Brot bekommen“?", explanation: "Es sieht so aus / anscheinend.", data: H("očigledno / izgleda", "görünüşe göre", "схоже / очевидно", "se pare", "على ما يبدو"), quiz_answers: [A("a", "anscheinend / es sieht so aus", true, 1), A("b", "garantiert immer", false, 2), A("c", "kostenlos", false, 3)] }
  ]
};