export const bakeryB1VisualPlan = [
  { position: 1, image_key: "baeck-b1-01", german_text: "Mara wohnt gegenüber der Bäckerei und kennt sie aus ihrem Alltag gut." },
  { position: 2, image_key: "baeck-b1-02", german_text: "Nach einem langen Tag möchte sie noch schnell etwas fürs Frühstück kaufen." },
  { position: 3, image_key: "baeck-b1-03", german_text: "Sie geht über die Straße in die Bäckerei." },
  { position: 4, image_key: "baeck-b1-04", german_text: "Die Verkäuferin erkennt Mara und begrüßt sie herzlich." },
  { position: 5, image_key: "baeck-b1-05", german_text: "Mara fragt, ob es heute etwas Besonderes oder Neues gibt." },
  { position: 6, image_key: "baeck-b1-06", german_text: "Die Verkäuferin zeigt mehrere Brotsorten und erklärt kurz die Unterschiede." },
  { position: 7, image_key: "baeck-b1-07", german_text: "Mara entscheidet sich für ein dunkles Brot, das lange frisch bleibt." },
  { position: 8, image_key: "baeck-b1-08", german_text: "Die Verkäuferin fragt nach Maras Vorlieben und empfiehlt eine passende Sorte." },
  { position: 9, image_key: "baeck-b1-09", german_text: "Mara erklärt, dass sie bei manchen Produkten wegen einer Unverträglichkeit vorsichtig sein muss." },
  { position: 10, image_key: "baeck-b1-10", german_text: "Sie fragt gezielt, welche Zutaten in einem Kuchen enthalten sind." },
  { position: 11, image_key: "baeck-b1-11", german_text: "Die Verkäuferin prüft die Zutatenliste und erklärt die wichtigsten Bestandteile." },
  { position: 12, image_key: "baeck-b1-12", german_text: "Mara fragt nach einer Alternative ohne die problematische Zutat." },
  { position: 13, image_key: "baeck-b1-13", german_text: "Die Verkäuferin zeigt einen anderen Kuchen und begründet ihre Empfehlung." },
  { position: 14, image_key: "baeck-b1-14", german_text: "Mara vergleicht beide Möglichkeiten und entscheidet sich für die sicherere Variante." },
  { position: 15, image_key: "baeck-b1-15", german_text: "Sie bittet zusätzlich um zwei Brötchen für den nächsten Morgen." },
  { position: 16, image_key: "baeck-b1-16", german_text: "Die Verkäuferin legt alles zusammen und nennt den Gesamtpreis." },
  { position: 17, image_key: "baeck-b1-17", german_text: "Mara merkt, dass der Betrag höher ist als erwartet, und fragt höflich nach." },
  { position: 18, image_key: "baeck-b1-18", german_text: "Die Verkäuferin erklärt, welches Produkt teurer ist und warum." },
  { position: 19, image_key: "baeck-b1-19", german_text: "Mara fragt, ob es eine günstigere Alternative gibt." },
  { position: 20, image_key: "baeck-b1-20", german_text: "Die Verkäuferin schlägt eine günstigere Variante vor, die trotzdem gut passt." },
  { position: 21, image_key: "baeck-b1-21", german_text: "Mara entscheidet sich für die Alternative und bittet um den neuen Gesamtpreis." },
  { position: 22, image_key: "baeck-b1-22", german_text: "Sie bezahlt mit Karte und nimmt den Kassenbon mit." },
  { position: 23, image_key: "baeck-b1-23", german_text: "Zu Hause merkt Mara, dass sie versehentlich das falsche Brot bekommen hat." },
  { position: 24, image_key: "baeck-b1-24", german_text: "Sie vergleicht das Brot mit dem Kassenbon und stellt fest, dass wirklich etwas nicht stimmt." },
  { position: 25, image_key: "baeck-b1-25", german_text: "Mara geht zurück in die Bäckerei und erklärt ruhig, was passiert ist." },
  { position: 26, image_key: "baeck-b1-26", german_text: "Die Verkäuferin bittet um den Kassenbon und prüft den Einkauf." },
  { position: 27, image_key: "baeck-b1-27", german_text: "Mara erklärt, warum das falsche Brot wegen ihrer Unverträglichkeit problematisch ist." },
  { position: 28, image_key: "baeck-b1-28", german_text: "Die Verkäuferin schlägt einen Umtausch ohne Aufpreis vor." },
  { position: 29, image_key: "baeck-b1-29", german_text: "Das richtige Brot wird auf Wunsch geschnitten und neu eingepackt." },
  { position: 30, image_key: "baeck-b1-30", german_text: "Mara bedankt sich für die schnelle Lösung und geht zufrieden nach Hause." },
] as const;
