import { dialogOrder, gap, match, order, sc, sentence, tf, type LevelContent } from "./shared";

export const bankA1: LevelContent = {
  slug: "bank-a1",
  title: "Bei der Bank – erster Bankbesuch (A1)",
  description:
    "Ein einfacher Bankbesuch: Konto eröffnen, Geld abheben, nach dem Weg im Bankgebäude fragen und um Hilfe bitten. Kurze Sätze, einfache Fragen.",

  scenes: [
    { text: "Olga geht zur Bank. Die Bank ist in der Hauptstraße.", hint: "Der Ort steht mit „in“: in der Hauptstraße." },
    { text: "Sie kommt herein und sagt: „Guten Tag!“", hint: "Am Anfang immer grüßen: Guten Tag / Guten Morgen." },
    { text: "„Ich möchte ein Konto eröffnen.“", hint: "„Ich möchte …“ ist höflich. Das zweite Verb steht am Ende." },
    { text: "„Gern. Haben Sie einen Ausweis dabei?“ – „Ja, hier bitte.“", hint: "Ja-Nein-Frage: Das Verb steht auf Position 1." },
    { text: "„Wie ist Ihr Name?“ – „Ich heiße Olga Ivanova.“", hint: "W-Frage mit „Wie“. Antwort: Ich heiße …" },
    { text: "„Wo wohnen Sie?“ – „Ich wohne in Wien, Bahnstraße 4.“", hint: "„Wo?“ fragt nach dem Ort." },
    { text: "Die Beraterin gibt ihr ein Formular. „Bitte unterschreiben Sie hier.“", hint: "Höfliche Bitte mit „bitte“ und Sie-Form." },
    { text: "„Ihre Bankkarte kommt mit der Post.“ – „Wie lange dauert das?“ – „Etwa eine Woche.“", hint: "„Wie lange?“ fragt nach der Zeit." },
    { text: "„Ich möchte Geld abheben. Wo ist der Geldautomat?“", hint: "Geld abheben = Geld aus dem Automaten holen." },
    { text: "„Der Geldautomat ist links neben dem Eingang.“", hint: "„neben“ + Dativ: neben dem Eingang." },
    { text: "Olga steckt die Karte in den Automaten und gibt die PIN ein.", hint: "die PIN eingeben – die vier Zahlen tippen." },
    { text: "Sie hebt 100 Euro ab. Sie nimmt das Geld und die Karte.", hint: "Trennbares Verb: abheben → sie hebt … ab." },
    { text: "„Entschuldigung, ich verstehe nicht. Sprechen Sie bitte langsam.“", hint: "Diese zwei Sätze helfen dir immer weiter." },
    { text: "„Kann ich hier auch Geld einzahlen?“ – „Ja, am Schalter.“", hint: "einzahlen = Geld auf das Konto bringen." },
    { text: "„Vielen Dank für Ihre Hilfe!“ – „Gern. Auf Wiedersehen!“", hint: "Zum Schluss: danken und sich verabschieden." },
  ],

  vocab: [
    { term: "Bank", article: "die", plural: "Banken", word_class: "Nomen", example: "Die Bank ist in der Hauptstraße." },
    { term: "Konto", article: "das", plural: "Konten", word_class: "Nomen", example: "Ich möchte ein Konto eröffnen." },
    { term: "Girokonto", article: "das", plural: "Girokonten", word_class: "Nomen", example: "Das Girokonto ist für Gehalt und Miete." },
    { term: "Bankkarte", article: "die", plural: "Bankkarten", word_class: "Nomen", example: "Meine Bankkarte kommt mit der Post." },
    { term: "Geldautomat", article: "der", plural: "Geldautomaten", word_class: "Nomen", example: "Der Geldautomat ist neben dem Eingang." },
    { term: "Geld", article: "das", plural: "—", word_class: "Nomen", example: "Ich hebe Geld ab." },
    { term: "Bargeld", article: "das", plural: "—", word_class: "Nomen", example: "Ich brauche Bargeld für den Markt." },
    { term: "Ausweis", article: "der", plural: "Ausweise", word_class: "Nomen", example: "Haben Sie einen Ausweis dabei?" },
    { term: "PIN", article: "die", plural: "PINs", word_class: "Nomen", example: "Ich gebe die PIN ein." },
    { term: "Schalter", article: "der", plural: "Schalter", word_class: "Nomen", example: "Am Schalter kann ich Geld einzahlen." },
    { term: "Eingang", article: "der", plural: "Eingänge", word_class: "Nomen", example: "Der Eingang ist an der Hauptstraße." },
    { term: "Wartebereich", article: "der", plural: "Wartebereiche", word_class: "Nomen", example: "Ich warte im Wartebereich." },
    { term: "Formular", article: "das", plural: "Formulare", word_class: "Nomen", example: "Bitte füllen Sie das Formular aus." },
    { term: "Unterschrift", article: "die", plural: "Unterschriften", word_class: "Nomen", example: "Hier fehlt noch Ihre Unterschrift." },
    { term: "Beraterin", article: "die", plural: "Beraterinnen", word_class: "Nomen", example: "Die Beraterin hilft mir." },
    { term: "Quittung", article: "die", plural: "Quittungen", word_class: "Nomen", example: "Möchten Sie eine Quittung?" },
    { term: "Kontonummer", article: "die", plural: "Kontonummern", word_class: "Nomen", example: "Meine Kontonummer steht auf dem Papier." },
    { term: "abheben", word_class: "Verb", example: "Ich hebe hundert Euro ab." },
    { term: "einzahlen", word_class: "Verb", example: "Ich zahle fünfzig Euro ein." },
    { term: "eröffnen", word_class: "Verb", example: "Ich möchte ein Konto eröffnen." },
    { term: "unterschreiben", word_class: "Verb", example: "Bitte unterschreiben Sie hier." },
    { term: "Ich verstehe nicht.", word_class: "Redemittel", example: "Entschuldigung, ich verstehe nicht." },
    { term: "Können Sie mir helfen?", word_class: "Redemittel", example: "Können Sie mir helfen? Ich suche den Automaten." },
  ],

  places: [
    { german_text: "der Eingang", preposition: "an", sentence: "Der Eingang ist an der Hauptstraße." },
    { german_text: "der Informationsschalter", preposition: "neben", sentence: "Der Informationsschalter ist neben dem Eingang." },
    { german_text: "der Geldautomat", preposition: "neben", sentence: "Der Geldautomat steht links neben dem Eingang." },
    { german_text: "der Wartebereich", preposition: "gegenüber", sentence: "Der Wartebereich ist gegenüber dem Schalter." },
    { german_text: "der Schalter", preposition: "hinter", sentence: "Der Schalter ist hinter dem Wartebereich." },
    { german_text: "der Beratungsplatz", preposition: "zwischen", sentence: "Der Beratungsplatz ist zwischen dem Schalter und dem Büro." },
    { german_text: "der Kontoauszugsdrucker", preposition: "an", sentence: "Der Kontoauszugsdrucker hängt an der Wand." },
    { german_text: "die Nummer", preposition: "auf", sentence: "Meine Nummer steht auf dem Bildschirm." },
  ],

  grammar: [
    { title: "Verb auf Position 2", explanation: "Im Aussagesatz steht das konjugierte Verb immer an zweiter Stelle.", examples: ["Ich brauche ein Konto.", "Heute gehe ich zur Bank.", "Am Schalter zahle ich Geld ein."] },
    { title: "W-Fragen in der Bank", explanation: "Mit Wo, Wie, Was und Wie lange bekommst du schnell eine Auskunft. Das Verb steht direkt nach dem Fragewort.", examples: ["Wo ist der Geldautomat?", "Wie lange dauert das?", "Was kostet das Konto?"] },
    { title: "Ja-Nein-Fragen", explanation: "Hier steht das Verb auf Position 1. Die Antwort ist Ja oder Nein.", examples: ["Haben Sie einen Ausweis?", "Ist die Bank heute offen?", "Kann ich hier Geld einzahlen?"] },
    { title: "möchten und können", explanation: "Das Modalverb steht auf Position 2, das zweite Verb im Infinitiv ganz am Ende.", examples: ["Ich möchte ein Konto eröffnen.", "Können Sie mir bitte helfen?", "Ich möchte Geld abheben."] },
    { title: "Akkusativ ganz einfach", explanation: "Nach brauchen, haben und nehmen steht der Akkusativ: der → den, die → die, das → das.", examples: ["Ich brauche einen Ausweis.", "Ich habe eine Bankkarte.", "Ich nehme das Formular."] },
    { title: "Trennbare Verben", explanation: "Bei abheben und einzahlen geht der erste Teil ans Satzende.", examples: ["Ich hebe Geld ab.", "Ich zahle 50 Euro ein.", "Bitte füllen Sie das Formular aus."] },
  ],

  dialogs: [
    {
      title: "Dialog 1 · Geld abheben und nachfragen",
      lines: [
        { speaker: "Olga", role: "Kundin", text: "Guten Tag! Ich möchte Geld abheben." },
        { speaker: "Mitarbeiter", role: "Bankmitarbeiter", text: "Guten Tag! Der Geldautomat ist links neben dem Eingang." },
        { speaker: "Olga", role: "Kundin", text: "Entschuldigung, ich verstehe nicht. Sprechen Sie bitte langsam." },
        { speaker: "Mitarbeiter", role: "Bankmitarbeiter", text: "Natürlich. Der Automat ist dort links. Sehen Sie?" },
        { speaker: "Olga", role: "Kundin", text: "Ah, danke. Wie viel Geld kann ich abheben?" },
        { speaker: "Mitarbeiter", role: "Bankmitarbeiter", text: "Am Automaten bis 500 Euro pro Tag." },
        { speaker: "Olga", role: "Kundin", text: "Gut. Und kann ich hier auch Geld einzahlen?" },
        { speaker: "Mitarbeiter", role: "Bankmitarbeiter", text: "Ja, das geht am Schalter. Bitte nehmen Sie eine Nummer." },
        { speaker: "Olga", role: "Kundin", text: "Vielen Dank für Ihre Hilfe! Auf Wiedersehen." },
      ],
    },
    {
      title: "Dialog 2 · Die Karte funktioniert nicht",
      lines: [
        { speaker: "Olga", role: "Kundin", text: "Entschuldigung, ich habe ein Problem." },
        { speaker: "Beraterin", role: "Beraterin", text: "Guten Tag. Was ist passiert?" },
        { speaker: "Olga", role: "Kundin", text: "Meine Bankkarte funktioniert nicht am Automaten." },
        { speaker: "Beraterin", role: "Beraterin", text: "Zeigen Sie mir bitte die Karte." },
        { speaker: "Olga", role: "Kundin", text: "Hier bitte. Ist die Karte kaputt?" },
        { speaker: "Beraterin", role: "Beraterin", text: "Nein. Die Karte ist alt. Sie bekommen eine neue Karte." },
        { speaker: "Olga", role: "Kundin", text: "Wie lange dauert das?" },
        { speaker: "Beraterin", role: "Beraterin", text: "Etwa eine Woche. Die Karte kommt mit der Post." },
        { speaker: "Olga", role: "Kundin", text: "Alles klar. Vielen Dank!" },
      ],
    },
  ],

  questions: [
    // --- 3 Wo ist was? (8) ---
    sc("places", "Wo ist der Geldautomat?", ["Neben dem Eingang.", "Hinter dem Büro.", "Auf dem Bildschirm."], "„neben“ steht mit Dativ: neben dem Eingang."),
    sc("places", "Wo warten die Kundinnen und Kunden?", ["Im Wartebereich.", "Am Geldautomaten.", "An der Tür."], "Der Wartebereich liegt gegenüber dem Schalter."),
    gap("places", "Der Schalter ist ___ dem Wartebereich.", "hinter", ["hinter", "auf", "zwischen"], "„hinter“ zeigt: der Schalter liegt weiter hinten."),
    gap("places", "Der Beratungsplatz ist ___ dem Schalter und dem Büro.", "zwischen", ["zwischen", "an", "vor"], "„zwischen“ braucht immer zwei Orte."),
    sc("places", "Sie möchten Bargeld einzahlen. Wohin gehen Sie?", ["Zum Schalter.", "Zum Kontoauszugsdrucker.", "In den Wartebereich."], "Bargeld einzahlen geht am Schalter oder an einem Einzahlungsautomaten."),
    gap("places", "Meine Nummer steht ___ dem Bildschirm.", "auf", ["auf", "in", "neben"], "Bei einer Fläche wie einem Bildschirm benutzt man „auf“."),
    sc("places", "Wo hängt der Kontoauszugsdrucker?", ["An der Wand.", "Unter dem Tisch.", "Vor der Tür."], "„an der Wand“ – die Präposition „an“ zeigt Kontakt zu einer senkrechten Fläche."),
    tf("places", "Der Informationsschalter ist neben dem Eingang.", true, "So finden Sie schnell eine erste Auskunft."),

    // --- 6 Grammatik (10) ---
    sc("grammar", "Welcher Satz ist richtig?", ["Ich möchte ein Konto eröffnen.", "Ich ein Konto eröffnen möchte.", "Möchte ich ein Konto eröffnen."], "Modalverb auf Position 2, Infinitiv am Satzende."),
    gap("grammar", "___ ist der Geldautomat?", "Wo", ["Wo", "Wie", "Was"], "„Wo“ fragt nach dem Ort."),
    gap("grammar", "___ lange dauert die neue Karte?", "Wie", ["Wie", "Wo", "Wer"], "„Wie lange“ fragt nach der Zeit."),
    sc("grammar", "Ich brauche ___ Ausweis.", ["einen", "ein", "eine"], "„der Ausweis“ wird im Akkusativ zu „einen Ausweis“."),
    sc("grammar", "Ich habe ___ Bankkarte.", ["eine", "einen", "ein"], "„die Bankkarte“ bleibt im Akkusativ „eine Bankkarte“."),
    sc("grammar", "Welche Frage ist eine Ja-Nein-Frage?", ["Haben Sie einen Ausweis?", "Wo ist der Schalter?", "Wie heißen Sie?"], "Bei Ja-Nein-Fragen steht das Verb auf Position 1."),
    gap("grammar", "Ich ___ hundert Euro ab.", "hebe", ["hebe", "abhebe", "heben"], "abheben ist trennbar: Ich hebe … ab."),
    sentence("grammar", "Bringe die Wörter in die richtige Reihenfolge.", ["Heute", "gehe", "ich", "zur", "Bank"], "Richtig: Heute gehe ich zur Bank. Das Verb bleibt auf Position 2."),
    sc("grammar", "Welche Bitte ist höflich?", ["Können Sie mir bitte helfen?", "Helfen!", "Sie helfen mir jetzt."], "Mit „Können Sie … bitte“ klingt eine Bitte freundlich."),
    tf("grammar", "In dem Satz „Ich zahle 50 Euro ein.“ steht der Verbteil „ein“ richtig am Satzende.", true, "einzahlen ist trennbar: Ich zahle … ein."),

    // --- 7 Übungen (16 handgeschrieben) ---
    sc("practice", "Sie kommen in die Bank. Was sagen Sie zuerst?", ["Guten Tag!", "Wie viel kostet das?", "Auf Wiedersehen."], "Zuerst grüßen – das gehört in Deutschland und Österreich immer dazu."),
    sc("practice", "Sie wollen ein Konto. Was sagen Sie?", ["Ich möchte ein Konto eröffnen.", "Ich möchte Geld abheben.", "Ich suche die Post."], "„Ich möchte …“ nennt höflich Ihr Anliegen."),
    sc("practice", "Die Beraterin fragt: „Haben Sie einen Ausweis dabei?“ Was antworten Sie?", ["Ja, hier bitte.", "Nein, ich heiße Olga.", "Ja, um zehn Uhr."], "Auf eine Ja-Nein-Frage antwortet man mit Ja oder Nein."),
    sc("practice", "Sie verstehen die Mitarbeiterin nicht. Was sagen Sie?", ["Sprechen Sie bitte langsam.", "Das ist zu teuer.", "Ich habe keine Zeit."], "Diese Bitte hilft im Alltag immer weiter."),
    sc("practice", "Was brauchen Sie am Geldautomaten?", ["Die Bankkarte und die PIN.", "Ein Formular und einen Stift.", "Eine Quittung und eine Nummer."], "Ohne Karte und PIN funktioniert der Automat nicht."),
    sc("practice", "Was bedeutet „Geld abheben“?", ["Geld vom Konto holen.", "Geld auf das Konto bringen.", "Geld an eine andere Person schicken."], "Das Gegenteil ist „einzahlen“."),
    sc("practice", "Was bedeutet „einzahlen“?", ["Geld auf das Konto bringen.", "Geld vom Konto holen.", "Eine Karte sperren."], "Einzahlen können Sie am Schalter oder am Einzahlungsautomaten."),
    tf("practice", "Die PIN darf man anderen Personen sagen.", false, "Die PIN ist geheim. Sagen Sie sie niemandem."),
    tf("practice", "Die Bankkarte kommt oft mit der Post nach Hause.", true, "Karte und PIN werden meistens getrennt verschickt."),
    gap("practice", "Ich möchte hundert Euro ___.", "abheben", ["abheben", "einzahlen", "eröffnen"], "Am Automaten holen Sie Geld – das heißt „abheben“."),
    gap("practice", "Bitte ___ Sie hier auf dem Formular.", "unterschreiben", ["unterschreiben", "sprechen", "warten"], "Ihre Unterschrift bestätigt das Formular."),
    order("practice", "Bringe den Bankbesuch in die richtige Reihenfolge.", ["Ich grüße die Mitarbeiterin.", "Ich sage mein Anliegen.", "Ich zeige meinen Ausweis.", "Ich unterschreibe das Formular.", "Ich verabschiede mich."], "So läuft ein einfacher Bankbesuch ab."),
    order("practice", "Bringe die Schritte am Geldautomaten in die richtige Reihenfolge.", ["Ich stecke die Karte in den Automaten.", "Ich gebe die PIN ein.", "Ich wähle den Betrag.", "Ich nehme das Geld.", "Ich nehme die Karte."], "Wichtig: Karte und Geld nie am Automaten liegen lassen."),
    match("practice", "Ordne die Wörter der passenden Erklärung zu.", [["der Geldautomat", "Hier hole ich Bargeld."], ["der Schalter", "Hier spreche ich mit einer Mitarbeiterin."], ["das Formular", "Das fülle ich aus und unterschreibe es."], ["die PIN", "Vier geheime Zahlen für meine Karte."]], "Diese vier Wörter brauchen Sie bei jedem Bankbesuch."),
    match("practice", "Ordne Frage und Antwort zu.", [["Wo ist der Automat?", "Links neben dem Eingang."], ["Wie lange dauert die Karte?", "Etwa eine Woche."], ["Was kostet das Konto?", "Das Konto kostet nichts."], ["Haben Sie einen Ausweis?", "Ja, hier bitte."]], "Achte darauf, welches Fragewort verwendet wird."),
    dialogOrder("practice", "Bringe das kurze Gespräch in die richtige Reihenfolge.", ["Kundin: Guten Tag! Ich möchte Geld abheben.", "Mitarbeiter: Der Geldautomat ist links neben dem Eingang.", "Kundin: Danke. Kann ich hier auch Geld einzahlen?", "Mitarbeiter: Ja, das geht am Schalter.", "Kundin: Vielen Dank! Auf Wiedersehen."], "Erst grüßen, dann das Anliegen, dann die Rückfrage, zum Schluss der Dank."),

    // --- 8 Dialog bauen (2) ---
    dialogOrder("dialog_builder", "Baue den Dialog „Konto eröffnen“ in die richtige Reihenfolge.", [
      "Kundin: Guten Tag! Ich möchte ein Konto eröffnen.",
      "Beraterin: Gern. Haben Sie einen Ausweis dabei?",
      "Kundin: Ja, hier bitte.",
      "Beraterin: Danke. Wo wohnen Sie?",
      "Kundin: Ich wohne in Wien, Bahnstraße 4.",
      "Beraterin: Bitte unterschreiben Sie hier.",
      "Kundin: Wann bekomme ich meine Karte?",
      "Beraterin: In etwa einer Woche mit der Post.",
    ], "Reihenfolge: Gruß, Anliegen, Ausweis, Daten, Unterschrift, Rückfrage, Antwort."),
    dialogOrder("dialog_builder", "Baue den Dialog „Problem mit der Karte“ in die richtige Reihenfolge.", [
      "Kundin: Entschuldigung, ich habe ein Problem.",
      "Beraterin: Guten Tag. Was ist passiert?",
      "Kundin: Meine Karte funktioniert nicht am Automaten.",
      "Beraterin: Zeigen Sie mir bitte die Karte.",
      "Kundin: Hier bitte. Ist die Karte kaputt?",
      "Beraterin: Nein, die Karte ist alt. Sie bekommen eine neue.",
      "Kundin: Wie lange dauert das?",
      "Beraterin: Etwa eine Woche. Auf Wiedersehen!",
    ], "Erst das Problem nennen, dann zeigen, dann die Lösung und die Zeit erfragen."),

    // --- 9 Abschlusstest (26 handgeschrieben + abgeleitete) ---
    sc("test", "Was sagen Sie am Anfang in der Bank?", ["Guten Tag!", "Tschüss!", "Bitte langsam!"], "Zuerst grüßen."),
    sc("test", "Sie möchten ein Konto. Welcher Satz passt?", ["Ich möchte ein Konto eröffnen.", "Ich möchte ein Konto abheben.", "Ich möchte ein Konto einzahlen."], "Ein Konto wird eröffnet."),
    sc("test", "Was brauchen Sie zur Kontoeröffnung?", ["Einen Ausweis.", "Eine Quittung.", "Einen Kontoauszug."], "Ohne Ausweis geht die Kontoeröffnung nicht."),
    sc("test", "Wo geben Sie die PIN ein?", ["Am Geldautomaten.", "Im Wartebereich.", "Auf dem Formular."], "Die PIN gehört nur in den Automaten oder das Kartenlesegerät."),
    sc("test", "„Wie lange dauert das?“ – Welche Antwort passt?", ["Etwa eine Woche.", "In der Hauptstraße.", "Mit der Bankkarte."], "„Wie lange“ fragt nach der Zeit."),
    sc("test", "„Wo wohnen Sie?“ – Welche Antwort passt?", ["In Wien, Bahnstraße 4.", "Ich heiße Olga.", "Um zehn Uhr."], "„Wo“ fragt nach dem Ort."),
    sc("test", "„Wie ist Ihr Name?“ – Welche Antwort passt?", ["Ich heiße Olga Ivanova.", "Ich wohne in Wien.", "Ja, hier bitte."], "„Wie ist Ihr Name?“ fragt nach dem Namen."),
    sc("test", "Sie wollen Bargeld einzahlen. Wohin gehen Sie?", ["Zum Schalter.", "Zum Wartebereich.", "Zum Eingang."], "Einzahlen geht am Schalter."),
    sc("test", "Welcher Satz ist höflich?", ["Können Sie mir bitte helfen?", "Helfen Sie!", "Ich will das jetzt."], "„Können Sie … bitte“ ist die höfliche Form."),
    sc("test", "Was ist eine Unterschrift?", ["Mein Name, mit der Hand geschrieben.", "Meine Kontonummer.", "Meine geheime Zahl."], "Die Unterschrift bestätigt ein Formular."),
    sc("test", "Welches Wort passt: „Ich ___ Geld ab.“", ["hebe", "zahle", "gebe"], "abheben: Ich hebe Geld ab."),
    sc("test", "Welches Wort passt: „Ich ___ Geld ein.“", ["zahle", "hebe", "mache"], "einzahlen: Ich zahle Geld ein."),
    sc("test", "Welcher Satz ist grammatisch richtig?", ["Ich brauche einen Ausweis.", "Ich brauche ein Ausweis.", "Ich brauche eine Ausweis."], "„der Ausweis“ wird im Akkusativ zu „einen Ausweis“."),
    sc("test", "Welcher Satz ist grammatisch richtig?", ["Kann ich hier Geld einzahlen?", "Kann ich hier Geld einzahle?", "Ich kann hier Geld einzahlen?"], "Modalverb auf Position 1, Infinitiv am Ende."),
    sc("test", "Der Automat gibt kein Geld. Was sagen Sie am Schalter?", ["Der Automat funktioniert nicht.", "Ich möchte ein Konto eröffnen.", "Ich habe keine Zeit."], "Beschreiben Sie kurz das Problem."),
    sc("test", "Was ist ein Girokonto?", ["Ein Konto für Gehalt, Miete und Alltag.", "Ein Automat in der Bank.", "Eine geheime Zahl."], "Das Girokonto ist das normale Alltagskonto."),
    tf("test", "Man darf die PIN auf die Bankkarte schreiben.", false, "Nie! Die PIN bleibt geheim und getrennt von der Karte."),
    tf("test", "Am Geldautomaten kann man Geld abheben.", true, "Genau dafür ist der Automat da."),
    tf("test", "„Auf Wiedersehen“ sagt man am Anfang des Gesprächs.", false, "Das sagt man beim Abschied."),
    tf("test", "Ein Formular unterschreibt man mit dem eigenen Namen.", true, "Die Unterschrift bestätigt Ihre Angaben."),
    gap("test", "Wo ___ der Geldautomat?", "ist", ["ist", "sind", "hat"], "„der Geldautomat“ ist Singular: ist."),
    gap("test", "Ich ___ ein Konto eröffnen.", "möchte", ["möchte", "möchten", "mag"], "ich möchte – das zweite Verb steht am Ende."),
    gap("test", "Der Automat ist ___ dem Eingang.", "neben", ["neben", "auf", "über"], "„neben“ + Dativ."),
    gap("test", "Vielen ___ für Ihre Hilfe!", "Dank", ["Dank", "Danke", "Bitte"], "Feste Wendung: Vielen Dank."),
    order("test", "Bringe die Sätze in die richtige Reihenfolge.", ["Guten Tag!", "Ich möchte ein Konto eröffnen.", "Hier ist mein Ausweis.", "Ich unterschreibe das Formular.", "Auf Wiedersehen!"], "So verläuft das Gespräch von der Begrüßung bis zum Abschied."),
    dialogOrder("test", "Bringe das Gespräch am Schalter in die richtige Reihenfolge.", ["Kundin: Guten Tag, ich möchte 50 Euro einzahlen.", "Mitarbeiter: Gern. Haben Sie Ihre Bankkarte dabei?", "Kundin: Ja, hier bitte.", "Mitarbeiter: Danke. Möchten Sie eine Quittung?", "Kundin: Ja, gern. Vielen Dank!"], "Gruß, Anliegen, Karte, Rückfrage, Dank."),
  ],
};
