/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BerufRouteImport } from './routes/beruf'
import { Route as JobBewerbungRouteImport } from './routes/job-bewerbung'
import { Route as LektionenRouteImport } from './routes/lektionen'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as PrivatunterrichtRouteImport } from './routes/privatunterricht'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as JobBewerbungIndexRouteImport } from './routes/job-bewerbung.index'
import { Route as JobBewerbungSlugRouteImport } from './routes/job-bewerbung.$slug'
import { Route as LektionSlugRouteImport } from './routes/lektion.$slug'
import { Route as ThemaSlugRouteImport } from './routes/thema.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BerufRoute = BerufRouteImport.update({
  id: '/beruf',
  path: '/beruf',
  getParentRoute: () => rootRouteImport,
} as any)
const JobBewerbungRoute = JobBewerbungRouteImport.update({
  id: '/job-bewerbung',
  path: '/job-bewerbung',
  getParentRoute: () => rootRouteImport,
} as any)
const LektionenRoute = LektionenRouteImport.update({
  id: '/lektionen',
  path: '/lektionen',
  getParentRoute: () => rootRouteImport,
} as any)
const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatunterrichtRoute = PrivatunterrichtRouteImport.update({
  id: '/privatunterricht',
  path: '/privatunterricht',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JobBewerbungIndexRoute = JobBewerbungIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobBewerbungRoute,
} as any)
const JobBewerbungSlugRoute = JobBewerbungSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JobBewerbungRoute,
} as any)
const LektionSlugRoute = LektionSlugRouteImport.update({
  id: '/lektion/$slug',
  path: '/lektion/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemaSlugRoute = ThemaSlugRouteImport.update({
  id: '/thema/$slug',
  path: '/thema/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/beruf': typeof BerufRoute
  '/job-bewerbung': typeof JobBewerbungRouteWithChildren
  '/lektionen': typeof LektionenRoute
  '/preise': typeof PreiseRoute
  '/privatunterricht': typeof PrivatunterrichtRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/job-bewerbung/$slug': typeof JobBewerbungSlugRoute
  '/lektion/$slug': typeof LektionSlugRoute
  '/thema/$slug': typeof ThemaSlugRoute
  '/job-bewerbung/': typeof JobBewerbungIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/beruf': typeof BerufRoute
  '/lektionen': typeof LektionenRoute
  '/preise': typeof PreiseRoute
  '/privatunterricht': typeof PrivatunterrichtRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/job-bewerbung/$slug': typeof JobBewerbungSlugRoute
  '/lektion/$slug': typeof LektionSlugRoute
  '/thema/$slug': typeof ThemaSlugRoute
  '/job-bewerbung': typeof JobBewerbungIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/beruf': typeof BerufRoute
  '/job-bewerbung': typeof JobBewerbungRouteWithChildren
  '/lektionen': typeof LektionenRoute
  '/preise': typeof PreiseRoute
  '/privatunterricht': typeof PrivatunterrichtRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/job-bewerbung/$slug': typeof JobBewerbungSlugRoute
  '/lektion/$slug': typeof LektionSlugRoute
  '/thema/$slug': typeof ThemaSlugRoute
  '/job-bewerbung/': typeof JobBewerbungIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/beruf'
    | '/job-bewerbung'
    | '/lektionen'
    | '/preise'
    | '/privatunterricht'
    | '/ueber-uns'
    | '/admin'
    | '/dashboard'
    | '/job-bewerbung/$slug'
    | '/lektion/$slug'
    | '/thema/$slug'
    | '/job-bewerbung/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/beruf'
    | '/lektionen'
    | '/preise'
    | '/privatunterricht'
    | '/ueber-uns'
    | '/admin'
    | '/dashboard'
    | '/job-bewerbung/$slug'
    | '/lektion/$slug'
    | '/thema/$slug'
    | '/job-bewerbung'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/beruf'
    | '/job-bewerbung'
    | '/lektionen'
    | '/preise'
    | '/privatunterricht'
    | '/ueber-uns'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/job-bewerbung/$slug'
    | '/lektion/$slug'
    | '/thema/$slug'
    | '/job-bewerbung/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BerufRoute: typeof BerufRoute
  JobBewerbungRoute: typeof JobBewerbungRouteWithChildren
  LektionenRoute: typeof LektionenRoute
  PreiseRoute: typeof PreiseRoute
  PrivatunterrichtRoute: typeof PrivatunterrichtRoute
  UeberUnsRoute: typeof UeberUnsRoute
  LektionSlugRoute: typeof LektionSlugRoute
  ThemaSlugRoute: typeof ThemaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beruf': {
      id: '/beruf'
      path: '/beruf'
      fullPath: '/beruf'
      preLoaderRoute: typeof BerufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-bewerbung': {
      id: '/job-bewerbung'
      path: '/job-bewerbung'
      fullPath: '/job-bewerbung'
      preLoaderRoute: typeof JobBewerbungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lektionen': {
      id: '/lektionen'
      path: '/lektionen'
      fullPath: '/lektionen'
      preLoaderRoute: typeof LektionenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatunterricht': {
      id: '/privatunterricht'
      path: '/privatunterricht'
      fullPath: '/privatunterricht'
      preLoaderRoute: typeof PrivatunterrichtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/job-bewerbung/': {
      id: '/job-bewerbung/'
      path: '/'
      fullPath: '/job-bewerbung/'
      preLoaderRoute: typeof JobBewerbungIndexRouteImport
      parentRoute: typeof JobBewerbungRoute
    }
    '/job-bewerbung/$slug': {
      id: '/job-bewerbung/$slug'
      path: '/$slug'
      fullPath: '/job-bewerbung/$slug'
      preLoaderRoute: typeof JobBewerbungSlugRouteImport
      parentRoute: typeof JobBewerbungRoute
    }
    '/lektion/$slug': {
      id: '/lektion/$slug'
      path: '/lektion/$slug'
      fullPath: '/lektion/$slug'
      preLoaderRoute: typeof LektionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thema/$slug': {
      id: '/thema/$slug'
      path: '/thema/$slug'
      fullPath: '/thema/$slug'
      preLoaderRoute: typeof ThemaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface JobBewerbungRouteChildren {
  JobBewerbungSlugRoute: typeof JobBewerbungSlugRoute
  JobBewerbungIndexRoute: typeof JobBewerbungIndexRoute
}

const JobBewerbungRouteChildren: JobBewerbungRouteChildren = {
  JobBewerbungSlugRoute: JobBewerbungSlugRoute,
  JobBewerbungIndexRoute: JobBewerbungIndexRoute,
}

const JobBewerbungRouteWithChildren = JobBewerbungRoute._addFileChildren(
  JobBewerbungRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BerufRoute: BerufRoute,
  JobBewerbungRoute: JobBewerbungRouteWithChildren,
  LektionenRoute: LektionenRoute,
  PreiseRoute: PreiseRoute,
  PrivatunterrichtRoute: PrivatunterrichtRoute,
  UeberUnsRoute: UeberUnsRoute,
  LektionSlugRoute: LektionSlugRoute,
  ThemaSlugRoute: ThemaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
